Codeinwp/neve

- template-parts/content-page.php
Comments are allowed on pages too. Comment form and replies have the same style as on post pages.
YES
- Open a page
- Edit it, and allow comments on it.
- Check if the comment form appears.
Closes #59
> Allow comments on pages

- inc/core/admin.php
- inc/core/core_loader.php
Onboarding disabled at theme activation. It is accessible from the about page.
Welcome notice added.
> Welcome Notice

- inc/core/admin.php
Onboarding can be opened from the welcome notice button.
NO
- Check the welcome notice button. The onboarding should start by clicking on it.
> Welcome notice updated

- gutenberg/blocks/video/template.json
> Update background image source for Video block

- inc/customizer/controls/ordering.php
- inc/customizer/options/layout_single_post.php
- inc/views/partials/post_meta.php
- inc/views/post_layout.php
- inc/views/template_parts.php
- single.php
- template-parts/content-none.php
- Filters and Hooks added for compatibility with Blog Pro module
- comments added to reorder elements on single post layout
MAYBE (check comments on single post layout)
Related to https://github.com/Codeinwp/neve-pro-addon/issues/36
Should be merged with [this PR](https://github.com/Codeinwp/neve-pro-addon/pull/44).
> Compatibility with Blog Pro module

- inc/core/front_end.php
> chore: remove neve-onboarding-gutenberg

- globals/utilities.php
Retrieve hooks location and names to be used in [Neve Hooks plugin](https://github.com/Codeinwp/neve-hooks/tree/development).
NO
> [WIP] Compatibility with Neve Hooks plugin

- globals/utilities.php
- inc/views/partials/post_meta.php
- views/archive-post.php
> fix: date post meta stripped <time> tags [#494]

- header-footer-grid/Core/Builder/Abstract_Builder.php
- header-footer-grid/templates/header-wrapper.php
contains changes from:
Codeinwp/neve/tree/feature/component_settings
Codeinwp/neve/tree/feature/component_loading
YES/NO
- 
- 
Closes #.
> chore: supporting feature for Codeinwp/neve-pro-addon#72

- inc/admin/metabox/controls/control_base.php
- inc/admin/metabox/main.php
- inc/customizer/options/layout_blog.php
- inc/customizer/options/layout_single_post.php
- inc/views/partials/post_meta.php
- inc/views/post_layout.php
This comes from here: https://github.com/Codeinwp/neve-pro-addon/issues/57#issuecomment-483164998
> chore: remove priority argument from meta and add it to settings array

- header-footer-grid/Core/Components/SecondNav.php
- header-footer-grid/Main.php
- inc/core/admin.php
- inc/core/front_end.php
added filter for registering custom nav
and suporting changes that reference: Codeinwp/neve-pro-addon#73
hiding widgets area, references: #507
sync with `development` branch
User: bogdan.preda@themeisle.com <Bogdan Preda>
> chore: supporting changes and fixes

- header-footer-grid/Core/Components/CustomHtml.php
- header-footer-grid/Core/Components/Logo.php
- header-footer-grid/Core/Components/Nav.php
- header-footer-grid/Core/Components/NavFooter.php
- header-footer-grid/Core/Components/SecondNav.php
Change the default header footer builder components width
NO
Closes #705 .
> [HFG] Default components width

- inc/core/admin.php
- inc/core/front_end.php
Change notice image and starter sites order based on the previous theme
NO
Closes #379 .
> Starter sites order

- inc/core/front_end.php
Allow proper content width
NO
- Check that images from imported  Elementor templates have proper `sizes` attribute
Closes #695.
> Larger Content Width

- header-footer-grid/Core/Components/Abstract_Component.php
- inc/compatibility/amp.php
- inc/views/header.php
Fixed nav search on amp
NO
Closes #710.
> fix: #710 - nav search field hides on click

- inc/core/front_end.php
^^^Title^^^
NO
- Add video embeds to a page / post
Closes #761.
cc @stefan-cotitosu
> fix: add support for responsive embeds

- inc/customizer/controls/react/package.json
Removes dependencies for react controls that weren't used. 
NO
Closes #749. Closes #748
> Removes unused dependencies

- 404.php
- inc/core/core_loader.php
- inc/views/content_404.php
- inc/views/content_none.php
Moved 404 page to its template to be able to replace it in custom layouts module
NO
> move 404 page to a separate file

- 404.php
- inc/core/core_loader.php
- inc/views/content_404.php
- inc/views/content_none.php
Moved 404 page to its template to be able to replace it in custom layouts module
NO
> Moved 404 page to a separate file

- functions.php
- inc/views/partials/excerpt.php
Fixed the issue with Otter content not being displayed on the blog when the excerpt is 300.
NO
Use the development version of Otter
Closes #753.
> Excerpt fix

- cypress/integration/customizer/container-settings.spec.js
- cypress/integration/customizer/hfg-row-background.spec.js
- cypress/integration/editor/post-page-metabox.spec.js
- cypress/support/commands.js
Adds e2e tests for the Post and Page meta box and container customize settings. Also improves 
NO
Related to Codeinwp/neve-pro-addon#299.
> E2E Container settings | E2E Post / Page meta box options

- inc/customizer/options/layout_blog.php
- inc/views/inline/blog.php
- inc/views/inline/front_end_style_manager.php
Added box shadow for post thumbnails
NO
Closes #805.
> Blog box shadow

- inc/core/front_end.php
> chore: make sure that plugins.php file is loaded where needed

- inc/customizer/controls/react/bundle/controls.css
- inc/customizer/controls/react/src/style.scss
> chore: additional typography control tweaks on wp 5.3

- inc/core/front_end.php
Adds possibility to use divi starter sites.
NO
cc @rodica-andronache
> chore: adds first divi site [codeinwp/neve-pro-addon#423]

- inc/core/front_end.php
> fix: wrapping Jetpack video embeds for proper aspect ratio

- header-footer-grid/Core/Components/Button.php
Adds button component styles.
NO
- Check component  style control
Closes #1062.
> feat: adds style controls to button builder component [closes #1062]

- header-footer-grid/Core/Components/Button.php
Transform button into a mergeable component.
It also adds a margin of 20px to the left of the component.
NOt sure
- Buttons should merge with other components. 
- They should have margin-left 20px by default.
Closes #1095.
> chore: make button into mergeable component [closes #1095]

- inc/views/inline/base_inline.php
Fixes notice.
NO
Closes #1275.
> fix: notice from array offset in responsive style method [closes #1275]

- header-footer-grid/Core/Components/MenuIcon.php
Changes for this PR: https://github.com/Codeinwp/neve-pro-addon/pull/549
NO
- To be tested with this PR: https://github.com/Codeinwp/neve-pro-addon/pull/549
- Should work fine with older plugin versions
Closes Codeinwp/neve-pro-addon#531.
> feat: adapts for second menu icon component

- header-footer-grid/templates/footer-row-wrapper.php
- header-footer-grid/templates/footer-wrapper.php
Adaptations for this PR: https://github.com/Codeinwp/neve-pro-addon/pull/561
NO
- Test with this PR: https://github.com/Codeinwp/neve-pro-addon/pull/561
Ref: Codeinwp/neve-pro-addon#537.
> chore: adapts for sticky footer [Codeinwp/neve-pro-addon#537]

- inc/core/admin.php
Remove the dashboard widget when Neve is installed
> fix: hide dashboard widget when Neve is active, fix #1277

- header-footer-grid/Core/Components/CartIcon.php
> chore: style not added properly for CartIcon component [ref #1370]

- inc/views/inline/gutenberg_editor.php
Fixes visual issues inside the editor when.
NO
- Install Gutenberg and WordPress RC5 (or the latest 5.4 version)
- See if everything works fine inside the editor
Closes #1404.
> fix: issues in Gutenberg on 5.4 with the plugin installed

- inc/views/header.php
Amp search as last menu item is broken on latest release https://app.diffy.website/#/diffs/26877/single/14/1440
Yes
> fix amp search as last menu item

- header-footer-grid/Core/Components/CartIcon.php
Fix the cart icon size in the customizer.
NO
Closes Codeinwp/neve-pro-addon#714.
> Fix cart icon size

- .github/workflows/test-e2e.yml
- cypress/integration/customizer/general/color-control.spec.js
- cypress/support/commands.js
Adds cypress test for color control on body text.
Closes codeinwp/neve-pro-addon#679.
> test: adds test for color control [ref codeinwp/neve-pro-addon#679]

- inc/views/page_header.php
Fixed the issue with the account page not displaying the current tab title
NO
Closes https://github.com/Codeinwp/neve-pro-addon/issues/666
😈😈😈
> Fix My account page title

- globals/hooks.php
- globals/utilities.php
- header.php
Changed the position for neve_after_header_hook and neve_before_header_hook outside the header tag and add neve_after_header_content_hook and neve_before_header_content_hook hooks inside the tag
NO
Closes #1635.
> Hook placement

- .github/workflows/test-e2e.yml
- bin/run-e2e.sh
- cypress/integration/dashboard/changelog.spec.js
- cypress/integration/dashboard/general.spec.js
- cypress/integration/dashboard/starter-sites.spec.js
- cypress/integration/dashboard/useful-plugins.spec.js
- cypress/package-lock.json
- cypress/package.json
ref: Codeinwp/themeisle-onboarding#2
> chore: adds dashboard cypress tests

- inc/customizer/base_customizer.php
Live refresh for spacing control ( padding, margin etc.)
NO
> fix: live refresh for spacing controls

- header-footer-grid/Core/Components/CartIcon.php
Cart icon color fix
NO
Closes #1888
> Fix cart icon color

- inc/views/post_layout.php
- inc/views/template_parts.php
> typecast the meta order

- header-footer-grid/Core/Components/CartIcon.php
- header-footer-grid/templates/components/component-cart-icon.php
Fix for cart icon
NO
Closes #Codeinwp/neve-pro-addon#832
> Fix for cart icon if woo booster is deactivated

- inc/core/front_end.php
Enqueue front-end scripts async
NO
> Enqueue js async [neve-pro-addon/#855]

- header-footer-grid/Core/Components/Abstract_Component.php
Adds the footer components responsive UI
NO 
Closes #2034.
> chore: show responsive switches for footer components

- inc/admin/metabox/manager.php
Closes #Codeinwp/neve-pro-addon#918.
> Fix close span tag for the message in meta

- inc/compatibility/lifter.php
Changed the hooks for the wrappers so they will be visible when using shortcodes too.
Closes Codeinwp/neve-pro-addon#874.
> Fix lifter lms shortcodes

- inc/core/admin.php
Change plugin names for Orbit Fox and Otter when installed with Neve.
NO
Closes Codeinwp/neve-pro-addon#968.
> Change pugin names

- inc/customizer/options/main.php
Change the Hompage Settings section location to Layout panel.
NO
Closes #https://github.com/Codeinwp/neve-pro-addon/issues/983
> chore: move homepage settings section [#983]

- inc/compatibility/woocommerce.php
- inc/core/settings/config.php
- inc/customizer/options/typography.php
Control headings on checkout from h3 options and not from body options.
NO
Closes #2167.
> Checkout font size

- inc/admin/metabox/manager.php
Made sure is_block_editor() is available.
NO
Closes #2254
> fix: fatal error when using Visualizer #2254

- cypress/integration/customizer/typography/font-family.spec.js
- inc/admin/metabox/manager.php
Made sure is_block_editor() is available.
NO
Closes #2254
> Fix fatal error when using Visualizer

- composer.json
- composer.lock
- dashboard/inc/Main.php
Fixes issue with composer >= 2.0 requiring PHP >= 7.1
NO
> fix: composer requiring php >=7.1.0

- cypress/.prettierrc.json
- cypress/integration/amp/amp-test.spec.js
- cypress/integration/customizer/general/order-control.spec.js
- cypress/integration/customizer/hfg/hfg-alignment-control.spec.js
- cypress/integration/customizer/hfg/hfg-margin-control.spec.js
- cypress/integration/customizer/hfg/hfg-padding-control.spec.js
- cypress/integration/customizer/hfg/hfg-row-background.spec.js
- cypress/integration/customizer/layout/container-settings.spec.js
- cypress/integration/customizer/layout/sidebar-settings.spec.js
- cypress/integration/customizer/typography/blog-typography.spec.js
- cypress/support/commands.js
- package.json
- yarn.lock
- Refactors aliasRestRoutes() function to a Cypress command to reduce duplicated code;
- Adds Prettier for cypress to standardize the code style.
NO
> Adds Prettier for cypress folder and move aliasRestRoutes() function to a Cypress command

- inc/views/partials/post_meta.php
Fix {meta_author} magic tag notice on 404 page.
NO
Closes #2478.
> fix: notice of {meta_author} on the 404 page [#2478]

- CONTRIBUTING.md
Adds how to run Cypress tests with Docker on the CONTRIBUTING.md
NO
Closes #2557
> docs: add a section for running tests with Cypress and Docker

- inc/compatibility/web_stories.php
- inc/core/core_loader.php
Adds integration with Google Web Stories 
https://share.getcloudapp.com/qGuXqNDq
> feat: adds compatibility with webstories.

- .gitignore
- composer.json
- composer.lock
- dashboard/src/utils/rest.js
- functions.php
- package.json
- phpcs.xml
- readme.txt
- yarn.lock
Adds compatibility with lint-staged.
Fix PHP compatibility inconsistency.
> Improve build and tooling

- composer.lock
- header-footer-grid/Core/Builder/Abstract_Builder.php
Fix issue with uasort incorrect usage on PHP 8.0
No
See #2603 
Closes #2603
> fix: issue triggered by incorect usage of uasort on PHP, fix #2603

- inc/customizer/controls/react/src/common/Responsive.js
- languages/neve.pot
> fix: responsive switches in customizer [closes #2646]

- assets/js/src/frontend/blog.js
- inc/views/pluggable/masonry.php
- languages/neve.pot
There were some naming issues that prevented the masonry script to run.
NO
- Go to Customizer -> Layout ->  Blog/Archive 
- Set the layout on grid or covers ( test it with both )
- Set at least 2 grid columns
- Activate masonry
- Test if masonry works with both pagination type ( page / infinite scroll )
> Masonry on blog

- e2e-tests/cypress/integration/dashboard/useful-plugins.spec.ts
Fix flakiness on useful plugin spec.
NO
- The pipeline should pass
- 
Closes #2682
> Fix cypress useful plugin flakiness

- .github/workflows/build-dev-artifacts.yml
- docker-compose.ci.yml
Removes shared volume in docker-compose for e2e tests
NO
- Tests should pass
- 
Closes #2694
> chore: removes shared volume for e2e tests

- e2e-tests/cypress/fixtures/customizer/hfg/hfg-copyright-component-setup.json
- e2e-tests/cypress/integration/customizer/hfg/hfg-copyright-component.spec.ts
Adds a test for the copyright footer component
NO
- Pipeline should not fail
Closes #2769 .
> test: adds copyright-component tests

- .github/workflows/build-dev-artifacts.yml
- bin/envs/woo-sample/start.sh
- e2e-tests/cypress/fixtures/woocommerce/button-setup.json
- e2e-tests/cypress/integration/woocommerce/button.spec.ts
- e2e-tests/cypress/integration/woocommerce/example.spec.ts
Adds the woocommerce environment for testing
Adds a test for the Primary and Secondary Button
NO
- Tests should pass the pipeline
Closes #2776 .
> Adds a test for the buttons

- inc/views/pluggable/metabox_settings.php
Adds meta association on template import/export
Closes #2790
> feat: adds compatibility with TPC meta association

- .github/ISSUE_TEMPLATE/Automated_test.md
- .github/ISSUE_TEMPLATE/Feature_request.md
NO
- When creating a new issue, the updated template should appear
Closes #2831
> style: updates issue templates

- e2e-tests/cypress/fixtures/customizer/form-fields/form-fields-setup.json
- e2e-tests/cypress/fixtures/customizer/layout/sidebar-settings.json
- e2e-tests/cypress/integration/customizer/form-fields/form-fields.spec.ts
Adds a test for the form-fields
NO
- Tests should pass the pipeline
Closes #2855 .
> Adds a test for the form fields

- assets/js/src/customizer-preview/app.js
- assets/scss/lifter.scss
- inc/compatibility/lifter.php
- inc/core/styles/frontend.php
Seems like lifter had an option to add a sidebar on catalog pages, I've made the changes so that would work ok.
YES
- Install LifterLMS
- Import courses from their wizard
- Try to add a sidebar
> Fix for lifter sidebar

- .github/ISSUE_TEMPLATE/Automated_test.md
- .github/ISSUE_TEMPLATE/Feature_request.md
Updates the feature request template to include that the QA team will fill the fields of Checklist Scenario, User Story, and Test Instructions.
NO
- The template that appears when creating a new issue should be updated.
Closes #2949
> chore: updates feature request template

- inc/admin/metabox/manager.php
- inc/admin/metabox/src/components/MetaFieldsManager.js
- inc/views/pluggable/metabox_settings.php
The filter that checks the single post meta needs to run after all other conditions. I just increased the priority argument and the problem should be fixed now.
NO
- Check if the author avatar works from the customizer
- Check if changing the author avatar display from single post options works 
Closes #2929.
> Fix author avatar display

- assets/js/src/frontend/navigation.js
- assets/scss/components/elements/_mega-menu.scss
- assets/scss/customizer-preview.scss
- assets/scss/elements/_mega-menu.scss
- assets/scss/mega-menu-legacy.scss
- grunt/cssmin.js
- grunt/rtlcss.js
- grunt/sass.js
- inc/views/nav_walker.php
Mega menu alignment inline script fix
@abaicus Let me know how it works and what you think about this.
It feels hacky, should I compile it and enqueue the build instead of inline as it is now? What do you think?
Thank you!
> fix: mega-menu inline script fix

- inc/compatibility/block-patterns/four-columns-team-members.php
- inc/compatibility/block-patterns/light-header-left-aligned-content.php
- inc/compatibility/block-patterns/three-columns-images-texts-content.php
I updated the indicated templates according to the code @mghenciu provided on Notion
NO
- Add the following patterns to a page or post:
1. Light header with left-aligned content
2. Three columns with images, content and buttons
3. Four columns with team members
- Check if everything works on frontend and backend
Closes #2891.
> Fix block template

- assets/scss/components/compat/woocommerce/_generic.scss
> Revert "Fix round sale tag"

- e2e-tests/cypress/fixtures/woocommerce/header-mini-cart.json
- e2e-tests/cypress/integration/woocommerce/header-mini-cart.ts
- e2e-tests/cypress/support/commands.ts
- e2e-tests/package.json
- e2e-tests/tsconfig.json
- e2e-tests/yarn.lock
Adds a spec for testing the functionality and style changes on header mini cart, for mobile and desktop versions.
NO
- Tests should pass the pipeline
Closes #2969
> test: adds tests for mini cart

- assets/js/src/frontend/hgf.js
- assets/js/src/frontend/navigation.js
- assets/js/src/shop/app.js
- assets/js/src/utils.js
- assets/scss/components/elements/navigation/_nav-menu.scss
- assets/scss/components/main/_a11y.scss
- assets/scss/elements/navigation/_nav-menu.scss
- globals/utilities.php
- header-footer-grid/Core/Components/Nav.php
- header-footer-grid/templates/components/component-nav.php
- header-footer-grid/templates/components/component-search-responsive.php
- header-footer-grid/templates/row-wrapper-mobile.php
- header.php
- inc/compatibility/amp.php
- inc/views/header.php
- inc/views/nav_walker.php
- package.json
- rollup.config.js
- yarn.lock
* Adds focus trap mechanism
* Improve CSS to allow keyboard navigation
* remove tabindex where is not necessary
* Improve rollup config
* update caniuse-lite db
Closes #3087, also fixes https://github.com/Codeinwp/neve/issues/3074 https://github.com/Codeinwp/neve/issues/2934 https://github.com/Codeinwp/neve/issues/2906 https://github.com/Codeinwp/neve-pro-addon/issues/1436
> fix: accesibility issues

- assets/js/src/frontend/hgf.js
- assets/js/src/frontend/navigation.js
- assets/js/src/shop/app.js
- assets/js/src/utils.js
- assets/scss/components/editor/_typography.scss
- assets/scss/components/elements/navigation/_nav-menu.scss
- assets/scss/components/main/_a11y.scss
- assets/scss/components/main/_typography.scss
- assets/scss/elements/navigation/_nav-menu.scss
- globals/utilities.php
- header-footer-grid/Core/Components/Nav.php
- header-footer-grid/templates/components/component-nav.php
- header-footer-grid/templates/components/component-search-responsive.php
- header-footer-grid/templates/row-wrapper-mobile.php
- header.php
- inc/compatibility/amp.php
- inc/views/header.php
- inc/views/nav_walker.php
- package.json
- page-templates/template-pagebuilder-full-width.php
- rollup.config.js
- searchform.php
- woocommerce/product-searchform.php
- yarn.lock
* In the woocommerce/product-searchform.php: Hard-coded search form replaced with the `get_search_form()` function
NO
https://vertis.d.pr/TvNBDq
- Make sure "product-searchform.php" template works well. it can be used with calling the `get_product_search_form() ` function on any hook. I don't know how we can activate this search template on WP admin.
You can use a snippet to show it:
`add_action('neve_before_sidebar_content', function(){
get_product_search_form();
});`
Closes #3087.
> Some fixes that reported by trac#105195

- assets/apps/customizer-controls/src/builder/components/Builder.tsx
Fixes the problem with the footer that becomes hidden when components are update inside of it.
NO
- Go to Footer builder
- Add new component
- The footer should still be visible
Closes #3080.
> fix: footer is not hidden after components update [#3080]

- inc/views/pluggable/pagination.php
add hooks in the nv/v1/posts REST endpoint to show hooks in the dynamic elements of the blog archive infinite scroll.
YES
- add snippets for the hooks(neve_loop_entry_before, neve_loop_entry_after)
- enable infinite scroll for blog archive
- make sure your snippet works well on the static and dynamic loaded elements of the infinite scroll.
Closes #3095.
> hooks added in the nv/v1/posts REST endpoint for dynamic elements of the infinite scroll

- assets/scss/components/elements/blog/_single.scss
- inc/core/settings/config.php
- inc/core/styles/frontend.php
- inc/customizer/options/layout_single_post.php
- inc/views/pluggable/metabox_settings.php
- inc/views/post_layout.php
Fix issue with title not aligning properly horizontally.
NO
1. Create a Neve Free instance
2. Add a post and open Customizer
3. Try to choose different alignments for the title in Single Post
Closes #3158 #3172.
> fix: solved post title alignment and cover defaults #3158

- assets/customizer/css/_generic.css
Fixes double scrollbar in customizer
NO
- Check if issue is fixed
- Navigate in customizer to see if anything broke
Closes #3216.
> Fix double scroll

- .github/workflows/test-php.yml
YES/NO
- 
- 
Closes Codeinwp/neve-pro-addon#1717.
> phpunit polyfills dependencies package

- header-footer-grid/Core/Builder/Abstract_Builder.php
Added the divider component.
This PR is linked to https://github.com/Codeinwp/neve-pro-addon/pull/1622.
NO
- Test instructions are described in the PR mentioned above.
Closes Codeinwp/neve-pro-addon#1564.
> Feat: Divider component

- .github/workflows/build-dev-artifacts.yml
- .github/workflows/deploy-storybook.yml
- .github/workflows/deploy.yml
- .github/workflows/e2e-storybook.yml
- .github/workflows/sync-qa.yml
- .github/workflows/trigger-visual-on-comment.yml
- package.json
- yarn.lock
ci: setup node version in CI
ci: upgrade node-sass
> ci: setup node version in CI

- assets/apps/customizer-controls/src/controls.js
- assets/js/src/customizer-preview/app.js
- inc/core/settings/config.php
- inc/core/styles/frontend.php
- inc/customizer/defaults/layout.php
- inc/customizer/defaults/single_post.php
- inc/customizer/options/layout_blog.php
- inc/customizer/options/layout_container.php
- inc/customizer/options/layout_sidebar.php
- inc/customizer/options/layout_single_post.php
- inc/views/cover_header.php
- inc/views/layouts/layout_container.php
- inc/views/layouts/layout_sidebar.php
- inc/views/partials/post_meta.php
- inc/views/post_layout.php
- start.php
> Revert "Feat: custom post and archive enhancements"

- .github/workflows/test-php.yml
the composer version was downgraded to v1 in phplint Github Action.
NO
- Make sure all php Github action tests works well.
Closes #3290 .
> downgrade composer version from latest to v1 on phplint Github Action.

- inc/customizer/controls/react/builder_columns.php
- inc/customizer/controls/react/button_appearance.php
- inc/customizer/controls/react/color.php
- inc/customizer/controls/react/font_family.php
- inc/customizer/controls/react/global_colors.php
- inc/customizer/controls/react/inline_select.php
- inc/customizer/controls/react/logo_palette.php
- inc/customizer/controls/react/multiselect.php
- inc/customizer/controls/react/nr_spacing.php
- inc/customizer/controls/react/ordering.php
- inc/customizer/controls/react/presets_selector.php
- inc/customizer/controls/react/radio_buttons.php
- inc/customizer/controls/react/radio_image.php
- inc/customizer/controls/react/range.php
- inc/customizer/controls/react/repeater.php
- inc/customizer/controls/react/responsive_radio_buttons.php
- inc/customizer/controls/react/responsive_range.php
- inc/customizer/controls/react/responsive_toggle.php
- inc/customizer/controls/react/rich_text.php
- inc/customizer/controls/react/spacing.php
- inc/customizer/controls/react/typography.php
Updated `to_json` deprecated methods to `json` methods
NO
- Ensure all customizer panels load fine and there's no errors on customizer controls
Closes #2912
> refactor: change deprecated to_json methods to json

- assets/scss/compat/_elementor.scss
- assets/scss/components/compat/_elementor.scss
- package.json
Allows scroll snapping to work with Elementor 
NO
- Create a page with sections using Elementor
- Enable the Scroll Snap feature: https://www.youtube.com/watch?v=Mc7Z_EwieWM&ab_channel=Elementor
- Try to scroll the sections on the frontend.
Closes #3255
> fix: scroll snap bug in elementor

- header-footer-grid/Core/Settings/Defaults.php
Fixes PHP 8.1 error and notices
YES
- There should no notice or error on the php 8.1
Closes https://github.com/Codeinwp/neve/issues/3280.
> Fixes 8.1 errors

- inc/views/page_header.php
- Add an additional check to make sure the title only hides on pages if the cover is selected.
YES
- Import a starter site
- Change the title layout on **Page** ( not posts as I did )
- Check the post archives ( categories, author archive )
Closes #3450.
> Fix archive missing title

- assets/apps/dashboard/src/Components/ModuleCard.js
- assets/apps/dashboard/src/Components/Notification.js
- inc/admin/dashboard/main.php
- inc/core/admin.php
This adds the Otter Pro transition to Neve Pro Addon alongside this PR: https://github.com/Codeinwp/neve-pro-addon/pull/1946
Details on how the migration path works are laid down here: https://github.com/Codeinwp/neve-pro-addon/issues/1925
A couple of notifications will appear in Dashboard if the user is using an older version of Otter Blocks.
- Please follow this: https://github.com/Codeinwp/neve-pro-addon/issues/1925 and
- this: https://github.com/Codeinwp/otter-blocks/pull/769
Closes https://github.com/Codeinwp/neve-pro-addon/issues/1925.
> [Wip] Feat/otter pro

- e2e-tests/cypress/support/commands.ts
Fix E2E classic editor test
Closes #3493.
> fix: e2e test

- start.php
NEVE_COMPATIBILITY_FEATURES has been updated for Sparks compatibility.
NO
- There should not be any regression.
Closes #3531 .
> fix: missing sparks compatibility constant key added

- assets/scss/components/elements/navigation/_nav-menu.scss
- assets/scss/components/elements/navigation/_nav-styles.scss
- inc/views/nav_walker.php
Fixes hover modes for HFG navigation components.
NO
- Check all the hover modes of nav components - Footer Nav / Primary Nav / Secondary Nav;
- All hover modes should work fine. Both in the sidebar, and in the desktop header rows;
- Mega menu should work fine as well;
Closes #3529.
> fix: issues with nav hover modes [closes #3529]

- theme.json
YES - fixing some issues sites might have had because of the `theme.json` file.
- Not much to test, honestly. This just reverts the changes made for #3485.
Closes #3543.
> chore: remove theme.json file [closes #3543]

- page.php
Send a different context  for woocommerce special pages
NO
Closes Codeinwp/neve-pro-addon#2100
> fix: update context on page

- assets/scss/components/elements/_hfg-alignments.scss
- header-footer-grid/Core/Builder/Abstract_Builder.php
- inc/views/nav_walker.php
Dropdown items respect sidebar alignment control.
NO
1. Have a menu with dropdowns
2. Change the sidebar alignment
3. Check that all items respect the alignment.
Closes #3593.
> fix: items alignment on sidebar

- assets/apps/dashboard/src/Components/Content/Start.js
Unused JS constant has been removed to fix GH Action failing.
NO
- All GH actions & E2E tests should be green.
Closes #3601.
> refactor: unused js constant has been removed

- assets/apps/customizer-controls/src/customizer-search/SearchComponent.tsx
- assets/apps/customizer-controls/src/customizer-search/SearchResults.tsx
Tried to fix the issue and it seems it works this way.
@preda-bogdan maybe you can have a look and see if this would be an acceptable fix.
> fix: section is not focusing properly

- assets/scss/components/editor/_typography.scss
- header-footer-grid/templates/components/component-nav.php
Missing variable in code + custom layout PHP editor style update
NO
Closes #3616.
> fix: missing variable [#3616]

- assets/scss/components/elements/_form-elements.scss
- assets/scss/components/elements/navigation/_nav-search.scss
- header-footer-grid/Core/Components/Search.php
- inc/core/settings/config.php
The height property for the input was not applied on submit button.
NO
- Test if the issue is fixed
- Test how other settings (form settings, button settings) are influencing the input and if the style breaks if different values are set to those inputs
Closes Codeinwp/neve-pro-addon#2168.
> Search icon component input fix

- assets/scss/components/compat/woocommerce/_cart.scss
- assets/scss/components/compat/woocommerce/_checkout.scss
- inc/compatibility/woocommerce.php
- Remove style for fieldset inside payment box
- Add padding for rows inside a fieldset
YES
- install Stripe plugin and log-in with the credentials I provided in PM
- see the checkbox described in the issue
Closes #3599.
> fix: checkout fieldset [#3599]

- inc/core/admin.php
Removed the name-changing for Otter in Neve
NO
Closes #3655.
> chore: stop changing Otter name [#3655]

- assets/js/src/frontend/hgf.js
- The issue was pretty easy to fix, we just needed to add some aria-hidden attributes. However since I never used the VoiceOver, it was pretty weird to test it.
NO
https://user-images.githubusercontent.com/9929553/201064044-6e01b460-a643-4403-abdb-6dadff0e1ca7.MP4
- Add this PR to an instance that you can access with your mobile
- Enable VoiceOver on your iPhone ( I did it via Siri since I was not that familiar with it )
- Open the menu and navigate through the links via swipe. ( Tip: swipe right under the menu and it will act as Tab on the computer, swipe left and it will go back, Double tap to click )
Closes #3676.
> VoiceOver accessibility issue on iPhone

- composer.lock
Update Themeisle SDK to the latest version
> chore: update SDK

- header-footer-grid/Core/Builder/Abstract_Builder.php
- header-footer-grid/Traits/Core.php
Fix for the PHP Warnings occur conditionally on legacy skin (due to header row BG image)
NO
To issue reproducing steps, please check here: https://github.com/Codeinwp/neve/issues/3717#issuecomment-1328212407 - The issue should be fixed. 
Example test scenario:
1. Have WP 5.7 and Neve 2.9.5
2. Create sample post
3. Go to customizer -> header builder
4. Case 1: For a row; go row style and choose image mode for the background add a image but do not play with bg position (left/right) https://vertis.d.pr/i/6rzr7S
5. Case 2: For another row; go row style and choose image mode and enable "use featured mode" toggle.
6. Case 3: For another row; go row style and choose image mode for the background but do not add any image. 
7. Upgrade Neve to latest stable version.
8. You should be able to see …
> Fixes for the PHP Warnings related HFG Row BG on Legacy Skin

- composer.lock
Updated sdk to fix the issue with customizer not opening in some cases
NO
Closes #3734.
> Fix customizer not working

- bin/envs/theme-check/start.sh
Temporary replace themecheck with a fork
Closes #3745.
> chore: fix themecheck

- assets/scss/components/compat/woocommerce/_checkout.scss
- inc/compatibility/elementor.php
- inc/compatibility/woocommerce.php
Fix Elementor Checkout not working
NO
- create a page and edit it with elementor
- add the checkout widget
- save the page and check if it shows well on frontend
Closes #3610.
> fix: elementor checkout [#3610]

- .github/workflows/neve-sync-branches.yml
Add sync with Neve 3.5
NO
Closes #3776.
> chore: add 3-5 sync

- .github/workflows/neve-sync-branches.yml
> chore: remove 3-5 sync

- search.php
- Added the filter for wrapper div classes
NO
**NOTE: Please test this with the PR from Neve PRO**
- Activate the Blog hover effects from the customizer. 
- Check if they work fine on the blog and search.
~ 25 minutes
Closes Codeinwp/neve-pro-addon#2328.
> Support changes for blog hover effects on the search page

- .github/workflows/playwright.yml
- e2e-tests/README.md
- e2e-tests/fixtures/customizer/hfg/alignment-control-setup.json
- e2e-tests/specs/customizer/form-fields/form-fields.spec.ts
- e2e-tests/specs/customizer/general/color-control.spec.ts
- e2e-tests/specs/customizer/general/custom-global-colors.spec.ts
- e2e-tests/specs/customizer/hfg/hfg-alignment-control.spec.ts
- e2e-tests/specs/customizer/hfg/hfg-margin-control.spec.ts
- e2e-tests/specs/customizer/hfg/hfg-menu-item-alignment.spec.ts
- e2e-tests/specs/customizer/hfg/hfg-padding-control.spec.ts
- e2e-tests/specs/customizer/hfg/hfg-palette-switch-component.spec.ts
- e2e-tests/specs/customizer/hfg/hfg-row-background.spec.ts
- e2e-tests/specs/customizer/hfg/hfg-search-component.spec.ts
- e2e-tests/specs/customizer/layout/blog-archive-settings.spec.ts
- e2e-tests/specs/customizer/layout/sidebar-settings.spec.ts
- e2e-tests/specs/customizer/layout/single-post-settings.spec.ts
- e2e-tests/specs/customizer/typography/blog-typography.spec.ts
- e2e-tests/specs/customizer/typography/font-family.spec.ts
- e2e-tests/specs/customizer/typography/font-sizes.spec.ts
- e2e-tests/specs/tpc/tpc-notice-install.spec.ts
- e2e-tests/utils.ts
- package.json
- Improve code quality for playwright tests
- Add a test for global custom colors
Closes Codeinwp/neve-pro-addon#2307.
> Playwright tests

- .distignore
- .github/workflows/create-tag.yml
- .github/workflows/test-php.yml
- composer-dev.json
- composer-dev.lock
- package.json
- Composer Dev dependencies were moved into a new composer config file (composer-dev.json)
- Some GH actions based on PHP tests were maintained to run over composer-dev.json
- a script command was added to `package.json` to composer install for devs: that's available as `yarn composer:install`
NO
- All GH Checks related composer should be green.
~ 40min
Closes #3857.
> Having two composer file (prod, dev) and rid of --ignore-platform-reqs

- .github/workflows/sync-qa.yml
- readme.md
Updated workflow to sync to QA server: `qa-neve.vertisite.cloud` via SFTP
Updated rsync to `staging.demosites.io`
NO
1. Github action to sync to QA should pass and the latest changes should be found on target servers.
2h 25min
Closes #3838.
> Fix: QA deployment sync

- .github/workflows/test-php.yml
- composer-dev.json
- composer.json
- composer.lock
- header-footer-grid/Core/Builder/Abstract_Builder.php
- header-footer-grid/Core/Components/Abstract_Component.php
- header-footer-grid/Core/Magic_Tags.php
- header-footer-grid/Core/Settings/Manager.php
- header-footer-grid/Main.php
- header-footer-grid/functions-migration.php
- header-footer-grid/functions-template.php
- header-footer-grid/loader.php
- inc/admin/dashboard/plugin_helper.php
- inc/admin/metabox/manager.php
- inc/compatibility/elementor.php
- inc/compatibility/starter_content.php
- inc/compatibility/woocommerce.php
- inc/core/admin.php
- inc/core/core_loader.php
- inc/core/styles/frontend.php
- inc/customizer/controls/react/typography.php
- inc/customizer/defaults/single_post.php
- inc/views/breadcrumbs.php
- inc/views/nav_walker.php
- inc/views/pluggable/pagination.php
- inc/views/product_layout.php
- phpstan.neon
Upgraded PHPStan packages:
```json
"phpstan/phpstan": "1.8.7",
"szepeviktor/phpstan-wordpress": "^v1.1.7",
"php-stubs/woocommerce-stubs": "^7.4.0",
"php-stubs/wordpress-stubs": "^6.1"
```
Fixed reported issues that were valid, some false positives were ignored.
NO
1. PHPStan tests should pass
2. No behavior changes should be introduced
~2h 50m
+ 3h for (Neve PRO PR that I did not account for when assigning the issue estimation)
Closes #3820.
> feat: updated phpstan and fixed reported issues

- inc/admin/dashboard/main.php
Fix the array call and preserve the menu location.
YES
1. Check that the customizer menu appears under Appearance and under Neve Options
Closes #4001.
> fix: customizer link

- .github/workflows/deploy.yml
- fix beta trying to deploy to wporg and latest
> fix beta being deployed to latest

- readme.md
- readme.txt
- style.css
Increased WP min version.
NO
- Switch to wp. 5.4
- Try to activate Neve. You should see this: https://vertis.d.pr/i/ffNtu8
Closes #4068.
> Increase WP min version

- e2e-tests/specs/tpc/tpc-notice-install.spec.ts
- Fix E2E test for the new TPC onboarding
NO
- Nothing to test, the tests should pass.
Closes #4106.
> E2e test for tpc [#4106]

- assets/apps/dashboard/src/utils/survey.js
- inc/admin/dashboard/main.php
Fix the plan identification and add info about license status and pro plugin version.
NO
- Try to trigger the NPS Form
- Once complemented, ping @Soare-Robert-Daniel or @vytisbulkevicius for confirmation with mention of the license key
Closes #2723
> Add extra attributes for Frombricks survey

- inc/core/admin.php
I've removed the filter to display the blog widget in the dashboard area.
Closes Codeinwp/themeisle#1642
> Added dashboard blog widget 

- .distignore
I've added the dashboard widget file in the build zip.
Closes https://github.com/Codeinwp/themeisle/issues/1642
> Removed dashboard widget file ignore from .distignore

- header-footer-grid/Core/Magic_Tags.php
In this PR, I've added new custom layout magic tag rendering support.
Closes https://github.com/Codeinwp/neve-pro-addon/issues/2709
> Added new custom layout magic tag support

- stories/utils/values.js
Fixed the `Build and Deploy StoryBook` checklist testcase error.
PR https://github.com/Codeinwp/neve/pull/4311
> Fixed JS syntax error

- e2e-tests/specs/customizer/layout/single-post-settings.spec.ts
- inc/customizer/defaults/single_post.php
- inc/customizer/options/layout_single_page.php
- inc/customizer/options/layout_single_post.php
- inc/views/cover_header.php
- inc/views/post_layout.php
> Revert "Fixed cover layout issue with CPT"

- docker-compose.ci.yml
- docker-compose.yml
Update the DB in the docker composer file to prevent infinite loading.
> refactor: replace MySQL image with MariaDB in docker-compose files

- readme.md
- readme.txt
Update description in README
NO
- Check if the description is correct.
Closes https://github.com/Codeinwp/neve-pro-addon/issues/2941
> refactor: update the description in README

- assets/apps/dashboard/src/Components/Content/StarterSitesUnavailable.js
- assets/apps/starter-sites/src/ss-try-button/SSTryButton.tsx
- inc/admin/dashboard/main.php
- inc/core/admin.php
- inc/customizer/traits/features_upsell.php
Small hot fixes based on testing.
> fix: PRF merges

- functions.php
Set the compatibility to the next major version of Neve PRO.
> fix: update NevePro compatibility requirements to version 3.0

- .github/workflows/create-tag.yml
- .github/workflows/deploy-npm-package.yml
- .github/workflows/deploy-storybook.yml
- .github/workflows/deploy.yml
- .github/workflows/diff-translations.yml
- .github/workflows/e2e-storybook.yml
- .github/workflows/playwright.yml
- .github/workflows/sync-qa.yml
- .github/workflows/test-npm.yml
- .github/workflows/test-php.yml
- .github/workflows/trigger-visual-on-comment.yml
Update GitHub Actions versions.
> chore: update Github Actions versions

- assets/apps/dashboard/src/Hooks/usePluginActions.js
Fixed broken link
Yes
Closes https://github.com/Codeinwp/neve/issues/4387
> Fixed starter sites broken link redirection

- assets/scss/components/main/_gutenberg.scss
> [!NOTE]
> The size checks will pass when this is merged togheter with #4397.
Adds minimal styling for the core login block.
YES
- Adds core login block to a page;
- It should be styled properly;
Closes Codeinwp/neve-pro-addon#2501.
> [Fix] Core login block styles

- assets/apps/metabox/src/components/MetaFieldsManager.js
Adds description to Neve options panel in single post editor.
NO
- Open the editor for a single post. 
- It should have a description at the top stating that the settings in this panel override the customizer settings;
Closes Codeinwp/neve-pro-addon#2893.
> [Feat] Adds description to the Neve editor options panel

- assets/scss/components/compat/woocommerce/_account.scss
- assets/scss/components/compat/woocommerce/_media-queries.scss
Improves Woocommerce My Account page styling.
YES
- Install and activate WooCommerce;
- Check that the My Account page works as expected & has the new styling;
Closes Codeinwp/neve-pro-addon#2935.
> [Feat] Improved Woo account page styling

- assets/apps/components/src/Controls/ColorControl.js
Fixed the styling options of the menu icon.
Closes https://github.com/Codeinwp/neve-pro-addon/issues/3022
> Fixed styling options of menu icon

- .distignore
- composer-dev.json
- composer-dev.lock
- functions.php
- header-footer-grid/Core/Magic_Tags.php
- header-footer-grid/Core/Settings/Manager.php
- phpstan-baseline.neon
- phpstan.neon
Update PHPStan and set it to v2 with baseline.
NO
- There are no main code changes.
> dev: update PHPStan to v2 and set the level to 6

- inc/core/styles/frontend.php
Update the CSS variable for the Secondary Button border color.
Closes https://github.com/Codeinwp/neve-pro-addon/issues/3040
> Fixed secondary button border color

- assets/apps/dashboard/src/Components/Content/Sidebar/LicenseCard.js
Fix added a new license when the current one expires.
Closes https://github.com/Codeinwp/neve-pro-addon/issues/3051
> Add new license while white label enabled
