inc/core/admin.php
inc/core/front_end.php
template-parts/content-none.php

- Welcome notice content updated
- Theme name changed in Onboarding, it was hardcoded
NO
- I strongly recommend to comment [these lines](https://github.com/Codeinwp/ti-about-page/blob/master/includes/admin/class-ti-notice-manager.php#L127) while testing
```
update_option( self::$dismiss_key, 'yes' );
return;
```
- Also, make sure to test with the About Page and Onboarding from my fork.
https://github.com/stefan-cotitosu/ti-about-page
https://github.com/stefan-cotitosu/ti-onboarding
- Welcome Notice
- Check theme name in Onboarding, both in pop-up and on sites library tab in Neve Options page

Welcome notice enhancements

---

onboarding/neve-main/data.json

@rodica-andronache I've added the functionality to the onboarding and disabled woo by default on the main demo in this commit. Right now, I didn't add anything to the demo export plugin so we have to be careful until then to not delete this line. :))

chore: disable woocommerce plugin for main demo by default

---

gutenberg/blocks/blog/template.json

Otter 1.2 brings an update to Posts and Maps blocks and it was required to update the Blogs block from the Template Library.
NO
Closes #.

chore: Update Gutenberg Blog block

---

views/archive-post.php

Remove escaping from article inner-content.
NO
Closes #733.

fix: useless escaping for the archive post inner content [fix #733]

---

inc/views/post_layout.php

Fixed conflict between metabox and content ordering (false was being used as `0` array key)
NO
- Disable the post thumbnail from the metabox for a post
- Disable the thumbnail from single post content ordering
- The title should be there.
Closes #731.

fix: hiding thumb hides title when hide title metabox option is enabled

---

header-footer-grid/Core/Components/Button.php

More specific selector for the button component CSS properties.
NO
- Set a padding in Buttons > Padding
- Set different padding for the Header Button component
- Check if the proper padding is applied for the Button component on WooCommerce pages.
Closes #773.

fix: header button component padding was affected by other settings

---

inc/admin/metabox/main.php

Changed the default metabox settings for new pages.
NO
- Add a new page. It should default to 100% content width and no-sidebar layout [in metabox]
- Check that old pages remain unaffected.
- Check that other post types remain unaffected.
Closes #381.

fix: set new pages to no sidebar and 100% content width automatically

---

globals/utilities.php

move after/before content hooks in hook list to Single
NO
- Test with custom layouts from Neve Pro
Closes Codeinwp/neve-pro-addon#322

chore: move after/before content hooks in hook list to Single

---

inc/customizer/controls/react/bundle/controls.css
inc/customizer/controls/react/src/style.scss

Fix line height in font-family control.
NO
Closes #936.

chore: fix typography control on WP 5.3

---

header-footer-grid/Core/Components/Nav.php
inc/views/header.php

Removes last menu item if it was never changed or it's empty.
NO
- By default, the setting should not appear.
- If you migrate from an older version with it set up to something, it should be there.
- If you migrate from an older version with it empty or with the default value, it shouldn't appear.
Closes #993.

chore: drop last menu item if it's disabled or not in use

---

header-footer-grid/Core/Components/MenuIcon.php

Padding applies to the menu icon button itself.
NO
Closes #991.

chore: make padding affect menu button itself instead of parent

---

inc/admin/metabox/controls/control_base.php

Changed the meta getting method for meta-box settings to pull only single meta values.
The data inconsistencies were coming from the checks, as meta might've been set but it was `''`. I previously made it verify if the value was set with `isset` in the meta array. 
That yielded that on the next save the value becomes `0`. 
The range and number input have a `min=50`, so the browser couldn't validate the value for that input, hence the error. 
cc @stefan-cotitosu this is going to fix #1026.
NO
Closes #1026.

fix: getting post meta value for single meta-box

---

inc/admin/metabox/controls/control_base.php
inc/views/pluggable/metabox_settings.php

Make sure we don't insert useless meta in the database.
NO (at least shouldn't be)
- Check if everything works properly with the meta box.
- Should still work with Pro [we have an additional field for product video there]
- New posts should not insert any meta from the meta box in the DB
- New pages insert content width `100` and Sidebar `full-width`
Closes #821.

chore: do not create useless meta for posts / pages in DB [fixes #821]

---

header-footer-grid/templates/components/component-footer-sidebar.php
inc/admin/metabox/controls/range.php

Fixes style for metabox range input in Firefox.
NO
Tested with _Chrome / Safari / Firefox_
- Go inside the editor
- Check the metabox options
- Individual content width should look fine in Firefox / Safari / Chrome (like the screenshot above)
Closes #1098.

Fix style for metabox range input in Firefox [closes #1098]

---

header-footer-grid/Core/Components/Logo.php

Moves logo component Display setting as first in the section.
NO
- Section should look like in the screenshot
Closes #1324.

chore: move logo component Display setting first in section [#1324]

---

inc/customizer/base_customizer.php

Adapt abstract class `base_customizer.php` to work with conditional headers from Neve Pro.
Related to Codeinwp/neve-pro-addon#530.
NO
- Test with this PR: https://github.com/Codeinwp/neve-pro-addon/pull/538
- Should work fine with older versions of Neve Pro. 
Closes Codeinwp/neve-pro-addon#530.

chore: changes to make compatible with Codeinwp/neve-pro-addon#530

---

header-footer-grid/Core/Components/MenuIcon.php

Adds component slug, to make sure it doesn't appear twice inside the add-component window.
NO
- Check that the menu icon component doesn't appear twice inside the add component window
Closes #531.

fix: menu icon component showing up twice [closes #531]

---

header-footer-grid/Core/Components/Copyright.php
header-footer-grid/Core/Components/CustomHtml.php
header-footer-grid/Core/Components/Logo.php

Adds color controls for HTML / Copyright / Page Header HTML / Logo components under the Style tab.
NO
- Test that the style controls apply color properly
- Should not affect `<a>` tags as those are handled by the skin mode.
Closes #1317.

feat: add color controls to components

---

header-pwa.php
header.php
inc/compatibility/amp.php

Fixes compatibility with codeless injection in GTM Plugin and the Google AMP plugin. 
NO
- Install GTM Plugin and make sure it is set to codeless injection.
- Install AMP Plugin and check that no weird strings are displayed at the top of the page.
- Make the menu still works in AMP mode.
Closes #1365.

fix: AMP + Google Tag Manager plugin issues [closes #1365]

---

header-footer-grid/Core/Components/Abstract_Component.php
header-footer-grid/Core/Components/Nav.php
header-footer-grid/templates/component-wrapper.php

Fixes issue with the selective refresh for components. Previously, the inner content was rendered twice upon selective refresh. Now it should render fine.
NO
- Test if selective refresh renders the inner content of the component twice - it shouldn't.
Closes #1370.

fix: selective refresh for components [closes #1370]

---

globals/utilities.php

AMP requires `role` and `tabindex` attributes for elements that have an `on="tap:..."` attribute, unless they are buttons or links (i.e. elements that aren't normally tappable/tabbable).
Originally reported on the AMP plugin support forum: https://wordpress.org/support/topic/the-attribute-tabindex-in-tag-span-is-missing-or-incorrect/
Note the changes where should be done automatically by the AMP plugin in the future (via https://github.com/ampproject/amp-wp/issues/4528) but it is best if the changes are done up-front.
As an alternative to adding these attributes, the icon could instead be represented by a `button` instead of a `span`.
YES (when tabbing there may be an outline on the element)
* No validation error should be reported for the page.
* The search icon should be tabbable with …

Add missing role=button and tabindex=0 for search icon button to fix AMP validity

---

header-footer-grid/Core/Magic_Tags.php

I've changed the {archive_title} tag a bit because when you had a blog page in customizer it returned "Archives" instead of the page title
NO
https://prnt.sc/salwbv

Fix archive_title magic tag

---

header-footer-grid/Core/Builder/Abstract_Builder.php

Imported demos with dark skins on header rows that had dropdowns were not properly set.
NO
- Clean wp (`wp theme mod remove --all && wp site empty --yes`)
- Import the `Shop` demo. 
- Primary menu dropdowns should have the proper background color
cc @rodica-andronache

chore: fix dropdown color issue with imported demos using dark skin on hfg rows [ref #1550]

---

inc/core/front_end.php

Add back image and thumbnail width in WooCommerce for free users.
NO
We should remove the function that removes that parameter in pro. I've made a PR for this: https://github.com/Codeinwp/neve-pro-addon/pull/720
Closes #1614.

Missing image and thumbnail width in WooCommerce

---

inc/compatibility/woocommerce.php

This modification is needed to be able to remove just the breadcrumbs in pro. I added woo breadcrumbs and product count in a hook to get the option to remove just the breadcrumbs and not the whole header that includes product filters too.
It's related to https://github.com/Codeinwp/neve-pro-addon/issues/660
NO

Fix for woo breadcrumbs

---

header-footer-grid/Core/Components/Abstract_Component.php
header-footer-grid/Core/Components/Abstract_FooterWidget.php

Enables vertical alignment on ALL footer components as it made much more sense.
NO
- All footer components - including pro ones - should have vertical alignment controls. 
- None of the other builder components should have vertical alignment controls.
- Vertical alignment should work, obviously :see_no_evil: . 
Closes #1368.

chore: enable vertical alignment for all footer components [#1368]

---

inc/core/admin.php

Adds filter to hide starter sites dashboard notice.
NO
- Must work with [this PR](https://github.com/Codeinwp/neve-pro-addon/pull/773)
Ref: Codeinwp/neve pro addon#706.

chore: add filter to hide dashboard notice [Codeinwp/neve pro addon#706]

---

globals/utilities.php
header-footer-grid/templates/components/component-search-responsive.php

I have no idea why the old implementation wasn't working on mobile.
How it was and wasn't working on mobile:
```on="tap:nv-search-icon-responsive.toggleClass(class='active')"```
How it is now and this way it's working:
```on="tap:AMP.setState({visible: !visible})"```
and on the `.nv-search-icon-responsive`
``` [class]="visible ? 'menu-item-nav-search active <?php echo esc_attr( $open ); ?>' : 'menu-item-nav-search <?php echo esc_attr( $open ); ?>'" ```
The implementation is similar but it's written differently.
NO
- Activate AMP
- Go to the AMP version on mobile and click on the search icon component in the header.
Closes #1743.

fix: canvas search on amp mobile [#1743]

---

header-footer-grid/Core/Builder/Abstract_Builder.php

The divider color was overwritten by the menu background-color
NO
Closes #1715.

fix: divider color [#1715]

---

composer.lock
inc/views/pluggable/pagination.php

Updates composer.lock
Adds permission callback to rest route
NO
- Latest RC should not throw notices when trying to add a new post. 
- Make sure you have `WP_DEBUG` set to `true`

WordPress 5.5RC Fixes

---

inc/customizer/options/layout_sidebar.php

Fix notice placement. Don't know why but if it's wrapped in a div, the position of it changes. I removed the wrapper and it looks ok.
NO
Closes Codeinwp/neve-pro-addon#886

fix: notice placement [Codeinwp/neve-pro-addon/#886]

---

inc/core/styles/gutenberg.php

Link colors were not applying inside the editor. Should be in working order now.
NO
Closes #2009.

fix: link colors inside the editor

---

views/page-header.php

Page Header was parsing HTML tags from search.
NO
- If you search for any HTML code in the site, the tags should not be parsed.
Closes Codeinwp/neve-pro-addon#902.

chore: do not parse html tags inside search heading

---

inc/core/styles/gutenberg.php

NO
- Headings should inherit customizer set colors 
Closes #2010.

fix: headings not inheriting customizer colors inside editor

---

header-footer-grid/Core/Magic_Tags.php
inc/views/partials/post_meta.php

Remove the meta_time_to_read magic tag in lite and add it in PRO via filters.
NO
Need to also merge https://github.com/Codeinwp/neve-pro-addon/pull/938
Closes #2065.

Remove time to read magic tag from lite

---

inc/compatibility/elementor.php

Some while ago we changed the hook on 404 but we forgot to change it in the Elementor compatibility file.
NO
Closes #2068.

Fix elementor 404 template

---

header-footer-grid/Core/Components/Button.php
header-footer-grid/Core/Components/CustomHtml.php
header-footer-grid/Core/Components/SecondNav.php

Related to [this PR](https://github.com/Codeinwp/neve-pro-addon/pull/942).
Components in Page Header were taken into account for conditional headers.
---
Modifies the following: 
- Button Component
- Custom HTML Component
- Secondary Nav Component
NO
- The page header components mentioned above should not be taken into account by the functionality of the conditional headers. 
Closes https://github.com/Codeinwp/neve-pro-addon/issues/927

fix: components in page_header were taken into account for conditional headers

---

inc/core/admin.php

Drops background sub menu item inside Appearance.
NO
- Background admin menu link should not appear anymore.
Closes Codeinwp/neve-pro-addon#930.

chore: drop Background sub menu item inside admin

---

inc/compatibility/woocommerce.php

Fixes styles that were overriding the More Details button in the product Quick View modal. 
NO
- More Details button should use the secondary button style.
Closes Codeinwp/neve-pro-addon#884.

fix: quick view more details button style overridden by primary button

---

header-footer-grid/Core/Components/Button.php

Increases button component default CSS selector specificity to override WooCommerce rules.
YES - but fixes some issues
- Button component style settings should apply on all pages, including woocommerce ones where they were overridden by the Button styles previously.
Closes #2036.

fix: button component selector specificity

---

header-footer-grid/Core/Magic_Tags.php

When adding a link, it already comes with the protocol for the link in the markup. The input in which we replaced the §
`{current_single_url}` was `<a href="http://{current_single_url}">` and then we were replacing the `{current_single_url}` with `http://neve.local/p=13` and the result was `<a href="http://http://neve.local/p=13">`
NO
- Create a custom layout that applies on a single post or page
- Add `{current_single_url}`as a link
Closes Codeinwp/neve-pro-addon#931.

Fix current_single_url magic tag when added as link [#931]

---

cypress/integration/customizer/layout/blog-archive-settings.spec.js

Resets settings after each test is done for blog archive layout to ensure there are no collisions with other specs.

chore: add reset to blog archive settings cypress tests

---

inc/core/admin.php

Migration needed theme mod was set only inside the TPC plugin instead of setting it inside the theme. That meant that when you changed the theme without the TPC plugin active, the change would not be saved for the migration purposes.
NO
- Use zerif-lite/zerif-pro and set some basic front page options inside the customizer.
- Switch to neve
- Follow the normal user flow installing the TPC plugin for starter sites.
- The migration from the old theme should work fine inside the starter sites page/tab
Closes Codeinwp/templates-patterns-collection#10.

fix: migration not being registered without TPC plugin

---

inc/admin/metabox/manager.php
inc/views/pluggable/metabox_settings.php

There was no way to add the sidebar on checkout. It resets to no sidebar every time you've updated the checkout page.
NO
- Go to the checkout page and try to change the sidebar position, then press publish.
- Refresh the page and see if the sidebar position is still no-sidebar

Fix no sidebar on checkout

---

inc/views/product_layout.php

The wrapper around the product wasn't hooked where it supposed to be
NO
Closes Codeinwp/neve-pro-addon#997.

Fix related products

---

inc/core/settings/config.php
inc/core/styles/gutenberg.php

When you had previously set colors for:
```
link-color
text-color
background-color
```
The old colors were still applied inside the editor.

fix: global colors overridden by old colors in editor

---

globals/utilities.php
inc/core/front_end.php

Old background color control value was applying to `body.custom-background` selector.
- use an old version of the theme, make sure you change the background color from the core background color control;
- migrate to this version, the background color should not apply;
- on the dev version, the background color will apply;

chore: fix issue with old core background color applying to body

---

inc/compatibility/amp.php

Fixes syntax oversight.
This was treated as a namespace separator so it did not affect the code.
ref: #2375

fix: syntax error [ref #2375]

---

inc/views/pluggable/metabox_settings.php

Fixes meta box settings that were not working properly:
- container type
- hiding header
- hiding footer
NO
- Set up a shop page
- Edit it and check if all the meta box settings work as expected
Closes Codeinwp/neve-pro-addon#999.

fix: apply individual page settings to shop page [closes Codeinwp/neve-pro-addon#999]

---

inc/views/breadcrumbs.php

Breadcrumbs were not displayed for SEOPress and RankMath
NO
Using the following plugins: 
- Yoast
- SeoPress (pro needed - you'll have to believe me that it works as I can't give you the API key (it's not mine :joy:)
- RankMath -> [enable breadcrumbs](https://successpixel.com/how-to-enable-breadcrumbs-with-rank-math-wordpress-seo-plugin/#:~:text=Before%20that%2C%20you%20must%20enable,Breadcrumbs%20%3E%3E%20Enable%20breadcrumbs%20function.)
- NavXT
---
- Breadcrumbs HFG Component should work with all of them;
- Should work with [this PR](https://github.com/Codeinwp/neve-pro-addon/pull/1077) just fine;
Closes Codeinwp/neve-pro-addon#996.

fix: breadcrumbs for SEOPress and RankMath [ref Codeinwp/neve-pro-addon#996]

---

inc/compatibility/elementor.php
inc/core/front_end.php

- Makes sure global colors theme name is adapted to White Label settings
NO
- Enable WhiteLabel and check the global colors names in the Elementor / Gutenberg Palettes;
- They should not include "Neve" but have the "Theme" prefix, as opposed to the free version.
Closes Codeinwp/neve-pro-addon#1096.

fix: adapt global colors for whitelabel [closes Codeinwp/neve-pro-addon#1096]

---

inc/views/partials/comments.php

Add a filter that will account for the functionality the doc tries the implement.
NO
- add a PHP file inside of your mu-plugins folder and add the following code to it: `add_filter( 'neve_show_comment_form_first', '__return_true' );
`
- the comment form should be displayed before the comments instead of after;
- this should replace the functionality that the document was aiming to provide; 
- note that after this is released you should ping me to update the doc;
Ref #2481.

chore: add filter to display comment form first [ref #2481]

---

globals/hooks.php
inc/compatibility/beaver.php
inc/core/front_end.php

Add support for beaver themer parts, following [this](https://docs.wpbeaverbuilder.com/beaver-themer/developer/add-header-footer-and-parts-support-to-your-theme-themer/) documentation.
NO
1. https://prnt.sc/xt6lu1
2. https://prnt.sc/xt6nt8
3. https://prnt.sc/xt6qw6
1. Install Beaver Builder Pro and Beaver Themer form handbook
2. Follow the steps described in the Screenshots section.
Closes #2329.

Add support for themer parts

---

cypress.json
cypress/integration/amp/amp-test.spec.js
cypress/integration/customizer/general/color-control.spec.js
cypress/integration/customizer/general/order-control.spec.js
cypress/integration/customizer/hfg/hfg-alignment-control.spec.js
cypress/integration/customizer/hfg/hfg-margin-control.spec.js
cypress/integration/customizer/hfg/hfg-padding-control.spec.js
cypress/integration/customizer/hfg/hfg-row-background.spec.js
cypress/integration/customizer/layout/container-settings.spec.js
cypress/integration/customizer/layout/sidebar-settings.spec.js
cypress/integration/customizer/typography/blog-typography.spec.js
cypress/integration/dashboard/general.spec.js
cypress/integration/dashboard/useful-plugins.spec.js
cypress/support/commands.js
cypress/support/index.js
package.json
yarn.lock

Upgrades Cypress to 6.4 so we can use [Cypress Studio](https://docs.cypress.io/guides/core-concepts/cypress-studio.html#Adding-a-New-Test)
NO
- The tests should pass on CI
- Everyone should be able to use Cypress Studio locally with the Cypress Test Runner

Cypress update 6.4

---

header-footer-grid/templates/components/component-cart-icon.php
inc/core/settings/config.php
inc/core/styles/frontend.php
inc/views/layouts/layout_sidebar.php

- added a class named `.secondary-default` on the close button for off-canvas mini cart and off-canvas shop sidebar
- exclude the `.secondary-default` class from `CSS_SELECTOR_BTN_SECONDARY_NORMAL` and `CSS_SELECTOR_BTN_SECONDARY_HOVER` in config.php
- create `CSS_SELECTOR_BTN_SECONDARY_DEFAULT` and `CSS_SELECTOR_BTN_SECONDARY_DEFAULT_HOVER` and add them only to background-color, text-color, border-radius, border-width and type
YES
- enable offcanvas for minicart an for shop sidebar and check the button
Closes #2358.

Fix close button style in off canvas

---

inc/views/partials/comments.php

Allows HTML in title of post displayed in the comments area.
NO
- Add a new post and use HTML inside the title - `<span style="color: red">HELLO</span> WORLD` something like this should work
- Go to the post and add a comment.
- The post title in the comments area should display the styled `span` tag, and not escape it.
Closes #2470.

enh: allow html tags in comments title [closes #2470]

---

inc/views/partials/post_meta.php
inc/views/post_layout.php

Fixed the meta_comments and current_post_meta magic tags on the 404 page
NO
- Add these magic tags in the HTML header component and check the 404 page
Closes #2490.

fix: meta_comments and current_post_meta magic tags [#2490]

---

dashboard/inc/Changelog_Handler.php

Fixes changelog parsing for double-digit releases:
e.g. 1.21.3 | 10.1.24
NO
- Go into the dashboard page for Neve 
- The changelog should be properly parsed as opposed to what's mentioned inside the issue
Closes #2536.

fix: changelog parsing regex in the dashboard [closes #2536]

---

assets/scss/style.scss
inc/core/styles/frontend.php

Fixes secondary button styles not properly applying on filtered selectors
YES
- Change the **Primary** & **Secondary** button settings inside **Customizer > Buttons**;
- Inside **Customizer > Form Fields > Button**, change the Button Style. Both styles should properly apply to the following things:
- Comment form on single posts;
- Forms from WPForms plugin;
- Forms from Contact Forms 7 plugin;
- Install the PRO version Import a demo site that uses a WooCommerce shop;
- Inside **Customizer > Layout > Content / Sidebar** enable the _Advanced Options_ ad set the **Shop / Archive** sidebar to _Off Canvas_;
-  On the shop, if you open the sidebar, the close button should inherit the secondary button styles;
If anything isn't clear, be sure to ping me for a more in-depth explanation. :+1: …

fix: secondary button styles filter not applying [closes #2583]

---

assets/scss/elements/blog/_blogpost-meta.scss
inc/customizer/options/layout_blog.php
inc/views/partials/post_meta.php
languages/neve.pot

- Added a toggle in the customizer to switch between created post date and the last updated date.
- Added the `neve_meta_date_prefix` filter to add a prefix before those dates.
NO
- Go to Customizer -> Layout -> Blog/Archive -> Post meta and enable the toggle that says `Use last updated date instead of the published one`. Also, make sure the date is enabled in the Meta Order control.
- Edit a post and press publish so the post would have an updated date.
- Check on blog/single/archive if the post is displaying the updated date and not the one that it was created.
- Check a post that was not updated. It should display the published date.
- In a child theme, add the following function in `functions.php`:
```
function neve_post_date_prefix( $prefix_array ) {
$prefix_array['published'] = …
```

Show last updated date on posts [#1804]

---

inc/compatibility/woocommerce.php

Seems like the selectors for the hover button added in WooCommerce didn't have a comma before them and they were concatenated to the selectors from neve, breaking them as well.
NO
- Check if hover color for secondary buttons from customizer works
Closes #2678 .

Fix button secondary color

---

assets/scss/main/_typography.scss
inc/customizer/options/typography.php
languages/neve.pot

- Removed the font-family property in _typography.scss because it was overwriting what's on the body.
- Mark the font control as 'default_is_inherit' to inherit from the body when it is set as default.
YES will produce visual changes if the body font is set and the headings font is not.
- Test if it works well when:
1. none of them are set ( headings and body font should have the same value, and the value is a default font )
2. body is set, but headings are not ( headings should have the same font as the body font )
3. body is not set, headings are set ( headings should have their value and body should have the default value )
4. both are set ( body have its font, headings have its font )
- Check if there is the correct font in both the front-end and editor.
Closes #2560.

Headings should inherit from body when set as default

---

functions.php
globals/hooks.php

- Added back the hooks.php files as they are used in child themes.
NO
Closes #2764.

Revert hooks file

---

e2e-tests/cypress/fixtures/woocommerce/single-product-setup.json
e2e-tests/cypress/integration/woocommerce/single-product.spec.ts

Adds a test for woocommerce single product that uses Exclusive products
NO
- All tests should pass the pipeline
Closes #2780 .

Adds a test for woocommerce single product

---

assets/scss/gutenberg-editor/_typography.scss

- Fix text color for blocks inside a group block with color applied.
- Removed the padding of a group block that has a background in the editor so it matches the front-end.
NO
The scenario is like this:
1. Have a group block
2. Insert in it two paragraphs
You can either add text color to each paragraph or add text color on the global block.
How it should behave:
1. If the group block has a text color set and the paragraphs don't, the paragraphs should inherit the text color from the group block.
2. If the group block has a text color set and the paragraphs have their own color set, the color of the paragraph should overwrite the group block color.
- Maybe try with some other blocks inside the group block too.
Closes #2540.

Fix group block color

---

functions.php
header-footer-grid/templates/components/component-logo.php
inc/views/post_layout.php
inc/views/template_parts.php
languages/neve.pot

- Added skip lazy class for logo, single thumbnail if it's before content, and the first image of the blog archive
NO
- Check if skip-lazy class is where I said it would be
Closes Codeinwp/neve-pro-addon#1249.

Add skip-lazy class

---

assets/scss/elements/_sidebar.scss

Changes post date style inside sidebar widgets according to #2582.
YES
- Add the recent posts widget and make sure to turn on the show post date option;
- The styling should look like in #2582
Closes #2582.

chore: fix post date styling inside widgets [closes #2582]

---

inc/views/font_manager.php

If a font family is set to inherit, but it uses font weights not shared by the body font, those are not enqueued outside the customizer.
NO
- Set the body font to a google font. `Inter` would work great.
- Set the heading font weights to 700;
- The font weights should work fine on the front end;
Closes #2843.

fix: font weights not getting properly enqueued when some font families are set to inherit

---

header-footer-grid/Core/Components/PaletteSwitch.php
languages/neve.pot

Set the default for auto adjust color to `false`
Don't adjust the colors automatically inside customizer
NO
When adding the palette switcher inside customizer the colors should not auto adjust even if the automatically adjust option is enabled. Only on the frontpage this should work as before.

fix: palette auto default to false and no customizer auto

---

globals/utilities.php
header-footer-grid/templates/components/component-search-responsive.php
languages/neve.pot

Removed the id from the search icon as it is not used by the theme or the plugin and is not required.
Added `aria-label` to link.
NO
1.  Import some starter site of Neve like Web Agency
2. Add Search Icon component to both desktop and mobile headers
3. Analyse the website with Google Chrome Lighthouse
4. No accessibility issues should be reported for this component.
Closes #2897.

fix: solve accessibility issues search icon #2897

---

header-footer-grid/Core/Magic_Tags.php
languages/neve.pot

Before the PR, {meta_author} magic tag output was not containing avatar image. It's fixed. Now, {meta_author} output contains author profile image.
YES
Before:
After:
- Make sure custom layouts be active
- Go WP Admin -> Appearance -> Custom Layouts -> Add new. _(Example test case: Layout: Header, Condition: post type is equal to Posts)_
- Add {meta_author} tag to the custom layout content
- Go a single post that have "Author Avatar" option checked
- The avatar image should be shown.
Closes #2853 .

fix: avatar visibility issue of meta_author magic tag fixed

---

inc/views/pluggable/metabox_settings.php

Modified the check for the sidebar so that it does not conflict with the individual post settings
NO
1. In Customizer set both single post and blog/archive pages to have sidebars https://vertis.d.pr/5cifRE
2. Create some test categories and assign a post or multiple posts to that test category.
3. Then, disable sidebar for that post(-s) assigned to a category manually with Neve options
4. Open the archive/category page of those posts - you should see that sidebar rendered on the category/archive page
This changes might affect the following issues also:
Codeinwp/neve-pro-addon#999
For this one check that the header on the Shop page is still hidden if `Disable Header` is enabled:
I tested this and it should work as before.
Codeinwp/neve#2790
For this one I would need some help from @selul …

fix: sidebar behaviour #2838

---

e2e-tests/cypress/fixtures/customizer/layout/sidebar-settings.json
e2e-tests/cypress/integration/customizer/layout/sidebar-settings.spec.ts
e2e-tests/cypress/integration/customizer/typography/blog-typography.spec.ts
e2e-tests/cypress/integration/dashboard/auto-heal.spec.ts
e2e-tests/cypress/integration/editor/classic/page.spec.ts
e2e-tests/cypress/integration/editor/classic/post.spec.ts
e2e-tests/cypress/integration/editor/modern/page-meta-sidebar.spec.ts
e2e-tests/cypress/integration/editor/modern/post-meta-sidebar.spec.ts
header-footer-grid/functions-migration.php

In strange cases when the theme mods options are using a corrupted value, we need to self heal them in order to avoid errors when setting the theme mods. 
NO
- Add a corrupted value for theme mods, you can use wp cli as `wp option update theme_mods_neve 1`
- Before it was throwing an error, now it should work just fine. 
Closes #2893

adds ability to self heal theme mods in case of corupted value.

---

assets/js/src/customizer-preview/app.js
assets/js/src/frontend/navigation.js

Should address problems with https://github.com/Codeinwp/neve/pull/2739#issuecomment-847081874
and: https://github.com/Codeinwp/neve/pull/2739#issuecomment-845850430
References: https://github.com/Codeinwp/neve/pull/2739
YES on some edge cases
1.  Add the search icon on the middle inside mobile header
2. Set to minimal
3. Check it does not go off-screen
4. Do the same for RTL
Same should apply for all dropdowns ( mega-menu )
The changes go over the `size-limit` for `modern` by `186 B`
Increases the compile size from `5.99 KB` to `6.18 KB` the available space by the size limit is of `10 B`

fix: dropdown calculation

---

inc/compatibility/elementor.php
inc/compatibility/woocommerce.php
inc/customizer/controls/react/src/controls.js
languages/neve.pot

Currently, if there are custom Elementor Woo Template ( shop or single product ), they don't work like expected. Neve dynamic styles and customizations are affecting to the user's custom Elementor Templates.
With this PR, we left users free about their custom WooCommerce Elementor Templates.
**How is working?**
If user has an custom Elementor shop or single product template, our custom Elementor class is bypassed.
YES
1. Install Neve, WooCommerce, Elementor, Elementor Pro
2. Create a new **Products Archive** Elementor template on WP Admin -> templates. When publish the template, set a condition for "all product archives"
3. Create a new **Single Product** Elementor template on WP Admin -> templates. When publish, set a condition for "Products"
- If user has custom Elementor products …

Independent Elementor WooCommerce Templates

---

assets/scss/woocommerce/_product.scss
bin/envs/theme-check/start.sh
inc/compatibility/woocommerce.php

- The issue here was that we targeted all elements in that div with `> *`. If a plugin come and add a script there, the script tag would have `display: flex;`
- Fixed an issue for grouped products. The padding of the primary button was applying to inputs for grouped products.
**NOTE**: You need to have https://github.com/Codeinwp/neve-pro-addon/pull/1431
NO
https://prnt.sc/15otb1h
- Import test data from WooCommerce https://github.com/woocommerce/woocommerce/tree/master/sample-data
- check that buttons and quantity input has the same height
- Check on normal, variable, grouped, and external products
- Test with seamless add to cart
- Test with quick view modal
- Test with and without Neve Pro
Closes #2903, Closes #2901, Closes #2915, Closes codeinwp/neve-pro-addon#1414

Fix issue with scripts appearing next to single product buttons

---

inc/customizer/controls/react/src/builder/HFGBuilder.tsx
inc/customizer/controls/react/src/builder/HFGBuilderComponent.tsx
inc/customizer/controls/react/src/builder/components/Slot.tsx

Fixes issue where changing header presets wasn't updating the unused items.
NO
- Test that the header preset changes affect the unused items properly;
- This should work flawlessly with the conditional headers from the Pro version;
Closes #3000.

fix: items in customizer panel don't adjust when changing presets

---

assets/scss/components/compat/woocommerce/_generic.scss
assets/scss/components/elements/form-elements/_inputs.scss

Adds bottom margin to the WooCommerce pages (My account, Checkout, Cart);
Adds bottom margin to `fieldset` tag (that can be visible on the My Account page); 
YES
Closes #3002.

fix: add back spacing for woocommerce standard pages and fieldset 

---

assets/js/src/customizer-preview/app.js
inc/customizer/controls/react/src/font-family/FontFamilyComponent.js
inc/views/font_manager.php

Wrapped the Font names in quotes, sanitized the URL request for google fonts API.
YES
1. Set any font with a stand-alone number in the name from Customizer -> Typography -> General -> Font family
2. It should be visible on the site.
Closes #2970.

fix: solve issue with multy worded google fonts #2970

---

inc/views/pluggable/masonry.php
inc/views/template_parts.php

Wrap Custom Layouts used inside the Post Loop so that they are added to the masonry when this is being used.
YES
1. Create a custom layout, set it to **Hooks** and select **loop entry before/loop entry after/middle posts loop**
2. In **Customizer > Layout > Blog/Archive** set the blog layout to **covers** or **grid**
3. Enable masonry
4. Check the blog page
Closes Codeinwp/neve-pro-addon#1471.

fix: blog custom layout inside loop with masonry

---

inc/compatibility/woocommerce.php

Removed the code that changes the category description and shops content position.
YES
- Go to woo category in wp dashboard and add a description
- Add page content on shop page
- Check the shop and the category page
Closes #3004 .

Fix archive shop description

---

header-footer-grid/Core/Builder/Abstract_Builder.php

Remove alignment classes for the primary menu on new skin as the control isn't available anymore.
NO
- Use the old version of neve (old skin)
- Align the sidebar menu to right/center on all devices 
- Switch to the new version
- Menu should be aligned left
Closes #3014.

fix: alignment classes still apply on new skin for primary menu when they shouldn't 

---

assets/scss/components/compat/woocommerce/_account.scss

There were some float options on the login button and on the forgot password that were breaking the layout of the form.
YES
https://vertis.d.pr/uDZMrm
- Import a starter site with WooCommerce
- Log out and go to the my account page
- Check that the form is not looking bad
Closes #3022.

Fix woo account login form

---

header-footer-grid/Core/Components/FooterWidgetOne.php

Fixes issue where footer widgets one component was not showing widgets controls in WordPress version 5.7.2
NO
- Install core version 5.7.2 (you can do that via WP-CLI using `wp core update --version=5.7.2 --force`);
- Footer Widgets One footer component should show the widget control;
- Everything should work fine on 5.8;
Closes #3013.

fix: footer one widget not showing up on 5.7.2 [closes #3013]

---

inc/customizer/controls/react/src/builder/components/Builder.tsx

- Fixes the auto-scroll functionality for the header/footer builder;
- Fixes event binding done wrongly - it was running more than once;
NO
- Go into the customizer
- Open the header or footer panel
- The header panel should scroll the preview to top
- The footer panel should scroll the preview to the footer
// Closes #.

fix: hfb not scrolling to header/footer on panel expansion

---

assets/scss/components/elements/blog/_comments.scss
assets/scss/elements/blog/_comments.scss
inc/views/partials/comments.php

Wrap the children of comments (replies) with a list role and open a new list for them.
This should make it compatible with the correct usage of ARIA roles, and Improve lighthouse compatibility.
NO
1. Post a comment on a blog post.
2. Reply to that comment.
3. Generate the Lighthouse report and check this accessibility audit.
@abaicus Can you let me know if the CSS changes I made are ok, or if you see any issues with the current changes to the HTML structure?
Closes #2974.

fix: comment reply markup

---

assets/scss/components/compat/woocommerce/_nav-cart.scss

Fixes cart icon component vertical alignment when there's a label
YES
- Add the cart icon component in the header
- Add a label to the icon
- The icon should be aligned properly 
Closes #3035.

style: fix cart icon misalignment with label [closes #3035]

---

assets/scss/components/elements/navigation/_nav-menu.scss
assets/scss/elements/navigation/_nav-menu.scss

Removes caret focus inside the primary menu.
I checked with other popular themes and it seems that all of them lack a focus outline on the dropdowns.
NO
- Add a menu with dropdowns inside the mobile sidebar; 
- There should be no outline on tap the dropdown caret;
Closes #2979.

style: remove caret-wrap focus [closes #2979]

---

assets/scss/components/elements/_content.scss
assets/scss/elements/_content.scss
inc/core/front_end.php

Removes the letterbox effect from video embeds for the following sources:
- youtube.com
- youtu.be
- cloudup.com
- dailymotion.com
- ted.com
- vimeo.com
YES
- Add embeds from the sites mentioned above;
- They should not have the letterbox effect mentioned in the issue;
- This should be fixed on the old skin as well;
Closes #1220.

fix: letterbox effect on video embeds

---

searchform.php

Due to Polylang implementation, we must specify in what language should the search happen.
NO
- Install Polylang, add more languages then translate the posts for each language
- Switch to a specific language and use the search form
Closes #2999.

Fix pll search on other language

---

header-footer-grid/Core/Builder/Abstract_Builder.php

Fixes customizer live refresh selector for header menu sidebar text color. It previously didn't work. 
The default value for the primary menu color is empty on the new skin, so this control should also change that on a new site.
NO
- Make sure you set up a fresh instance and that you don't import the starter content
- Set up a basic primary menu and make sure it's both in the sidebar and on one of the desktop rows
- Go to the mobile sidebar controls inside the customizer
- The text color control should control the primary menu color as well as other components' text color
- The changes should properly reflect on the front end
Closes #2958.

fix: customizer live refresh selector for header menu sidebar

---

assets/scss/components/elements/blog/_single.scss

- fixes tag spacing for posts mentioned in #3041 
- styles the tags block inside sidebars
YES
- add a lot of tags to a post so they go on two rows. spacing should be ok
- add tag blocks inside the sidebar. these should be properly styled
Closes #3041.

fix: tag spacing for posts [closes #3041]

---

assets/scss/components/editor/_typography.scss

Fixes social icons block appearance inside the editor. 
Previously we added the typography and colors to all `.wp-block` elements. Now we do it in a more generic way by styling the following selectors:
```
body .editor-styles-wrapper,
body .editor-styles-wrapper p 
```
NO
- Add a social icons block inside the editor. It should look fine, as opposed to what is described in the issue;
- All typography settings from the customizer should still apply as expected inside the editor;
Closes #3031.

style: apply typography style in a more generic way inside the editor

---

assets/scss/components/compat/woocommerce/_generic.scss

The solution that I've chosen for this is to have the sale tag square as long as the content is small enough.
YES
https://github.com/Codeinwp/neve-pro-addon/issues/1475#issuecomment-908197765
- Install Woo and add some products on sale
- Make the sale tag round in the customizer
Closes Codeinwp/neve-pro-addon#1475.

Fix round sale tag

---

assets/scss/components/compat/woocommerce/_account.scss
assets/scss/components/compat/woocommerce/_blocks.scss
assets/scss/components/compat/woocommerce/_cart.scss
assets/scss/components/compat/woocommerce/_checkout.scss
assets/scss/components/compat/woocommerce/_generic.scss
assets/scss/components/compat/woocommerce/_product.scss
assets/scss/components/compat/woocommerce/_shop-loop.scss
assets/scss/components/compat/woocommerce/single/_reviews.scss
assets/scss/components/elements/_form-elements.scss
assets/scss/components/elements/_sidebar.scss
assets/scss/components/elements/blog/_single.scss
assets/scss/components/main/_extends.scss
assets/scss/woocommerce/_cart.scss
assets/scss/woocommerce/_checkout.scss
assets/scss/woocommerce/_generic.scss
e2e-tests/cypress/integration/customizer/form-fields/form-fields.spec.ts
inc/core/settings/mods.php
inc/core/styles/frontend.php
inc/customizer/options/form_fields.php

Goes together with [this PR](https://github.com/Codeinwp/neve-pro-addon/pull/1543), but should still work fine with the old version of Pro. It's just some minor CSS rules removed over there.
Removes the form fields spacing and from label spacing controls inside the customizer;
Adds 20px distance for WooCommerce forms (Checkout, My Account, etc);
Removes any other margin we used to have on generic form fields;
Fixes Password Protected posts style. They will be left-aligned from now on;
Yes
- Nothing should be broken with forms - in terms of how it looks;
- Everything should still work inside the customizer as expected;
- Create a password-protected post;
- The password form should look ok and be left-aligned;
Closes #2996
Closes #3042

chore: drop form fields & labels spacing controls & fix password-protected posts

---

e2e-tests/cypress/fixtures/customizer/hfg/menu-item-alignment-setup.json
e2e-tests/cypress/integration/customizer/hfg/hfg-menu-item-alignment.spec.ts

Adds a cypress test for checking the menu subitems alignment, as it was a regression issue. 
This was part of the cypress dojo.
NO
- All specs should pass the pipeline
Closes https://github.com/Codeinwp/neve/issues/3061

Add cypress test for sidebar menu subitems alignment

---

inc/compatibility/elementor.php

Currently customizer fails to load when elementor-pro is installed but no "product" or "product-archive" template is present. This happens because on `inc/compatibility/woocommerce.php` L114, `NeveReactCustomize.elementor` is set to `{ hasElementorProductTemplate: "0", hasElementorShopTemplate: "0" }` as `Elementor::has_template` returns string value instead of bool or int. In JavaScript land, "0" is a truthy value, unlike php thus resulting in an error being thrown.
NO
- Add neve (master) & elementor-pro to a wordpress site 
- Open customizer. You'll see customizer sections fail to load
- Merge PR
- Open customizer again. It should load properly now

Fix customizer load error with elementor-pro

---

assets/scss/components/elements/_content.scss
assets/scss/components/main/_typography.scss

Fixes issue with list indents interfering with some block styles that contained ul/ol tags.
YES
- Add some lists that have multiple indent levels;
- The lists should have spacing to the left;
- Add blocks that contain ul/ol tags (you can try the ones mentioned in the issue [here](https://github.com/Codeinwp/neve/issues/3028));
- These blocks should look fine, having no space on the left side;
- No other lists inside the theme should be affected (Navigation Menus, or any other component using `<ul>` & `<ol>` tags;
- Blocks mentioned inside the issue should not have the list-style (the dots/numbers before li elements), but lists in content should have them;
Closes #3028.

fix: list indent overrides some blocks that contain ul/ol

---

assets/scss/components/editor/_typography.scss
assets/scss/components/main/_typography.scss

Underline links on page/post content and in text widgets
YES
We need to be compliant with this rule:
> When links appear within a larger body of block-level content, they must be clearly distinguishable from surrounding content (Post content, comment content, text widgets, custom options with large blocks of texts). https://make.wordpress.org/themes/handbook/review/accessibility/required/#content-links
I identified in our theme 4 areas: post content / page content / comment content / text widgets and I added a rule that links in those areas to have an underline.
You should:
- Check those areas and see if underline applies
- Let me know if you think we should add the underline for other links
Closes #3087.

Fix underline links

---

header-footer-grid/Core/Components/Abstract_Component.php

Font family was corrupting when saving on HFG builder. It's fixed with this PR.
YES
- Go Customizer -> Header -> Click 'set' icon of the Primary Menu -> Go 'Style' tab then, change font-family.
- Make sure the font that you chosen works well on customizer preview and fontend.
Closes #3055 .

Fix: Font family saving issue on the Header Nav widget

---

inc/admin/dashboard/main.php

Fix i18n of Menu item and Page title "Neve Options".
The current menu item and page title are Neve + '  ' + 'Options', which is a problem for i18n of languages where this concatenation should be reversed, eg.: Portuguese translation: "Opções do Neve".
Currently it's impossible to correctly translate this, as the menu renders "Neve Opções", which wrong.
YES
Closes #3111.

[i18n] Fix hardcoded concatenation for "Neve Options" menu item and page title

---

.storybook/theme.js
assets/apps/customizer-controls/src/common/Accordion.js
assets/apps/customizer-controls/src/scss/_button-appearance.scss

Provided a temporary fix for the huge icons in storybook.
NO
- Open storybook
- Go to Accordion or Button Appearance components
- The arrow icons should have a normal size
Closes #3046.

Fix: storybook icons appearance [ref #3046]

---

inc/views/template_parts.php

Changes post title tag to h2 on archive
NO
- The post title tag should be h2 instead of h3 
- There should be no visual difference 
- The options that should be affecting the post title should work as expected
Closes #3107

chore: change archive post title tag back to h2 [closes #3107]

---

stories/hfg/BuilderColumns.stories.js

Stoped storybook page from returning a TypeError when the number of columns is not in range in the Builder Columns Control.
NO
- Go to storybook > HFG > Builder Columns Control
- Clear the columns number field (or set a number that is not in the range 1-5)
- The page should not return an error and the current number of columns should be equal to the last valid input.
Closes #3048.

fix: handle invalid number of columns in storybook

---

assets/js/src/customizer-preview/app.js
assets/scss/components/elements/_sidebar.scss
inc/views/layouts/layout_sidebar.php

With the PR, if the content width of the layout that has "Others" type exceed the 95%, hide sidebar on the customizer preview.
Before the PR, page reload was required.
Note: I have tested the other post types such as blog/archive, the sidebar always seems even the content width is 100%. So, I'm not sure if we use the fix these.
My some findings before the PR:
- blog/archive - it's not working, the sidebar shows all time even if the content %100.
- single post - it's not working, the sidebar shows all time even if the content %100.
- shop/archive - it's not working, the sidebar shows all time even if the content %100.
- single product - when content width is exceed the 95%, the sidebar is hidden on frontend but it's showed on customizer
- other - when content width is exceed the 95%, the …

Fix sidebar visibility on customizer preview

---

inc/compatibility/woocommerce.php

Wrap the customer details in a div and make sure the open div has the lowest priority so it would execute before all other plugins.
NO
1. Install and Activate the [Food Store](https://wordpress.org/plugins/food-store/) plugin
2. Open the Checkout page and check the fields
3. Test with and without Neve Pro. When testing with Neve Pro make sure you check with other layouts too
Closes #3049.

Food store compatibility fix

---

inc/views/product_layout.php

There was unclosed div tags on shop page on Neve if Neve Pro is disabled. It's fixed with the PR.
NO
- Make sure there are no unclosed tags in the shop page. It should work the following cases:
-- Only Install Neve
-- Install Neve + Neve Pro
- Make sure there are no unnecessary a element on the shop page. (#3076)
Closes #3076,#3008.

Fixed the unclosed div element on the shop page

---

inc/compatibility/amp.php

Due to aria-role attribute used in the carret submenu div, the AMP validator was reporting error with the menu.
No
- Activate AMP in developer mode
- Install Neve and configure one menu for Primary menu with 2 levels menu items
- Check that no issues are reported by AMP validator, previously we had warnings reported on carret icon. 
- Make sure that each item from the menu is reachable by keyword navigation both on amp/non amp and on mobile/desktop
Closes #3110

fix: remove aria-role on carret for menu, breaking AMP validator

---

assets/scss/components/hfg/style.scss
assets/scss/style.scss
header-footer-grid/Core/Builder/Abstract_Builder.php
header-footer-grid/Core/Components/Abstract_Component.php
header-footer-grid/Core/Components/CartIcon.php
header-footer-grid/templates/components/component-cart-icon.php
header-footer-grid/templates/components/component-palette-switch.php
inc/compatibility/woocommerce.php

Makes the Palette `Switcher`, `Cart` and `My Account` **(Pro Component)** header components labels inherit the font styles (family and weight) of the `Primary Menu` and `Secondary Menu` if these are next to each other (in the same slot, in the same group);
YES (might change things for people who had these components next to each other)
**Before:**
**With this PR:**
- Set up a header that has a primary/secondary navigation component with a different font family;
- Any of the components mentioned in the summary, when placed in the same slot (i.e. form a group) with either one of the ones mentioned above should inherit Font Family and Font Weight from the menu;
Closes #2491.

fix: HFG Components Labels Font Styles

---

assets/scss/components/elements/navigation/_nav-menu.scss
header-footer-grid/templates/row-wrapper-mobile.php

- adds `data-row-id` data attribute to the header mobile sidebar;
- fixes issue with styling done on the `[data-row-id]` selector not applying;
- fixes issue with dropdowns inside the mobile sidebar inheriting overlay color instead of being transparent;
YES
For #3116:
---
- follow the #3116 issue reproduction steps; 
- the colors should be applying properly on the components inside the mobile sidebar;
- all other styles should be working fine 
For #3127:
---
- add a primary menu with dropdowns inside the mobile sidebar;
- add a background image and make sure it has an overlay;
- dropdowns inside the mobile sidebar should not have a background color like described in #3127;
Closes #3116
Closes #3127

fix: header mobile sidebar components had some wrong styles

---

assets/apps/customizer-controls/src/builder/components/Row.tsx

Fixes issue where footer components were not sent back to the components sidebar and the add component popover.
NO
- Fill a footer row with components (it should have more than 1 column);
- Switch the columns number to something lower than initial;
- The components that disappeared from the footer row should be reinstated inside the customizer sidebar and the popover for adding components.
Closes #3101.

fix: footer components not updating after columns change [closes #3101]

---

assets/scss/components/elements/_content.scss

Removes clearfix on `.nv-content-wrap` and `.excerpt-wrap`. It seems that it wasn't doing anything. 
NO
- The posts archive should still work as expected with all the settings inside the **Layout  > Blog / Archive** section;
- Nothing should go out of line;
- The layout shouldn't break;
Closes #3064.

chore: remove useless clearfix [closes #3064]

---

.github/workflows/test-php.yml

Phpstan version hard-coded updated as 0.12.99.
In the free time, we will add support for the phpstan v1.0 and update phpstan version again for the v1.0
NO
Closes #3192 .

chore: phpstan version hard-coded updated as 0.12.99 on gh action

---

header-footer-grid/Core/Customizer.php
header-footer-grid/Traits/Core.php

Removed unused method introduced by this commit 8 months ago: https://github.com/Codeinwp/neve/commit/a84353d56ec3af7c14ad6c23d0e8b73f4c30f891 things seem to be working fine without it so went ahead and removed the code all together
NO
- Install this patch
- Test that Header Footer Grid operation is fine
Closes #2992

Removed unused get_assets_suffix() method

---

assets/apps/customizer-controls/src/repeater/Repeater.js

The repeater control shouldn't enable publishing inside the customizer on load.
This will still happen if the values were previously saved wrong in the DB.
NO
- Add a header/footer component that uses a repeater 
- Upon customizer load, the publish button shouldn't be enabled on a clean instance
closes #3194.

fix: repeater control adding unused values to the db

---

header-footer-grid/Core/Builder/Abstract_Builder.php

Fixes inconsistency where values for the layout were falling through even though they were non-existent
NO
Reproduction steps here: https://github.com/Codeinwp/neve/issues/3195
Fixes #3195.

fix: edge case of footer columns not having a proper corresponding layout

---

inc/core/styles/css_prop.php

Fixes issue with inline styles breaking when using a quoted value for any font family control inside the customizer. 
At some point we started quoting font-family inside the db and then removed it.
NO
- Import this file with customizer-import-export (make sure you rename it to have a `.dat` extension);
[neve-export (3).txt](https://github.com/Codeinwp/neve/files/7467931/neve-export.3.txt)
- On the old version, inline styles should be broken;
- Using the version on this branch, the issue should be fixed;
Closes #3189.

fix: styles breaking due to old font-family values containing quotes and slashes 

---

inc/compatibility/woocommerce.php

Seems that the container we've added to fix compatibility with foodstore plugin was closing too early so the button wasn't in that container.
I just changed the priority of when we close the 'nv-customer-details' div.
NO
- Test that nothing breaks on the checkout page with all the checkout settings.
- Check the comment that Stefan added in the issue, update the instance he already created and see if the problem is solved
- 
Closes #3201.

Fix compatibility with cartflows plugin

---

assets/apps/customizer-controls/src/rich-text/RichText.js
assets/apps/customizer-controls/src/rich-text/RichTextComponent.js
e2e-tests/cypress/integration/customizer/layout/blog-archive-settings.spec.ts
header-footer-grid/Core/Components/CustomHtml.php
inc/customizer/controls/react/rich_text.php

Solve regression #3178 and improve Safari support
NO
1. Use a HTML component inside the Header that already has data set before using the new component
2. Check that when switching to the new control the content lines are preserved
3. Check that on Safari it does not break the Customizer
4. Check that the code editor is being displayed correctly
Closes #3178.

fix: solve new lines for existing content and safari support #3178

---

header-footer-grid/Core/Builder/Abstract_Builder.php

The sidebar had some border controls that didn't do anything because they shouldn't be there.
NO
- Go to Customizing -> Header -> Mobile Sidebar
- There shouldn't be any controls for the border
Closes #3206.

Fix: removed redundant border settings from sidebar

---

assets/scss/components/compat/woocommerce/_widgets.scss

Fixes the issue with the clear button inside WooCommerce widgets filter dropdowns.
NO
-  On a WordPress instance with Woocommerce
-  Go to Appearance->Widgets and we add "Filter products by Attribute", this must be set to dropdown (https://vertis.d.pr/MOIp17)
- After selecting something in the dropdown, the clear button should be clickable
Closes #2943.

fix: clear button not clickable on woocommerce widget filter dropdowns

---

assets/js/src/frontend/hgf.js
assets/js/src/frontend/navigation.js
assets/scss/components/elements/navigation/_nav-menu.scss
assets/scss/components/elements/navigation/_nav-toggle.scss
assets/scss/components/hfg/frontend/layout/_mobile_sidebar.scss
assets/scss/components/main/_a11y.scss
header-footer-grid/templates/row-wrapper-mobile.php

Changes first focus inside the mobile menu to the close button instead of the first element. We must have an initial focus according to a11y guidelines, but I think it's fine if we have it on the close button instead of the menu item. 
This is what twentytwentyone does as well. 
Also changes some of the CSS to ensure we don't go over the limit.
cc: @cristian-ungureanu just keeping you in the loop 
YES
- Open the site on a mobile device (or browserstack) and open the mobile sidebar;
- There should be no outline on menu items, but the close button should be now in focus;
- Focus should still work on the desktop version of the site;
Closes  #3154;

fix: move autofocus to close button inside mobile nav menu

---

assets/js/src/customizer-preview/app.js
inc/core/styles/frontend.php
rollup.config.js

It seems like the sidebar on the 404 page was not working correctly.
To see the issue you should:
1. Disable "Enable Advanced Options"
2. Set a general value, let's say sidebar right and save customizer
( Not 100% sure 1 & 2 are required )
3. Enable "Enable Advanced Options"
4. You'll notice that the sidebar position is controlled from BLOG / ARCHIVE control and the sidebar width is controlled by OTHERS control
This PR fixes this behavior and makes the sidebar on the 404 page controlled by BLOG / ARCHIVE.
Also, I saw that[ those two files](https://github.com/Codeinwp/neve/tree/master/inc/customizer/options/js) were replaced and their function was included in [app.js](https://github.com/Codeinwp/neve/blob/master/assets/js/src/customizer-preview/app.js). When I tried to fix this issue, I …

Fix sidebar on 404 page

---

assets/apps/customizer-controls/src/responsive-range/ResponsiveRangeComponent.js
assets/apps/customizer-controls/src/typeface/Typeface.js

This PR makes all responsive controls reset the values for all devices when clicking the reset button (the problem was with the range and number controls).
NO
- In the customizer go to a responsive range control (for example Header -> Primary Menu -> Items Spacing) and to a number control ( Typography -> General -> Font Size )
- Change the values for all devices and then click the reset button
- The values should be reset for all devices
Closes #3197.

Fix: reset button on range control resets all devices

---

inc/views/pluggable/pagination.php

Before the PR, the hook **neve_before_pagination** wasn't working on the first page of the pagination.
YES
- Make sure you've enough posts to see pagination on blog archive page and enable pagination for the blog/archive.
- Add a snippet for the **neve_before_pagination** hook, it should work on the all pages that contains pagination.
- Make sure there is no regression on the pagination feature.
Closes #3253,codeinwp/neve-pro-addon#1601

fix: neve_before_pagination hook on the first paginated page

---

assets/apps/customizer-controls/src/builder/components/ComponentsPopover.tsx
assets/apps/customizer-controls/src/builder/scss/_items-popover.scss
inc/core/front_end.php

chore: remove byline in header components inserter upsell
- Into Customizer > Header 
- Click the add button on any row
- The description inside the upsell (text before button) should not be there anymore
Closes  Codeinwp/neve-pro-addon#1724.

chore: remove byline in header components inserter upsell

---

header-footer-grid/Core/Components/Abstract_Component.php
header-footer-grid/Core/Components/CartIcon.php
header-footer-grid/Core/Components/PaletteSwitch.php

The off-canvas sidebar opens from that button, only if the class "cart-is-empty" is not present. When you add a product to the cart, it's added via ajax and the "cart-is-empty" class is not removed.
This PR fixes the behavior and it removes the `cart-is-empty` class when a product is added via ajax add to cart.
NO
- Install neve and neve pro
- Set cart icon component in header with off-canvas layout
- Go to the shop page and have an empty cart
- Refresh the page
- Add a product to the cart
- Close the sidebar that opens
- Try to click on the cart icon, the sidebar should open
Closes Codeinwp/neve-pro-addon#1745.

Fix cart component offcanvas

---

.github/workflows/build-dev-artifacts.yml
assets/scss/components/elements/_mega-menu.scss
bin/envs/mega-menu/start.sh
e2e-tests/cypress/integration/mega-menu/mega-menu-test.spec.ts

- fixes issue with dropdowns inside mobile-sidebar when using a mega-menu
- should be tested both with the class-based mega-menu and the PRO mega-menu feature
- adds cypress tests for the mega-menu in the free version
NO
- You can follow the steps described here: Codeinwp/neve-pro-addon#1779
- The dropdowns should be in working order
Closes  Codeinwp/neve-pro-addon#1779.

fix: dropdowns display in mobile sidebar mega-menu

---

assets/scss/components/elements/navigation/_nav-menu.scss

Links in menu to same page, that have hashes will not have the active-item color applied anymore.
YES
- Import copywriter demo;
- Change the primary menu active link color;
- Add the `Home` page to the menu;
- On the homepage, the only link that has an active color should be the `Home` link
Closes #3234.

fix: menu links to in-page sections have active color

---

header-footer-grid/Core/Builder/Header.php
inc/core/theme_info.php
inc/customizer/options/upsells.php
phpstan.neon

Customizer upsells should still be visible if no license has been activated, or the license is invalid
NO
- Install the version from this PR; 
- Add the pro version without a license;
- The upsells should still be visible;
Closes Codeinwp/neve-pro-addon#1674.

keep upsells when license is invalid

---

assets/apps/customizer-controls/src/builder-upsell/Upsells.tsx
assets/apps/customizer-controls/src/controls.js
assets/apps/customizer-controls/src/scss/_upsell.scss
assets/apps/customizer-controls/src/style.scss
assets/apps/dashboard/src/Components/Content/FreePro.js
header-footer-grid/Core/Customizer.php
inc/admin/dashboard/main.php
inc/admin/dashboard/upsell_features.php
inc/customizer/controls/react/upsell_section.php
inc/customizer/options/upsells.php

Changed the Customizer upsell section as specified [here](https://github.com/Codeinwp/neve-pro-addon/issues/1721)
This is now not required as mentioned [here](https://github.com/Codeinwp/neve-pro-addon/issues/1721#issuecomment-998780124)
A new PR was created for this here: https://github.com/Codeinwp/neve/pull/3284
YES
1. Open Customizer with Neve Pro deactivated
2. Check the upsell section and the links
Closes Codeinwp/neve-pro-addon#1721.

Feat: changed upsell section customizer

---

.github/workflows/test-php.yml
assets/apps/customizer-controls/src/controls.js
assets/apps/customizer-controls/src/documentation-section/Documentation.tsx
assets/apps/customizer-controls/src/scss/_documentation.scss
assets/apps/customizer-controls/src/style.scss
header-footer-grid/Core/Customizer.php
inc/customizer/controls/react/documentation_section.php
inc/customizer/options/main.php

Added a section in customizer on the main panel that links to the documentation for Neve
YES
1. Open Customizer check that the Section is present in both Free and Pro and that it links to the documentation in a new tab.
Closes Codeinwp/neve-pro-addon#1716.

Feat: Documentation Section in Customizer

---

inc/views/pluggable/metabox_settings.php

The function right [here](https://github.com/Codeinwp/neve/blob/master/inc/views/pluggable/metabox_settings.php#L149) returns the post/page ID using `global $post;`. On the shop page, the global post is alternated by WooCommerce as the shop page is not only a page but an archive too. In this case the global $post returns the id of the last product added and not for the page id causing the custom meta not to override the settings from the customizer. This PR fixes that.
YES
- Import Jewelrey starter site
- Try to place the sidebar left in customizer and right in custom post meta. It should not work
- Add this PR and check if this is working
- Check the off-canvas layout form customizer too. Select it from the Customizer and remove it from the custom meta.
Closes …

Fix shop sidebar

---

inc/views/cover_header.php

Hide the whole cover if the title is disabled from meta.
YES
- Enable page cover
- Disable the title from a page meta
- Check the page, the cover should disappear, not just the title in that cover
Closes Codeinwp/neve-pro-addon#1758.

Page cover

---

assets/apps/customizer-controls/src/typeface/Typeface.js
assets/apps/customizer-controls/src/typeface/TypefaceComponent.js
globals/utilities.php
header-footer-grid/Core/Components/Abstract_Component.php
inc/customizer/controls/react/typography.php
inc/customizer/loader.php
inc/customizer/options/buttons.php
inc/customizer/options/form_fields.php
inc/customizer/options/typography.php

When selecting the font weight, only the ones that are supported for the used font family are displayed.
NO
- The following controls should display the available weights for the selected body font family: 
1. Buttons -> Button Text
2. Form Fields -> Input Text and Form Labels
3. Typography -> General
4. Typography -> Blog -> Blog Archive -> Post Excerpt  and Post Meta
5. Typography -> Blog -> Single Post  -> Post Meta
- And the following for the heading font family:
1. Typography -> Headings
2. Typography -> Blog -> Blog Archive -> Post Title
3. Typography -> Blog -> Single Post  -> Post Title and Comments Reply Title
The HFG components that use a font family selector should also be checked: menus, custom html, contact, and copyright.
Let me know if I missed any font-related control. …

Feat: Display only the weights that are available for the selected font

---

inc/compatibility/elementor.php

* Elementor Pro displaying location was refactored to leverage global Elementor [elementor_theme_do_location()](url) function.
_ref: https://developers.elementor.com/docs/themes/registering-locations/_
NO
- Make sure there is no regression on our Elementor compatibility support
Closes [#https://github.com/Codeinwp/neve-pro-addon/issues/1797.](https://github.com/Codeinwp/neve-pro-addon/issues/1797)

refactor: elementor do_location usage method refactored

---

assets/apps/components/src/Controls/RadioImage.js

Fixes some errors inside the radio-image react controls initially introduced in PR https://github.com/Codeinwp/neve/pull/3270
NO
- Check that the locked layouts inside **WooCommerce** > **Checkout** still work as before;
Closes #3305

fix: react errors from radio-image control

---

inc/compatibility/woocommerce.php

Natively, if cart item has discounted price; WooCommerce doesn't show regular price, just shows discounted price on the cart. With the PR, the both of the prices(discounted, sale prices) are shown on the cart.
before: https://vertis.d.pr/NnA0MV
after: https://vertis.d.pr/uu49bD
YES
- Add some products(has sale price, has not sale price) to the cart
- If product has discounted price, the both prices should be shown (regular price should be shown as crossed)
Closes codeinwp/neve-pro-addon#1581.

feat: show regular price too with the sale price on the woocommerce cart

---

assets/apps/components/src/Controls/Background.js
globals/sanitize-functions.php
header-footer-grid/Core/Builder/Abstract_Builder.php
header-footer-grid/Core/Builder/Header.php
header-footer-grid/Traits/Core.php

Fixes sanitization for Background customizer control
NO
- Make sure WP_DEBUG is turned on;
- Inside customizer go to an HFB row settings panel;
- Set a background image and delete both of the values inside the position fields under the image;
- Save the customizer options;
- There should be no warning on the front end;
- Upon reloading the customizer, these values should be 0;
Closes #3300.

chore: fix sanitization for background customizer control

---

assets/scss/components/elements/_mega-menu.scss
assets/scss/components/hfg/style.scss
header-footer-grid/Core/Builder/Abstract_Builder.php

- fixes issue with grouped components adjacent to mega-menu not being clickable;
NO
- Set up a mega-menu with the pro version or with classes;
- Add a button next to it in customizer; 
- The button should be clickable
Closes Codeinwp/neve-pro-addon#1796.

fix: grouped header items next to mega-menu not clickable

---

header-footer-grid/Core/Components/PaletteSwitch.php

The color palette and fallback font `:root` CSS properties were outputted twice when using the palette switcher inside HFB.
NO
- Add the palette switcher to the header;
- The switch should still work fine;
- It should still work fine with the `Automatically adjust color scheme` option inside the customizer;
- In the inspector, when scrolling the styles panel all the way down (like in the issue screenshot), the root variables should not be available twice;
Closes #3317.

fix: root css properties outputted twice when using dark mode toggle

---

assets/apps/dashboard/src/Components/Content/Start.js
assets/apps/dashboard/src/scss/components/_card.scss

- I removed the custom style added for the secondary button from the Starter sites card
- I refactored the component so the buttons would have a wrapper only if the pro is active and there are two buttons
- Changed the CSS to display grid to easily add a gap between buttons
YES
- Check the Starter sites card when pro is not active and check the secondary button. It should look like other secondary buttons
- Check the Starter sites card when pro is active. The button should hold its position ( bottom of the card )
Closes #3311.

Remove secondary button style added in Neve

---

inc/admin/dashboard/main.php
inc/admin/dashboard/plugin_helper.php

I updated the version of recommended plugins if a plugin is already installed.
NO
- Get this PR
- Install Otter
- Check the version of otter in the recommended plugins tab
- Edit the version in otter's main file
- Check if the version in recommended plugins is updated
- Before this, the version wouldn't change
Closes #3250.

If a recommended plugin is installed get its version locally 

---

assets/scss/components/elements/blog/_blogpost-meta.scss

This should fix the date in the meta on the blog archive.
YES
- This https://snipboard.io/hlPAEc.jpg should not happen anymore
- If a date is too long, the whole date should be on a new row, not just the year or a part of it.
- Also check meta on a single post and make sure nothing breaks there.
- 
- 
Closes #3222.

Fix: Date in meta should not break

---

inc/views/nav_walker.php

Allows additional classes on the mega-menu columns.
NO
- Create a mega-menu with the documentation [here](https://docs.themeisle.com/article/964-neve-mega-menu-setup);  
- Try adding additional classes to the column elements. These should appear inside the inspector on the front-end;
- It should work with both the free version and the pro version using both mega-menu approaches;
Closes #3153.

fix: allow additional classes on mega-menu column items [closes #3153]

---

inc/customizer/options/base_layout_single.php

Fixxed Single Post section not being displayed for old skin.
NO
1. Check that on the old skin in Customizer > Layout > Single Post is being displayed
2. Check that this works with Free and PRO
Closes #3299

fix: solve customizer display old skin

---

assets/apps/components/src/Common/svg.js
assets/apps/customizer-controls/src/radio-buttons/RadioButtonsComponent.js
start.php

Adds 6 icon choices for scroll to top created by @mghenciu here: https://www.figma.com/file/QklXyJh0XHVzq2h4IpPNaz/Neve-options?node-id=2334%3A19104
NO
- Switch between different icons, they should change the icon in the scroll to top button
Closes Codeinwp/neve-pro-addon#1575

More scroll to top icons

---

assets/apps/dashboard/src/scss/components/_card.scss

By default the external link pulls the color from WP admin css, this change specifies an external link color for cards component so it's not changed by the admin theme
NO
- Change the WordPress admin profile theme to the modern theme: https://prnt.sc/26js45b
- The external link in the Templates Cloud card should not change color
Closes #3266

set card external link color

---

assets/apps/dashboard/src/Components/Card.js
assets/apps/dashboard/src/Components/Content/Start.js
assets/apps/dashboard/src/scss/components/_card.scss

Added two new cards on the Start page of the Neve dashboard: WooCommerce Booster and Block Editor Booster.
Also, added a lock icon for those cards that describe pro features.
NO
- Go to Neve dashboard, on the Start page
- These new cards should be displayed when the user is not pro ( WooCommerce Booster and Block Editor Booster)
- The Templates Cloud card should have the lock icon only when the user is not pro
Closes Codeinwp/neve-pro-addon#1673.

feat: add dashboard cards for woocommerce and block editor boosters

---

assets/scss/components/elements/blog/_comments.scss
inc/views/partials/comments.php

Changes the comment reply title to an H2 tag. 
Also updates the `# thoughts on X` heading to an H2 tag.
NO
- Check the comment from the `Leave a reply` heading and the comments heading;
- These should now be H2 level headings;
- The styles should still apply in the same manner as before;
- It should work just as before with and without comments;
Closes #2935.

fix: change comment reply title tag to H2 [a11y][closes #2935]

---

assets/scss/components/elements/_content.scss

Applies Y-axis margin to `ul` & `ol` tags inside nested content.
YES
- Add a list block inside a columns block;
- It should now have the same Y-axis margin as lists that are placed directly inside the content;
Closes #3326.

style: ul & ol y-axis margins not applying in nested HTML tags inside content wrap

---

assets/scss/components/hfg/style.scss
header-footer-grid/templates/components/component-copyright.php

fix stripping of spaces from copyright component
NO
- Add the copyright component in the footer
- Add the following text to the copyright component:
` <a href="https://themeisle.com/themes/neve/" rel="nofollow">Neve</a> powered by <a href="http://wordpress.org" rel="nofollow">WordPress</a>
`
- Check the frontend, with this fix the spaces should be present. Without this fix the spaces are stripped
Closes #3325

fix: stripping of spaces from footer copyright component

---

assets/apps/dashboard/src/Components/Content/Start.js

Opens Get Neve Pro button in a new tab when clicked.
NO
- Click the "Get Neve Pro" button, it should open in a new tab
Closes Codeinwp/neve-pro-addon#1739

chore: open Get Neve Pro button in new tab

---

assets/scss/components/compat/_elementor.scss
package.json

Fixes Elementor text widget list style issues.
YES
1. Add a text widget inside Elementor;
2. Add `ul`/`ol` lists;
3. They should have padding and proper list styles;
Closes #3364.

fix: elementor list styles & CSS size improvements [closes #3364]

---

assets/apps/customizer-controls/src/rich-text/RichText.js

Fixed an issue where tinymce would strip empty tags.
The `verify_html` option should not be required as the input is sanitized in WP upon save.
NO
1. Add a Custm HTML component and go into `Code` view
2. Copy this `<a href="https://instagram.com/" target="_blank"><span class="dashicons dashicons-facebook"></span></a>` and check that after toggling to View the element is being rendered and is stil displayed in code view
Closes #3334.

fix: tinymce behaviour on empty tags #3334

---

assets/scss/components/elements/blog/_blogpost-default-alt.scss

Fixed padding on blog list layout for mobile devices.
NO
- Switch to list layout in Customizer -> Layout -> Blog
- Add different paddings for each device
- Check if the padding is working
Closes Codeinwp/neve-pro-addon#1847.

Fix padding on blog list

---

assets/scss/components/elements/form-elements/_inputs.scss

The issue comes from `:focus-visible` pseudo-class. It seems that Safari supports it only in the latest version https://caniuse.com/?search=focus-visible. 
So what happens here is this: The SCSS is built and the result in CSS is something like:
```
input:read-write:focus, input:read-write:focus-visible ...{ 
outline: 0;
box-shadow: 0 0 3px 0 var(--nv-secondary-accent);
--formFieldBorderColor: var(--nv-secondary-accent);
}
```
Because older versions of Safari don't know about `:focus-visible`, it just ignores the whole CSS block.
NO
- Check focus on inputs, textareas, select fields
Closes #3366.

Fix input focus on safari [#3366]

---

assets/apps/components/src/Common/MediaLibrary.js
assets/scss/components/elements/navigation/_nav-brand.scss
header-footer-grid/Core/Components/Logo.php

I've improved support for SVG, it should allow use of SVG inside the Logo and will allow crop skipping since it is not possible on SVG.
NO
1. Upload a SVG using [SVG Support](https://wordpress.org/plugins/svg-support/) plugin.
2. Set the SVG as a LOGO, check that you are allowed to skip crop.
3. Check that all settings are applied correctly, eg. Size of Logo.
Closes #3350.

fix: improve support for SVG allow crop skipping

---

assets/apps/customizer-controls/src/scss/_repeater.scss

I changed the css for Repeater component so that titles that are very long in case the user decides to add html will display cleaner and will be caped.
This is also a supporting change for  Codeinwp/neve-pro-addon#1851
YES
1.  Add the contact component.
2. Add a very long content
3. Check that the title is not overflowing.
Closes Codeinwp/neve-pro-addon#1851.

fix: limit title lenght display Codeinwp/neve-pro-addon#1851

---

assets/scss/components/compat/woocommerce/_product.scss

Added a width for the product addons container
NO
- Install this patch
- Install the WooCommerce Product Add-ons plugin available on [this page](https://handbook.vertistudio.com/3rd-party-products/#woo-addons)
- Edit a product, and add some new fields - https://vertis.d.pr/fEqoXi
-Check the product page 
The issue with alignment should no longer be present.
Closes #3257

fix: woocommerce product addons alignment

---

assets/apps/customizer-controls/src/builder/Control.js

Changed the selector for the builder components on HFG for Page Header as to not trigger error on mixed versions (theme/pro addon) inside Customizer.
NO
1. Use the `master` version of the Neve PRO with the build from here.
2. Check that Customizer is loading properly and no errors are thrown inside the console.
Previously an error was thrown, check the linked issue for more details.
Closes #3401.

fix: page header support with mixed theme versions #3401

---

assets/apps/metabox/src/components/MetaFieldsManager.js
assets/apps/metabox/src/editor.scss

Reset post custom content width when sidebar position changed and show a notice when content width is above 80
NO
- Install this patch
- Try changing the post content width to any value
- If you switch to one of the sidebar layouts, the custom width value will reset to 70
- If you change the custom width to above 80 a notice will show informing that the sidebar width might be affected.
Closes #3370

Reset post custom content width when sidebar position changed

---

composer.lock

Update SDK to fix the issue with the auto-update link not appearing
Closes Codeinwp/neve-pro-addon#1677.

chore: update themeisle-sdk

---

inc/core/styles/css_prop.php

It seems that we allow values less than 1 for directional controls if the unit is set as EM.
Because we use `absint` function to sanitize the value, when setting any directional control with a value less than 1, `absint` will change that value to 0, `absint(0.9) = 0`.
In this PR I've replaced `absint` with `abs` to make sure the value is positive.
NO
- Have a form on a page. It can be any form. The user had the [Ghostkit](https://wordpress.org/plugins/ghostkit/) Form block.
- Go to customizer -> Form fields and for every control from there, set the unit in EM and the value less than 1.
- After you save in the customizer, make sure the changes apply on frontend too
Closes #3399.

Controls with values lower than 1 are not working

---

inc/views/pluggable/masonry.php
inc/views/template_parts.php

Fix custom layout made with elementor when masonry is enabled.
NO
- Open a Elementor demo
- Create a Custom Layout for the Blog/Archive page
- Enable the Grid Layout for the blog page
- Enable Masonry for the blog page
Closes Codeinwp/neve-pro-addon#1803.

Elementor custom layout header

---

assets/apps/components/src/Controls/NumberControl.js
assets/apps/customizer-controls/src/typeface/Typeface.js
assets/apps/customizer-controls/src/typeface/TypefaceComponent.js
inc/core/styles/css_prop.php
inc/customizer/options/typography.php

Added the "Unitless" option for line-height property 
NO
https://vertis.d.pr/MOfxMK
- In customizer go to typography -> general and change the unit for the line-height
- Check that everything works as expected (on both customizer and front-end )
- Do the same for heading controls
- Check the console to make sure there are no errors
Closes #3225.

Add option to have unitless line height

---

assets/scss/components/compat/woocommerce/_product.scss

Changed the compatibility style for WooCommerce, it was missing the `flex-wrap` property to allow items to flow on a new row if required.
It looked like an issue only on some products that were not using the main style.
YES
Previously:
After changes:
1. enable the new skin in the customization section
2. install the plugin Booking Activities
3. create a product variation that has a booking
4. Choose a product variation type (Activity)
5. Check the booking display on the item
Closes #3161.

fix: added flex-wrap for compatibilities #3161

---

assets/scss/components/main/_typography.scss

Added the following code on the body selector:
```
-webkit-font-smoothing: antialiased;
-moz-osx-font-smoothing: grayscale;
```
YES
- Install the theme
- Import any startersite
- Open the console
- Enable / disable the -webkit-font-smoothing property that exist on body
- Check on Mozilla too
- 
- 
Closes #3408.

Add antialiasing on text

---

assets/apps/dashboard/src/Components/Content/StarterSitesUnavailable.js
assets/apps/dashboard/src/utils/common.js
inc/admin/dashboard/main.php

Fixes edge case where some plugins are not defined in the `neveDash` constant inside the dashboard.
NO
- Go to `inc/admin/dashboard/main.php`;
- Comment line 48 (`'templates-patterns-collection',`);
- Go into the dashboard, the page should load fine;
Closes #3419.

fix: accessing undefined property on object

---

globals/utilities.php
inc/core/styles/css_prop.php

What I did was to have another array same as $value but with float type. Then, in conditions, we use the float value to compare. I changed the '===' with '==' as float(0) is not equal with (int)0
NO
- Have php8 on a site with Neve
- Change the value of a typography control
- Make sure negative values of margins are still working
- Make sure em values can be lower than 0
Closes #3422.

fatal error on php 8

---

views/page-header.php

The `get_the_ID()` function was returning the id of the first post instead of the ID of the blog page. I've replaced `get_the_ID()` with `get_queried_object()` function.
NO
1. Create a fresh WP instance
2. Install Neve (3.2.2) & Neve Pro
3. Import the [Business demo](https://demosites.io/business-gb/)
4. Go on the Blog page
5. You should not see 2 Page Titles anymore
6. Try with blog page and other pages from both customizer and meta  ( make sure the pages don't have the "Page Builder Full Width" template as we don't display the title on that template )
7. Try with posts.
Closes #3432.

Fix meta hide title

---

assets/scss/components/hfg/frontend/layout/_general.scss

Fix the mobile sticky header when not in the global header context.
YES
1. Go to Customizer -> Header -> Global Header Settings -> Style -> Enable Advanced Options, and set to off.
2. Set the Main row of the Header to Sticky only for Mobile, it should be sticky on Mobile and Normal on Desktop
3. Check that it also works when is set sticky for Desktop and Normal for Mobile and both set to Sticky.
Closes #3428.

chore: fix mobile sticky when not in global header context #3428

---

assets/scss/components/main/_typography.scss

Here's what is happening:
In order to prevent the page from scrolling behind the lightbox that they open, they add `overflow:hidden` on `body`. Now, to prevent content shifting ( the scrollbar should disappear due to `overflow:hidden` ) , they are adding a `margin-right: 17px` on the body tag.
In our case, we have an `overflow-x:  hidden` on the `html` tag as well and that keeps the scrollbar active, and those 17px they add are making the content shift.
What I did here was to remove the `overflow-x:  hidden` from HTML tag. We have the `overflow-x: hidden;` on the body tag too and if we remove the one on the HTML tag, nothing should happen.
NO
- On a Windows OS ( you can replicate it on https://browserstack.com/ ) install Neve and …

Content shifting for fancybox [#1468]

---

assets/scss/components/compat/woocommerce/_checkout.scss
inc/compatibility/woocommerce.php

Fixed the compatibility issue with [Klarna Checkout](https://woocommerce.com/products/klarna-checkout/).
What I did was to identify if the paying method is via Klarna and prevent any actions and changes for the checkout page.
NO
-> Before the fix: https://vertis.d.pr/ZpFyau
-> After the fix: https://vertis.d.pr/Uvu47D
1. Install the provided plugin on a fresh instance
2. In [Klarna settings](https://vertis.d.pr/YkKk9K) set the following credentials for "API Credentials Europe":
username: PK55887_87674d4be58e
password: MWEe5XuMPmSe6tTa
3. There are multiple settings to do to make sure Klarna will work:
- Make sure you have the privacy policy page set in WooCommerce
- Make sure the currency is AUD, CAD, CHF, DKK, EUR, GBP, NOK, SEK, or USD
- Configure Klarna like this: …

Fix Klarna compatibility issue

---

assets/scss/components/compat/woocommerce/_cart.scss
assets/scss/components/compat/woocommerce/_nav-cart.scss

I did some debugging here, and this is what I found:
Elementor PRO overrides the mini cart template from WooCoommerce. According to [their article](https://developers.elementor.com/elementor-pro-2-7-new-approach-to-woocommerce-mini-cart/), you can enable or disable the usage of that template by going to Dashboard > Elementor > Settings > Integrations tab > WooCommerce section and choose Enable or Disable.
- If the template is enabled and you condition the header with a mini cart made in Elementor to appear only on the shop page, when you're not on the shop page you'll see the mini cart affected. It will look like this and there's nothing we can do about it:
On the other hand, the mini cart on the shop page will look like this: 
- If the template is not enabled the mini cart will look …

fix: mini cart issues with Elementor [Codeinwp/neve-pro-addon#1863]

---

inc/compatibility/woocommerce.php

Solves the div opening and closing on a single product for the new skin.
This was a regression introduced by the fact that the divs were not closing in the correct order on the new skin.
YES
1. Import a WooCommerce starter-site
2. Enable the Performance module from PRO
3. The layout should not be affected
Closes Codeinwp/neve-pro-addon#1937.

fix: solves performance module display for related 

---

inc/views/template_parts.php

- Add margin-top of 60px for featured post
YES
- Enable featured post
- Test when homepage is latest posts or static page
- When testing the static page, enable / disable the title from neve page meta
- 
Closes #3442.

Fix featured post margin

---

assets/scss/components/elements/_form-elements.scss

Fixed the styles for the search widget prior to 5.8 on the new skin.
YES
1. You will need a version of WP under 5.8 I would recommend 5.7.2
2. Create a search widget inside the footer area
3. Increase the row size to 300
4. The search widget should display correctly.
The changes here will also fix widgets that have been ported from 5.7 to the new widget area from 5.8 onwards.
Closes #3265.

fix: legacy search widget display on new skin

---

assets/scss/components/elements/navigation/_nav-menu.scss

These styles seem to have not been added when we moved to new skin, they exist in old skin: https://github.com/Codeinwp/neve/blob/v3.2.3/assets/scss/elements/navigation/_nav-menu.scss#L217-L220
NO
- Create a menu item with sub items
- Test mobile menu on mobile
- Test mobile menu on desktop 
Closes https://github.com/Codeinwp/neve/issues/3404

chore: add padding for submenu items in sidebar menu

---

assets/js/src/customizer-preview/app.js
inc/compatibility/woocommerce.php
inc/customizer/defaults/layout.php
inc/customizer/loader.php
inc/views/layouts/layout_sidebar.php
inc/views/pluggable/metabox_settings.php

Prevent shop sidebar to hide when content is >= 95% and the sidebar is off-canvas
While working on this, I noticed that if shop sidebar was set in customizer as off-canvas and on single shop page you choose right sidebar, the specific setting is not applying. This PR is a fix for that too.
NO
- Import a startersite with WooCommerce
- Edit the shop page and Reset all options to default
- In Customizer change the shop sidebar to off-canvas
- Change the width to 95 or higher
- See if the sidebar is showing and if the toggle that opens the sidebar is working
- Test if everything is ok with other sidebar positions
- Test if the sidebar settings on the single page options overwrite the one from customizer
Closes Codeinwp/neve-pro-addon#1951.

Fix shop sidebar offcanvas

---

assets/scss/components/elements/_form-elements.scss
header-footer-grid/Core/Builder/Footer.php

Made selectors for legacy smaller so as to keep the size of the bundle under the limit.
NO
1. Use the same steps as described here: https://github.com/Codeinwp/neve/pull/3451#issue-1220926380
2. Check that it works with legacy and for the new component the height is adjusted accordingly.
Closes #3265.

fix: smaller selectors for scss

---

assets/apps/dashboard/src/Components/LicenseCard.js
assets/apps/dashboard/src/scss/components/_sidebar.scss
inc/admin/dashboard/main.php

Fix position of external link icon
NO
- Installing this patch should fix the position issue for the external link icon: https://vertis.d.pr/YSXccp
Closes https://github.com/Codeinwp/neve-pro-addon/issues/1957

chore: align external icon for purchase history link

---

assets/scss/components/elements/_sidebar.scss
inc/compatibility/woocommerce.php
inc/customizer/defaults/layout.php
inc/views/layouts/layout_sidebar.php
inc/views/pluggable/metabox_settings.php

- Fix sidebar toggle on mobile
NO
- Import a starter site with WooCommerce
- Edit the shop page and Reset all options to default
- In Customizer change the shop sidebar to off-canvas
- Change the width to 95 or higher
- See if the sidebar is showing and if the toggle that opens the sidebar is working
- Test if everything is ok with other sidebar positions
- Test if the sidebar settings on the single page options overwrite the one from customizer
- Make sure the toggle for sidebar ( in left, right, or off-canvas position ) on mobile does not disappear
- 
Closes #3465.

Fix sidebar toggle

---

header-footer-grid/Core/Magic_Tags.php

Adds `{current_query_title}` magic tag which gets the current title of the page being viewed.
NO
- Add the `{current_query_title}` magic tag to a HTML component anywhere in neve header or footer builder and save changes.
- The magic tag should output the currently viewed page's(or post, or archive) name 
Closes Codeinwp/neve-pro-addon#1586

chore: add current query title magic tag

---

.github/workflows/diff-translations.yml

Later today the default branch for the  [Automattic/action-required-review](https://github.com/Automattic/action-required-review) repository will change from `master` to `trunk`. This file references the `master` version, which will result in issues after the branch rename.
I'd recommend changing that to a tagged version (v2 in this case).
No.
- Translations diff tests should pass, particularly when using the required review action where appropriate.

GitHub Actions: Updating action-required-review tag

---

.github/workflows/diff-translations.yml
assets/js/src/frontend/navigation.js
e2e-tests/cypress/integration/customizer/hfg/hfg-menu-item-alignment.spec.ts
e2e-tests/cypress/integration/mega-menu/mega-menu-test.spec.ts
e2e-tests/cypress/support/commands.ts
header-footer-grid/Core/Magic_Tags.php
inc/views/nav_walker.php

Changed dropdown links to use the button tag.
Merged changes from #3339
Cleaned up CSS to not trigger the size limit
Removed tab open for dropdown only opens on the `Enter` key or click
NO
1. Check that the navigation looks the same as before
2. Check that the dropdown caret is now a button tag
3. Check that can be opened on the `Enter` key or  click
4. Check the same for Mega Menu
Closes #3258.

fix: changed menu dropdown link to button

---

inc/views/partials/post_meta.php

When changing the meta, I applied the wp_kses_post over the time tag and it will be stripped leaving it without classes.
NO
- Enable the date in Post Meta
- Check the blog and single layout pages
- Toggle this option - https://vertis.d.pr/PgKwQt
Closes #3503.

Fix meta two dates

---

header-footer-grid/Core/Magic_Tags.php

wp_title needed false for the display parameter
NO
- Add "Youe are viewing {current_query_title} page" in a HTML component in header
- Check the frontend
Closes #3504.

fix: magic tag can't be displayed inline with other text [#3504]

---

inc/views/page_header.php

The title was missing from pages when featured posts were enabled
NO
- Enable the featured post in the customizer
- Check and see that the pages are still displaying the title.
Note: Make sure you reset the meta option from the Neve page edit sidebar. Some of the pages you import are disabling the actual page title and are adding it to the page content.
Closes #3491

Missing title on page

---

assets/apps/metabox/src/components/MetaFieldsManager.js
inc/views/pluggable/metabox_settings.php

Use default style width when the container is not defined on new posts.
YES
1. Go into the editor (either create a new page, or post);
2. Open up the Neve sidebar; 
3. The content width should be the same as for the frontend one;
4. If you click the "Default" option for the container, everything should remain the same. Previously it would update.
Closes #3522.

fix: solve default for container width

---

assets/apps/customizer-controls/src/repeater/RepeaterItemContent.js

Added default value if no option is selected to trigger the change event on repeater select control.
NO
1. Install ACF and create a field group -> field.
2. Populate it for a particular post.
3. Go to Appearance > Customize > Layout > Single Post > Post Meta.
4. Add a new item there and click on ACF.
5. Select the field that was populated before and check if it appears.
Closes #3519.

fix: acf field select not triggering update

---

header-footer-grid/Core/Components/SecondNav.php

Adds active menu item color for the secondary navigation header component.
NO
- The secondary navigation component should have an active item color control; 
- The color should show up fine in the front end;
Closes #3426.

Active menu item color to secondary nav component

---

header-footer-grid/Core/Customizer.php

Don't register the Documentation Section if the Whitelabel feature is used.
NO
1. Check inside Customizer that the Documentation Section is loaded only if Whitelabel is not active or not configured.
Closes Codeinwp/neve-pro-addon#2046.

fix: hide doc section when whitelabel is active

---

assets/scss/gutenberg-editor-style.scss
theme.json

Adds the `theme.json` file, thus enabling additional features inside the editor mentioned in the issue (#3485).
More on what gets enabled using this flag [🔗 here](https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-json/#opt-in-into-ui-controls).
NO
- Add a group block inside the editor;
- It should now have the options mentioned inside the issue;
- Other blocks get new options as well, so we might need to test for compatibility with Otter and anything that might be out of order with core blocks; 
Closes #3485.

feat: adds theme.json & enable "appearanceTools"

---

inc/views/partials/comments.php

Fixed how the comment replies tag close.
NO
1. Add 2 Comments on a Post
2. Reply to the First Comment
3. Reply to the Reply of the First Comment
4. Check that the indentation is preserved for replies and that the second Comment is not shown as a reply.
Closes #3546.

fix: nested replies closing tags

---

assets/scss/components/hfg/frontend/layout/_footer.scss
header-footer-grid/assets/scss/frontend/layout/_footer.scss

Changed the `z-index` for the footer, when sticky it would not display over some elements.
YES
1. Enable the sticky footer row
2. Enable the wishlist icon for products, and the sale label
3. Scroll the page on the shop and single product pages - on the product page it happens with the related/exclusive products
4. Check no items or badges are displayed over the footer.
Closes Codeinwp/neve-pro-addon#2092.

fix: sticky footer z-index Codeinwp/neve-pro-addon#2092

---

inc/compatibility/easy_digital_downloads.php

Updated the filter for newer versions of `EDD >= 3.0.0`
NO
1. Import the NFT starter site (it contains the EDD plugin)
2. Check the dashboard, no error or warning should be displayed
Closes #3542.

fix: deprecated edd filter

---

inc/core/front_end.php
inc/views/post_layout.php

- Change the way we check if we add comments script or not
In order to load comment-reply script we are checking:
1. If comments are enabled
2. If current page is single ( post / page / cpt )
3. If thread comments are enabled ( https://vertis.d.pr/mCPDSn )
4. If post is password protected
5. For posts and CPT we check that the comments are enabled in customizer
6. If current post type supports comments
NO
- Try each condition above and make each one to return false. Then, check if the script appears in your page:
Closes #3549.

Fix comment reply script loading

---

header-footer-grid/functions-template.php
header-footer-grid/templates/row-wrapper-mobile.php

- Fixes the error thrown if you have an empty header.
NO
- On a clean instance of a local environment ( not tastewp ) install just neve free.
- Go in customizer and apply the starter content
- Save customizer and refresh
- Empty the header both on mobile and desktop and hit publish
- Exit the customizer and see the frontpage. Without this fix you should see an error.
- Try the previous steps for footer too and make sure the issue doesn't happen there as well
Closes #3557.

fix: critical error when header is empty [#3557]

---

globals/migrations.php

Fixed the migration defaults on the first install publish for header buttons.
YES
1. Install Neve free on a clean instance 
2. Enter the customizer and hit publish to apply the starter content
3. Exit the customizer and see the button in the header
Closes #3560.

fix: solve migration button defaults missmatch #3560

---

globals/migrations.php
header-footer-grid/Core/Components/Button.php
inc/core/styles/css_prop.php

Fix `border-radius` with 0 values not being respected on buttons.
Fix default appearance on a new import for header buttons and fix regression
YES
1. Test on a fresh instance of Neve
2. Check that the default Header Button displays the same in Customizer and on the Frontend
3. Check that the Woo button displays as before
4. Check that the `border-radius` can now have 0 values
Closes #3565.
Closes #3570.

fix: button border default and default import #3565 #3570

---

page.php

Changed the sent context if page was checkout or cart.
NO
Same as https://github.com/Codeinwp/neve-pro-addon/pull/2101
Closes Codeinwp/neve-pro-addon#2101.

Blog sidebar affecting shop sidebar

---

assets/scss/components/elements/navigation/_nav-toggle.scss
header-footer-grid/Core/Components/Abstract_Component.php
header-footer-grid/Core/Components/MenuIcon.php

- Adds a new margin control for the Menu Icon component 
NO
- See if the control applies properly in the customizer and on the front end
Closes  Codeinwp/neve-pro-addon#2095.

Add margin control for menu label

---

assets/apps/customizer-controls/src/builder-instructions/Instructions.tsx

Removed extra divider if no description is provided.
NO
1. Go into Customizer > Typography
2. Check that there is only one divider at the top.
3. Check that on Customizer > Footer, where a description is provided there is a divider before and after the description of the section.
Closes #3580.

fix: solve extra divider when no description #3580

---

inc/views/nav_walker.php

Added ARIA label to caret figure and changed role for div on desktop.
NO
1. Check that on the desktop there is an ARIA label for the dropdown caret.
2. Check that with screen readers there is no problem with the tab navigation and spoken text.
Closes #3582.

chore: add aria label to caret figure #3582

---

assets/js/src/shop/app.js

**The changes contains:**
1.  Fix for the https://github.com/Codeinwp/neve/issues/3591 issue
2. Fix for the: https://github.com/Codeinwp/sparks-for-woocommerce/pull/134#issuecomment-1229888627 issue(second TODO in the comment that added by @irinelenache )
-- The https://github.com/Codeinwp/neve/commit/df70e7f3c0ec7670f3f30c62b5480ba7b1e0a771 commit is responsible for the fix. I'll make performance improvements and move some code to the Neve Pro side probably.
**! Note: This PR(https://github.com/Codeinwp/neve/pull/3592) is relative to https://github.com/Codeinwp/sparks-for-woocommerce/pull/134**
YES
- Activate stable Neve Pro
- Activate Sparks from [this](https://github.com/Codeinwp/sparks-for-woocommerce/pull/134) PR.
- Activate Sparks Variation Swatches and make sure catalog attributes …

Fix for two issue related between Exclusive Products section and Sparks Variation Swatches

---

header-footer-grid/Core/Components/Search.php
inc/core/settings/config.php

Exclude button submit from secondary button style
NO
- Import the Photography starter site and add the search component in the header 
- Check if secondary button settings are still applying
Closes #3586.

fix: secondary button options applying on search submit button

---

comments.php

Before this PR; if "allow comments" is unchecked in Post Settings->Discussion part (https://vertis.d.pr/y58XyU); comments and reply form were hidden.
With this PR; I've changed the behavior on there. From now on, if comments disabled; only reply form is hidden but comments are visible.
YES
**If "allow comments" is deactivated:**
before: https://vertis.d.pr/ctJa1U
after: https://vertis.d.pr/nWf5d7
- Visit a single post and submit some comments
- Go post edit screen, play with the "Allow comments" checkbox. If it's disabled, the post should be closed for the new comments but old comments still should be visible. If its state is checked; old comments & the reply form should be visible together.
Closes #3459 .

Show comments but hide reply form if "allow comments" settings is unchecked

---

assets/apps/customizer-controls/src/controls.js
assets/apps/customizer-controls/src/customizer-search/MainSearch.tsx
assets/apps/customizer-controls/src/customizer-search/SearchComponent.tsx
assets/apps/customizer-controls/src/customizer-search/SearchResults.tsx
assets/apps/customizer-controls/src/customizer-search/SearchToggle.tsx
assets/apps/customizer-controls/src/scss/_customizer-search.scss
assets/apps/customizer-controls/src/style.scss

Added a new component for the Customizer that allows the user to search through all Customizer sections and panels.
YES
Demo:
https://vertis.d.pr/zXX7gg
Preview:
1. Go into Customizer
2. Toggle the search feature on the main page:
3. Check the search results and the navigation
Closes Codeinwp/neve-pro-addon#1438.

feat: Customizer Search component for Settings

---

assets/apps/components/src/Controls/RadioImage.js
header-footer-grid/Core/Components/Search.php
inc/core/settings/config.php

Added the active class also to the wrapper to allow the design for custom layout pop-up select.
YES
1. Check that the RadioImage options in Neve don't change design wise
2. No regression was introduced
References Codeinwp/neve-pro-addon#2045.

chore: added active class to wrapper to allow cl popup design

---

assets/scss/components/elements/navigation/_nav-menu.scss
header-footer-grid/Core/Components/Nav.php
header-footer-grid/templates/components/component-nav.php

- Changed the behavior of this feature. Until now, the first level was expanded but you couldn't toggle it after, altho the submenu icons were clickable.
- Right now, if this option is enabled, the first level of submenus will be expanded by default but you will be able to retract them after.
- I chose this solution because it removes some additional CSS and justifies the presence of the submenu toggles.
NO
- On mobile, enable the "Expand the first level of dropdowns when the menu is in mobile menu content." option
- Check on desktop and make sure the submenus are not expanded
- Check on mobile, the first level of submenus should be expanded and you should be able to retract them
Closes #3583.

Expand first level of submenu fix

---

assets/apps/customizer-controls/src/responsive-range/ResponsiveRangeComponent.js

The browser console errors related relative CSS unit support (only happens with previous Neve Pro versions) that we've added in v3.4 has been fixed with the following way:
* I've added fallback CSS unit suffix for default control values in Responsive Range Slider component.
NO
- All relative units (whatever Neve Pro is activated or not) still should work well
- No regression on entire of the customizer controls (saved values are preserved, default values still works well.)
- No browser error when customizer is opened (whatever Neve Pro is activated or not)
Closes #3614 .

fix: check if the defaultVal has the suffix prop or not

---

inc/compatibility/starter-content/home.php

Changed the starter's content hero image block with the new markup
NO
- On a fresh Neve instance install the Gutenberg plugin
- Open the customizer and check the hero image on a large screen
Closes #3623.

fix: hero image on starter content

---

assets/apps/components/src/Common/svg.js
package.json
yarn.lock

Fix upside down carets on Safari. Please check with neve pro PR and after without neve pro, just neve
NO
Closes Codeinwp/neve-pro-addon#2166.

fix: upside down carets on safari

---

assets/apps/customizer-controls/src/customizer-search/SearchComponent.tsx

Added clear field and results on customizer search if a section transition or panel transition is triggered.
Previously if a transition was triggered, eg. the edit button, the results would remain listed hiding the section or panel.
NO
1. Search for something using the Customizer Search
2. Instead of clicking on the result, click on the edit button from the Customizer Preview
3. Check that the results are hidden and the section is displayed correctly.
Closes #3627.

fix: hook into expand panel or section to clear search

---

header-footer-grid/Core/Builder/Abstract_Builder.php
header-footer-grid/Core/Builder/Header.php
header-footer-grid/Core/Components/Abstract_Component.php
header-footer-grid/Core/Components/Nav.php
header-footer-grid/Main.php
header-footer-grid/templates/component-wrapper.php
header-footer-grid/templates/components/component-nav.php
inc/views/nav_walker.php

Fixing the "Expand first level of dropdowns when menu is in mobile menu content." setting brakes the menus on legacy skin. This PR should fix the problem.
NO
- On a fresh instance, install Neve 2.9, apply the starter content and add a new item to the header.
- Update to the latest version, migrate the HFG
- Switch to the legacy skin
- Enable the "Expand first level of dropdowns when menu is in mobile menu content." 
- Check and see if submenus are expanded.
- Check and see if the option still works on mobile
- Check if "Expand first level of dropdowns when menu is in mobile menu content." option applies only to current instance
Closes #3619.

fix: expanded submenus on old skin

---

assets/apps/customizer-controls/src/builder/HFGBuilderComponent.tsx

Improved the toggle for the page header.
Previously it would only mount on Global Page Header Settings.
NO
1. Go to Customizer > Page Header > Page Header Top or Page Header Bottom
2. Check that the builder opens
3. Check the builder opens as before for the Header section
Closes Codeinwp/neve-pro-addon#2173.

fix: toggle of page header on rows

---

assets/scss/components/main/_extends.scss
assets/scss/lifter.scss

- The dropdown icon for select inputs was missing because we applied the background color through `background` property. Changing it to `background-color` fixes the issue
NO
- Create a form with a select input, not necessarily Gravity forms
- Set a color in customizer in Form Fields section
- Check the form on frontend
Closes #3635.

Caret for select dropdown not appearing

---

assets/scss/components/elements/form-elements/_inputs.scss
assets/scss/components/main/_extends.scss
assets/scss/lifter.scss

- reverted the changes previously made and found a way to have the caret for select inputs and also keep the gradient
NO
- See if the reported problem was fixed
- Check and make sure the gradient for inputs is still working
Closes #3635.

fix: missing caret of form select with background color

---

assets/scss/components/compat/woocommerce/_breadcrumbs.scss
assets/scss/components/compat/woocommerce/_media-queries.scss
assets/scss/woocommerce.scss

Adjusted the breadcrumbs and the text for the results display on mobile for WooCommerce.
YES
1. Check that on WooCommerce templates on mobile the Breadcrumbs and Product Results text are being displayed correctly without getting squashed together.
Closes #3621.

fix: breadcrumbs and results in woo display on mobile #3621

---

assets/apps/metabox/src/editor.scss

- Fixed the way the meta sidebar looks on wp 61
NO
Closes #3640.

fix: meta sidebar styling for wp6.1 [#3640]

---

inc/views/nav_walker.php

I cannot replicate the main issue. By the looks of it, the client either has a child theme and overwrites files from the theme or did some modifications inside the theme files.
I've added a supplementary check for it as it does no harm but the problem shouldn't appear.
NO
- Install neve and add a menu
- In the theme's files, go and comment this line https://github.com/Codeinwp/neve/blob/master/header-footer-grid/templates/components/component-nav.php#L38
- With or without that line commented, there should be no error on frontend
Closes #3660.

Add another check for component id

---

globals/utilities.php
inc/customizer/defaults/layout.php
inc/customizer/options/layout_blog.php
inc/customizer/options/layout_single_post.php
inc/views/partials/post_meta.php
inc/views/post_layout.php
inc/views/template_parts.php

This PR fixes the two errors described in the issue thread.
- I've taken that method and made another one global with the same functionality;
- I kept the previous method to avoid any compatibility issues with the pro version ( since the method is used in pro ) but I've added the deprecated tag
- For the second issue, I've replaced the alt attribute with the display name since the `get_the_author` function produces the notice
NO
- Install PHP8.1
- Import the  data from https://wpcom-themes.svn.automattic.com/demo/theme-unit-test-data.xml
- Check the blog for any related issues with Neve
- Make sure there aren't any issues with neve old / neve pro new, neve new/ neve pro old. For neve new test with this PR https://github.com/Codeinwp/neve-pro-addon/pull/2226
Closes #3662.

fix: call to static method in trait #3662

---

composer.lock

Updated the webfont loader composer dependency. This should fix the issue.
NO
1. Enable the Typekit module in the Neve dashboard, you can use this project ID: `xcw3ype`
2. Enable local font loading from the performance module
3. Select a Typekit font in the customizer.
4. In DevTools from Chrome, check and see how the selected font is loading.
Closes Codeinwp/neve-pro-addon#2228.

fix: update webfont loader [Codeinwp/neve-pro-addon#2228]

---

assets/customizer/css/heading.css

Updated the CSS so it will work for both type of Heading controls, the template one and the react one
NO
- Check the H1 - H6 headings in typography panel
- Install Neve Pro and check if the dropdown works for headings in the primary menu component
Closes Codeinwp/neve-pro-addon#2221.

Dropdown arrow for customizer headings

---

assets/apps/customizer-controls/src/scss/_controls-layout.scss

Fix the style for toggle controls in WP 6.1. Seems they've added a `min-width: 0` on `components-base-control__field` class and a margin-bottom on `components-toggle-control`
NO
- Upgrade to WP 6.1 ( I tried RC5 )
- Check customizer controls
Closes #3643.

fix: toggle style

---

woocommerce/product-searchform.php

Update the template version so Woocommerce doesn't throw an error
NO
- Update to this version and check the Woocommerce status page in the dashboard
- If you want to test the template, the code will execute only with Gutenberg disabled. After you disable Gutenberg, make sure you add the Product search widget inside the sidebar.
Closes #3677

Update template version for Woocommerce

---

assets/scss/components/editor/_typography.scss
inc/views/font_manager.php

Enqueue google fonts for editor preview (iFrame).
NO
https://vertis.d.pr/v/Q7SV8g
1. Have a Google Font defined in General
2. Check inside the Gutenberg Editor on the Preview (Mobile Tablet) that the font is being loaded and displayed.
Closes #3654.

fix: enqueue google fonts on editor preview #3654

---

assets/apps/components/src/Controls/ColorControl.js
assets/apps/components/src/Style/_gradient-component.scss

Added a min with to keep the gradient picker from collapsing in WP6.1
YES
1. Check the gradient color picker inside Customizer with WP6.1
2. Check that it maintains the proper width
Closes #3689.

fix: gradient picker size for wp6.1

---

functions.php
inc/admin/dashboard/plugin_helper.php

- Defined a variable in `functions.php` pointing to the plugins directory
- Tested on both Bedrock and WordPress and everything seems to be fine.
NO
- Test if the plugins install/activate/deactivate from the dashboard are still working fine.
- Test if TPC is installing.
- Check if the import works correctly.
- To test the Bedrock side, you'll need to install https://github.com/roots/bedrock/ on your local environment. Please ping me if you need help with the installation.
- Test the first three steps mentioned above.
Closes #3690.

Fix plugin path issues with bedrock

---

inc/compatibility/elementor.php

The error occurs whenever the `get_documents_for_location` function was called. It wasn't necessary to call it since we could call the `get_location_templates`, a function that is used by `get_documents_for_location`.
NO
- Follow the steps from the issue's body
- Since this is a regression, please test https://github.com/Codeinwp/neve-pro-addon/issues/2116 again
Closes Codeinwp/neve-pro-addon#2277.

fix: elementor header disappears

---

assets/js/src/frontend/hgf.js
assets/js/src/frontend/navigation.js
assets/scss/components/elements/_mega-menu.scss
assets/scss/components/elements/navigation/_nav-menu.scss
assets/scss/components/elements/navigation/_nav-styles.scss
assets/scss/components/hfg/frontend/layout/_mobile_sidebar.scss
assets/scss/elements/_mega-menu.scss
composer.json
inc/views/nav_walker.php

This PR will revert accessibility changes and should revert the menu functionality to how it worked prior to the 3.4.8 release.
Rollback changes from https://github.com/Codeinwp/neve/pull/3696
Works with changes for pro from here: https://github.com/Codeinwp/neve-pro-addon/pull/2291
Will reopen:
https://github.com/Codeinwp/neve/issues/2935.
https://github.com/Codeinwp/neve/issues/3731.
YES/NO
- 
- 
Closes #3750.
Closes #3752.

chore: rollback menu changes

---

inc/customizer/defaults/layout.php

```
File: inc/customizer/defaults/layout.php
87: 
88: 		$body_classes = apply_filters( 'body_class', [] );
```
https://developer.wordpress.org/reference/hooks/body_class/
The `body_class` created in neve theme is made similar to the WP `body_class` hook. The `body_class` hook in neve theme has only 1 parameter passed which is different from the WP `body_class` where two parameters are used. This has resulted in a fatal error where third-party plugins and themes relied on `body_class` with two parameters.
YES/NO
-  Use the `body_class` hook with two parameters in `functions.php` for now, which should result in a fatal error.
- 
Closes #.

fix: make body_class hook signature similar to WP's

---

.github/workflows/playwright.yml
bin/envs/sample-data/start.sh
e2e-tests/specs/tpc/tpc-notice-install.spec.ts
inc/admin/dashboard/plugin_helper.php
inc/core/admin.php
tests/php/static-analysis-stubs/config.php

Fixes one click install not working anymore.
The plugin state was active even if the plugin was not present in environments where files use symbolic links.
I think this was introduced by the changes here: https://github.com/Codeinwp/neve/pull/3693
I took the liberty to use `WP_PLUGIN_DIR` constant witch seam to work more consistent inside Beadrock and also on other environments.
I've also tweaked the button behavior as it had a conflict with other JS actions that were closing the notice to early.
ToDo:
+ [x] Add playwright tests
(For the playwright tests to work I had to install TPC via wp-cli as permissions did not allow for folder creation.)
NO
You can use:
```sh
wp option update neve_notice_dismissed no && wp plugin deactivate templates-patterns-collection && wp plugin delete …
```

fix: solves one click install

---

assets/apps/components/src/Style/_gradient-component.scss

Fixes the mega menu style settings not appearing
NO
- Bogdan was adding some style to fix a bug introduced by WP core 6.1. I removed that style since the issue seemed to be fixed. Please make sure that this fix doesn't break anything that was fixed before https://github.com/Codeinwp/neve-pro-addon/issues/2286#issuecomment-1369932584
- Check if the styles popups are appearing and working for the Mega menu ( see the issue's body )
Closes Codeinwp/neve-pro-addon#2286.

fix: popup for colors in mega menu not appearing [#2286]

---

inc/admin/dashboard/plugin_helper.php

Updated the plugin path since for wp-cloudflare-page-cache it's not the expected pattern `$slug / $slug.php`
/NO
- Go to Neve dashboard, plugins tab and install cloudflare supercache
Closes #3769.

fix: cloudflare supecache install [#3769]

---

.github/workflows/diff-translations.yml
bin/makepot.sh
languages/README.md
package.json

Runs the POT generation and POT diff on JS build files instead of using the source files, mirroring wp.org behavior.
NO
Closes #3774

chore: run potfile generation on build files instead of source

---

inc/views/template_parts.php

Added an additional check to not display featured post on other pages than the first one of the blog post when using pagination.
When pagination is used the featured post should display only on the first page.
YES
1. Enable featured post
2. Have enough posts to have pagination, and use the numbered pagination.
3. Check that the featured post is only visible on the first page.
Closes #3779.

fix: display featured post only on first page #3779

---

assets/apps/components/src/Style/_gradient-component.scss

Enforced the `max-height` for that container so that it does not produce the same visual defect.
Changed back the properties that were removed here: https://github.com/Codeinwp/neve-pro-addon/issues/2286
cc: @cristian-ungureanu did it work correctly inside Customizer for the gradient picker?
Better scoped the gradient style to apply only under Customizer controls so as to not apply to Mega Menu or other usages.
YES
MM Color picker:
Customizer Color Picker small screen:
Customizer Color Picker small screen and Gradient popover:
Customizer:
1. Test the color picker with a screen height of < 800
2. Check that for Gradient Colors ( E.g. Buttons background ) the gradient selector does not completely block the parent pop-over
3. Check that inside MM the color picker opens as expected.
Closes …

fix: color picker issue on small screens

---

inc/views/layouts/layout_sidebar.php

The issue was that we added the `neve_sidebar_setup_filter` before returning the defaults if the **Enable Advanced Options** was disabled.
The Custom Post Types module uses the filter to add the required theme mods if the feature is enabled. However, by invoking it here, we short-circuited the check and made the toggle redundant. This would introduce a regression and would not return the expected defaults.
In order to maintain the functionality of the new sidebar module and not change existing logic and behavior I've added a new filter `neve_before_returning_sidebar_setup` that we can use to alter the sidebar data before returning from the `get_sidebar_setup()` function.
This has changes in PRO for the Sidebar Module to hook as before using the new filter.
Link: 
NO
1. Check that it …

fix: sidebar logic change Codeinwp/neve-pro-addon#2335

---

functions.php

- Change the tested up-to version of Neve Pro
NO
- Update Neve and Neve Pro
- Check if the message is still displayed
- Check if this version works with Neve Pro 2.1 ( min required version ) ( eg: there are no fatal errors that break the website )
~ 2 minutes
Closes Codeinwp/neve-pro-addon#2343.

Update tested up to Neve Pro version

---

inc/views/partials/post_meta.php

For this task I had 2 options:
- Make the function global and wrap it in `if ( ! function_exists() )` to make it pluggable
- Add a filter over the result of this function
I choose to add a filter since this function could be used in other products. So, in order for our user to edit it, he could add the following code inside a child-theme:
```php
function neve_get_author_meta( $markup, $post_id, $show_before ) {
global $post;
if ( ! function_exists( 'coauthors_posts_links' ) ) {
return $markup;
}
$link = coauthors_posts_links( $between = null, $betweenLast = null, $before = null, $after = null, $echo = false);
$link = apply_filters( 'the_author_posts_link', $link );
return wp_kses_post( $link ) . '';
}
add_filter( 'neve_filter_author_meta_markup', 'neve_get_author_meta', 10, 3 );
```
Note …

Add filter for the author post meta

---

inc/compatibility/elementor.php
inc/compatibility/woocommerce.php
inc/core/front_end.php

Prevent any modification for WooCommerce if the current page is the checkout one and the page is edited with Elementor and it has the Checkout widget on it
NO
- Check if the issue described **[here](https://github.com/Codeinwp/neve/issues/3610)** is fixed 
- Should be tested with https://github.com/Codeinwp/neve-pro-addon/pull/2308
Closes #3610.

fix: elementor checkout [#3610]

---

inc/core/styles/css_prop.php

* Maintain support for a deprecated pattern (usage 'self' in callable argument) with PHP 8.2
ref: https://php.watch/versions/8.2/partially-supported-callable-deprecation#deprecated-patterns
NO
- Make sure there is no PHP warning/error on PHP 8.2 on Neve Pro + Neve or only Neve
~ 1h 5min
Closes #3595 .

PHP 8.2 Support

---

assets/scss/components/elements/blog/_blogpost-covers.scss

Added a display flex property on the parent of the inner class so the inner class can be aligned vertically.
NO
- Switch to cover layout
- Check if all controls from the customizer still work
- Try to add a featured post and see if it works properly
24 min
Closes Codeinwp/neve-pro-addon#2354.

Vertical align for cover posts

---

assets/apps/components/src/Controls/ButtonAppearance.js
assets/apps/components/src/Style/_button-appearance.scss

- The control was missing the padding because we previously added [this CSS ](https://github.com/Codeinwp/neve/blob/master/assets/apps/components/src/Style/_button-appearance.scss#L17-L19)
- We added that CSS to fix another issue: https://vertis.d.pr/i/ejZGVj, but we didn't take into consideration when the style is not set on filled or outlined. This PR should fix both cases.
NO
- Go to customizer, add a button inside the header
- Edit that button and check the appearance control inside the style tab
- Check the Primary / Secondary button controls from Customizer -> Buttons
26 min
Closes #3809.

Missing padding for button appearance control

---

inc/views/pluggable/pagination.php

Fix the issue with infinite scroll when Polylang is active. The problem was that `$args` came with a parameter named "pagename." This parameter makes WP_Query return an empty string.
NO
- Install Polylang
- Add two languages
- Add posts and translations for those posts
- Enable infinite scroll in the customizer
- Test the following steps for the "Your homepage displays" customizer option set both as " Your latest posts" and "A static page."
- Check that infinite scroll works in both languages.
- Check that infinite scroll works on the search page.
~ 1h 20min
Closes #3803.

fix: polylang infinite scroll [#3803]

---

.github/workflows/deploy.yml

It uses this custom GH Action forked out of 10up's Plugin Deployment: https://github.com/marketplace/actions/wordpress-theme-deploy - you can check the code to make sure I'm not missing anything that Neve needs.
For testing, I used forked out [Neve](https://github.com/HardeepAsrani/theme-directory) and added this to deployment with the build process involved: https://github.com/HardeepAsrani/theme-directory/blob/primary/.github/workflows/deploy.yml
And here are the deployed results: https://svn.riouxsvn.com/theme-directory/1.2/
We can perhaps also test it with a FSE theme before employing it to be used with a major theme? Let me know your thoughts.
closes #3793

Add WPorg Deployment

---

composer.json
composer.lock
phpstan.neon

In this PR I changed webfont-loader to point to my fork where I fixed the issue.
The issue was that when downloading a font with multiple font weights from Typekit, the file name was the same resulting in one font weight overwriting another's file.
NO
Please have a look over this PR: https://github.com/WPTT/webfont-loader/pull/21
- Use the following Typekit project Id to replicate the issue and see if it's fixed: set1ymb
- Enable local loading of fonts.
- Choose Sofia-pro for the body font.
- Check on the front end if the issue is the same as in the customizer.
- After you test with that project id, you can do another round of tests with this one: vds6kqq, since it adds more options.
- Please also test if Google fonts loading locally are affected in any way.
~ 4h 30min
Closes …

Typekit fonts when loading them locally

---

inc/customizer/options/layout_blog.php

The sanitization function was changed to hide the toggle if the Image Position control was set to "No image". While this worked well in Neve Pro, in Neve, the control just disappeared.
NO
- Just with Neve free installed, no PRO, check the customizer -> layout -> blog /archive panel. You should see the toggle there
- Activate Neve Pro and check the presence of the control again
- Switch to Image Position => "No Image"
- Check if the toggle disappears. The condition for the toggle to be present are list layout + image position not "no image"
21 min
Closes #3831.

Alternating layout control is missing

---

assets/scss/components/elements/navigation/_nav-menu.scss

This is a regression caused by 3.5.2 update. The elements had "display: flex" and "align-items: center" before, I'm not sure why we removed them. 
NO
- Go to the customizer and add a primary menu.
- Inside the Layout tab, add a min-height for elements, let's say 100
- For that primary menu location, set a menu. When you create the menu, make sure you add child items.
- Check how the menu looks on the frontend
- Please check that no other issues appear in the mega menu
45min
Closes #3832.

Menu item not aligned with caret

---

assets/scss/components/elements/blog/_comments.scss

Added proper padding-left for comments.
It appears this was actually a regression since Neve 3.0.
YES
Before Neve 3: https://vertis.d.pr/i/8ck7Wq
After Neve 3 ( 3.1 ): https://vertis.d.pr/i/lcIPW2
In this PR: https://vertis.d.pr/i/7yvSkd
- Add a comment
- Reply to that comment
- Reply to the previous reply and check the indentation
2h 35min
Closes #3798.

Comment indentation

---

header-footer-grid/Core/Magic_Tags.php

- Properly replace magic tag in this format: `https://{magic_tag}` and `http://{magic_tag}`, no matter the magic tag.
NO
- Install WC, Neve, Neve Pro
- Create a sample product
- Create a custom layout and choose a rule to restrict it with product post_type
- Try to use {cart_link} magic link in the editor, you'll see it works as a text etc.
- Try to add {cart_link} for link of the Button or Button Groups blocks, you'll see on the frontend;
- Try to use it like "Link Option" https://vertis.d.pr/i/oWfjBe
- Try and see if other magic tags that return URLs like `{current_single_url}` are still working fine 
1h
Closes Codeinwp/neve-pro-addon#2266.

Cart-link magic tag not working correctly

---

assets/scss/components/elements/_content.scss
assets/scss/components/elements/blog/_single.scss

- Added a margin-bottom for the image block. This margin would only apply inside the content ( .nv-content-wrap class )
NO
- https://vertis.d.pr/i/WUzvop
- Edit a post and add an image block with caption and other image without caption
- Make sure they both have margin bottom
53 min
Closes #3762.

Fix image margin bottom

---

assets/scss/components/elements/_content.scss
assets/scss/components/elements/blog/_comments.scss
assets/scss/components/elements/blog/_single.scss

- This PR fixes the file size limit. Since I removed/replaced some code, we need to retest some issues that may be affected by these changes.
Here's what I've changed in this PR:
- Replaced the variable name for image margin `--contentimgmargin` to `--img-m`
- Removed the code for having a different margin on desktop than on mobile as it wasn't there before
- Remove
```
.comment-content {
flex-grow: 1;
}
```
as the code wasn't necessary anymore.
NO
Please follow the test indications for the following issues:
- https://github.com/Codeinwp/neve/issues/3762
- https://github.com/Codeinwp/neve/issues/3798
- https://github.com/Codeinwp/neve/issues/3790
34 min
Closes #3762, #3798, #3790 https://github.com/Codeinwp/neve/issues/3856

Fix the file size limit

---

.github/workflows/deploy.yml
.github/workflows/playwright.yml

GH secret names of AWS credentials, which are used for GH workflows, were updated to fix dependabot checks are failing.
NO
- GH checks should be green.
Closes https://github.com/Codeinwp/themeisle/issues/1445.

Fix for GH checks of Dependabot PRs are failing

---

inc/views/page_header.php

If the heading layout is "cover", WooCommerce pages seem to have a double title. That's fixed.
YES
Note: The issue is completely related to the Neve Free.
- Install WooCommerce
- Visit Customizer->Layout->Page then choose **Cover** for **Header Layout**
- Make sure the double title issue was fixed in WooCommerce pages such as a cart, checkout, etc. Normal pages and WooCommerce pages behave the same regarding the page header (the title is located only in the header cover.)
- Make sure there is no regression on the page header/title mechanism overall Neve
- ⚠️  Make sure that PR doesn't cause "#3450" issue again.
Closes https://github.com/Codeinwp/neve-pro-addon/issues/2408.

Do not render heading title multiple in WooCommerce pages.

---

assets/scss/components/hfg/frontend/layout/_mobile_sidebar.scss
e2e-tests/specs/customizer/general/custom-global-colors.spec.ts
header-footer-grid/templates/row-wrapper-mobile.php

- In this PR, I moved the `transition: all 0.3s cubic-bezier(0.79, 0.14, 0.15, 0.86);` CSS property to a separate class and added that class in PHP to be able to reduce the CSS size. Before this PR, the property was added to each class and it was taking lot of space ( kudos to @mskapusuz for noticing this )
- I also fixed an e2e test that was failing after the latest modifications in Otter.
NO
The transition property was on menu sidebar on mobile so here's what you need to check:
- The menu sidebar still opens and closes in the same way with the same animation. Here's a video about what's the expected behaviour: https://vertis.d.pr/v/ABtsJM and how the header would open without that transition: https://vertis.d.pr/v/rL4PhB. It should be pretty easy to spot.
- Check if the sidebar opens …

Fix the size limit issue in Neve

---

assets/apps/components/src/Controls/ColorControl.js

In WP 6.2 RC the Gradient component has `gradients` as required even if they are not used.
I'm passing an empty array to not break the component.
NO
1.  Go to the header builder
2. Add a Button component
3. Edit the Style options for the Button
4. Change the Background color for the Button
5. Add a gradient for the background color
6. Check that the control does not break, and that no JS error is thrown.
Closes #3894.

chore: solve gradient issue for wp62rc 

---

inc/compatibility/ppom.php
inc/core/core_loader.php

Neve + PPOM had an visual issue on the single product page, that was causing 'add to cart button' was looking weird.
YES
This is the helper PR of an another PR on the PPOM repo. Please follow up the instructions on https://github.com/Codeinwp/woocommerce-product-addon/pull/108
Closes https://github.com/Codeinwp/woocommerce-product-addon/issues/106.

Fix Neve + PPOM Visual Compatibility on Single Product Page

---

assets/apps/dashboard/src/Components/Sidebar.js
assets/apps/dashboard/src/Components/SupportCard.js
composer-dev.lock

- I've added the support link inside the dashboard
NO
- Test with [this PR](https://github.com/Codeinwp/neve-pro-addon/pull/2463) from Neve PRO, otherwise, you won't see the change. The PR from Neve PRO adds the actual link and the button text to avoid adding new strings
- Activate a license and test that the link points where it should
- Check that the link appears in any tab
- Check that the link disappears when you deactivate the license 
Closes Codeinwp/neve-pro-addon#2428.

Add link to the support form in Neve dashboard

---

assets/scss/components/elements/blog/_single.scss

In this PR, I removed the style of post tags that was applied to the tag cloud widget. That style was only visible for users who disabled the widget editor and switched back to classic widgets. We removed the style that was applying to the gutenberg block tagcloud in Neve 3.1 when we fixed this issue: https://github.com/Codeinwp/neve/issues/3489.
YES
In the above screenshot, you see how the tag cloud appears when added as a block and then how it appears when you added with the widget editor disabled. That's the expected behavior.
- Import the theme unit test data from [here](https://raw.githubusercontent.com/WPTT/theme-unit-test/master/themeunittestdata.wordpress.xml) to avoid adding tags manually
- Go to widgets and add the tag cloud block
- Install …

Font-size for tagcloud

---

.github/workflows/pr-checklist.yml

Excluded `update_dependencies` branch to not run on Dependabot PRs
Excluded Draft PRs
NO
1. Action should not run on Dependabot PRs
2. Action should not run on Draft PRs
Closes #3935.

fix: exclude draft pr and update_dependencies branch #3935

---

header-footer-grid/templates/components/component-logo.php

- Change the title attribute of the logo wrap to be different than the content
- Add `rel="home"` on the link
NO
- Add this version on an online instance of your choice ( TasteWP / InstaWP etc. )
- Check it on https://accessmonitor.acessibilidade.gov.pt/. You should not get "Links with the same text in content and `title` attribute" error.
Closes #3934.

fix: logo accessibility issue [#3934]

---

inc/core/styles/css_prop.php
inc/core/styles/css_vars.php

The problem comes from [this line](https://github.com/Codeinwp/neve/blob/master/inc/core/styles/css_vars.php#L197). We're removing the border width from the padding to have the same button width, no matter the style.
Eg: you have two buttons, one with an outline, and another without an outline, right next to each other. In order for them to have the same size, you need to remove the border width size from the padding. That was working well when we didn't had other unit sizes for the padding control. If the padding is 10EM and we remove 2 from it, we end up with 8EM and not 10EM - 2px.
In this PR i changed what the CSS variable will return, instead of subtract button border width from padding, return `calc(padding.suffix - borderWidth.px)`
https://vertis.d.pr/v/w9QQy5
NO
- Import Neve Web …

Button padding different when using EM unit

---

assets/apps/customizer-controls/src/ordering/OrderingComponent.js

- I removed the js script added in php from Neve Pro ( see https://github.com/Codeinwp/neve-pro-addon/pull/2484 )
- I added the functionality inside the Ordering control, as we do for other controls of this type ( eg. neve_layout_single_(.+)_elements_order )
- I updated the components label from "Price" to "Product Price" to avoid adding any new string
NO
Before this fix:
https://vertis.d.pr/v/f2VboS
After this fix:
https://vertis.d.pr/v/dmXHcO
- Test with this PR: https://github.com/Codeinwp/neve-pro-addon/pull/2484
- Import a WooCommerce starter site
- Install and activate Sparks
- Go to customizer => WooCommerce => Product catalog => Card Content 
- Switch to inline mode for title and price
- Disable title + price or any other elements
- Switch back to left/right/center, the price …

Card content elements control - fix the behavior in customizer

---

inc/compatibility/starter-content/about.php
inc/compatibility/starter-content/home.php
inc/compatibility/starter-content/portofolio.php
inc/compatibility/starter-content/project-details.php

Added the missing spacing to the default starter content.
YES
1. have two instances of Neve, one where you import the Web Agency Starter Site via TPC, and one where you just open the Customizer so that the Starter Content is displayed.
2. Check the spacing for elements on the following pages: Home, About, Portfolio, and Project Details. The elements' spacing should be the same.
Closes #3938.

fix: added spacing to the default starter_content

---

assets/apps/dashboard/src/Components/ModuleCard.js
start.php

Allow a placeholder inside the dashboard controls so that logic from Neve Pro can be added as a component and for cases where specific control logic is used.
In this case, the Restrict content feature saves all the settings within a single option.
Extended the compatibility array to allow for Restrict content to be used only with versions of Neve that support this.
NO
Testing instructions can be found on the main PR: Codeinwp/neve-pro-addon#2444
Closes Codeinwp/neve-pro-addon#1703.

chore: supporting changes for 

---

inc/views/breadcrumbs.php

- Added a way to show breadcrumbs on frontend if they are in HFG's context
This PR is made to support changes from Neve Pro https://github.com/Codeinwp/neve-pro-addon/pull/2490
NO
- Install SEO by Yoast
- Check that the breadcrumbs in lite are still working as before
- With this PR active, https://github.com/Codeinwp/neve-pro-addon/pull/2490, add the breadcrumbs component inside the header. It should show the breadcrumb on frontpage too
Closes Codeinwp/neve-pro-addon#2481.

Fix breadcrumbs not available on frontend

---

assets/scss/components/compat/woocommerce/single/_reviews.scss

Updated the font size for the product tabs section for the H2 tag.
YES
Pic 1
1. Import a Shop Template
2. Check the font size for the `h2` tag under the product tabs. See pic. 1
Closes #3962.

fix: updated font size for product tabs h2

---

header-footer-grid/Core/Components/CartIcon.php

The header cart icon was not using the conditional headers flag and the color setting would not save for each header.
NO
<details open>
<summary>Default Header</summary>
</details>
<details open>
<summary>Shop Header</summary>
</details>
1. Use a Shop Starter Site as a starting point
2. Disable `Show This Header Site-wide` from Global Header Settings
3. Change the colors for the Responsive Search and Cart Icons from the default Header
4. Change the colors for the Responsive Search and Cart Icons from the Shop Header and make sure it is enabled for the products Archive Type
5. Check that the colors are displayed correctly for each Header when used.
Closes Codeinwp/neve-pro-addon#2524.

fix: solve header cart icon 

---

inc/views/nav_walker.php

Fixed the alignment on center when using items that have sub-menus
YES
1. Create a menu, with submenu items
2. Set the Mobile sidebar to the Center
3. Check the mobile menu
Closes #3980.

fix: solve alignment for mobile nav when center #3980

---

inc/admin/dashboard/main.php

For non-admin users the Appearance menu is removed, the new theme page should also be removed if the user does not have the capability and no errors should be thrown. 
YES
1. Check that non-admin users don't experience any errors with the new changes
2. Previously for Editors it would throw an error as the changes we introduced did not check if the appearance menu was present or not. Check other user types as well.
Closes #4004.

fix: solve erros reported for non-admins #4004

---

header-footer-grid/Core/Components/Abstract_FooterWidget.php

I added a null condition for checking the Footer section id.
ℹ️ I could not reproduce the bug. Thus, I suspect it was temporary regression caused by some issue that has been solved. Still, I added the condition to be sure of the feature.
NO
Follow the instruction from the linked issue.
Closes #3982 .

Fix possible null value for Footer section ID 

---

header-footer-grid/Core/Components/MenuIcon.php

Conditioned the JS `onClick` attribute to not be added if the webpage is in AMP mode.
Previously it was added and caused AMP to report issues with the compatibility.
The other reported issues originate from Otter and Feedzy for the linked issue.
NO
<details open>
<summary>Pic. 1</summary>
</details>
<details>
<summary>Pic. 2</summary>
</details>
<details>
<summary>Pic. 3</summary>
</details>
1. On a fresh instance on Neve + Neve Pro, install the [AMP plugin](https://wordpress.org/plugins/amp/)
2. Use the standard Starter Site that is imported when first publishing the Customizer.
3. Activate the AMP plugin and set the **Template Mode** to **Standard** (see Pic. 1)
4. Check the front page, and see if issues are reported for the URL (see Pic. 2)
5. Previously the `onclick` attribute was …

fix: am reported issue #4000

---

assets/apps/dashboard/src/Components/Plugin/InstallActivate.js

The `useState` was creating a render loop since it was dependent on a state that was changed within.
NO
1. On a fresh Neve instance
2. Enable `SCRIPT_DEBUG`
3. Open the browser console
4. Go to **Neve Options** > **Starter Sites**
5. The error from the issue should not be reported.
Closes #4022.

fix: react script loop #4022

---

.distignore
CONTRIBUTING.md
docs/FAQ.md

Added more documentation to the contributing guidelines.
NO
No testing is required as it only contains documentation updates.
Closes Codeinwp/neve-pro-addon#2561.

chore: improve contributing guidelines

---

inc/views/partials/post_meta.php

The Feedzy uses the `global $post` inside the hook that changes the Author.
In order to allow hooks that rely on the global to work properly, I changed the context while rendering the template part
with the post that is dynamically passed.
Also, a cleanup was added at the end to preserve the original global for further code execution.
NO
<details open>
<summary>Import Feed (Pic 1)</summary>
</details>
<details>
<summary>Map Content (Pic 2)</summary>
</details>
<details>
<summary>Map Content (Pic 3)</summary>
</details>
<details>
<summary>Import Posts (Pic 4)</summary>
</details>
<details>
<summary>Featured Posts Sticky (Pic 5)</summary>
</details>
<details>
<summary>Correct Sticky Frontend (Pic 6)</summary>
</details>
1. Create a fresh Neve instance
2. Install Feedzy and Feedzy PRO
3. Go …

fix: set correct post context for author hooks #4011

---

inc/views/nav_walker.php

Add `aria-label` on the dropdown of the sidebar menu.
NO
<details open>
<summary>Pic 1</summary>
</details>
<details open>
<summary>Aria Label</summary>
</details>
1. Create a fresh instance of Neve
2. Import the Web Agency Starter site
3. Check on mobile view if the sidebar dropdown (see Pic 1) has the proper aria-label (you can use Inspect element from the browser).
Closes #4020.

fix: menu dropdown aria attribute #4020

---

inc/admin/dashboard/main.php

Changed capability for the page we register to point back to the Customizer.
The previous capability was `activate_plugins`, now it is set to `manage_options` only for this page.
NO
1. Create a fresh multisite instance that is using Neve or use an existing one and enable Neve
2. Create a user with the role of `Administrator` to use instead of the `Super Admin` account
3. Login with the `Administrator` account
4. Check that you can access the Customizer, previously it will not allow the user as it does not have the capability to activate plugins.
Closes #4033.

fix: solve customizer permissions on multisites #4033

---

readme.md
readme.txt

The new WP update should be released on August 8th https://github.com/Codeinwp/neve-pro-addon/issues/2585

Update WP version to 6.3

---

globals/utilities.php

I've changed the function to make sure that `json_decode` will get the proper parameter type. This should fix user's error and prevent similar things from happening.
**Note:** I could not replicate the issue or see the HS ticket and I saw that the user switched to Hestia. Those changes should prevent the error from happening but I could not properly test if it solves the problem since I don't have access to the user's site.
NO
- Not much to test here as I wasn't able to replicate the issue, just a general check that post-meta defaults are working fine.
Closes Codeinwp/neve-pro-addon#2544.

Check the input type in neve_get_default_meta_value function

---

header-footer-grid/Core/Components/PaletteSwitch.php

This is not exactly a bug as described in the video attached. The problem comes from the fact that we take into consideration the user's last choice inside the customizer. Please see the video for the exact explanation.
What I did here was to actually check if we're inside the customizer and the auto adjust feature is on and if that happens, ignore the user's last pallet choice stored inside the localStorage.
**Note for the code reviewer**: The script is added in PHP so we minimized it there. Here's the unminimized version of the current changes so you could understand it easier:
```php
/**
* Get JS contents from file to use as inline script.
*
* @return string
*/
public function toggle_script() {
$auto_adjust = Mods::get($this->get_id() . '_' . self::AUTO_ADJUST, 0);
$default_state = …
```

Fix for confusing palette switch in customizer

---

assets/apps/metabox/src/components/Sidebar.js
inc/admin/metabox/manager.php

The script where the error occurs shouldn't even be loaded there. It seems like "global $post_type" returns "page" on "widgets.php" so it loads the script. I did a separate check for "widgets.php" page and prevent the script from loading.
I also fixed the script so even if it loads there, it won't throw an error.
NO
- Go to widgets.php / customize.php and make sure the error doesn't appear anymore.
- Go to a post type ( cpt, page, posts etc. ) single post editor and make sure the neve sidebar is still visible
Closes #4069.

fix: neve meta sidebar error on widgets.php [#4069]

---

assets/scss/components/elements/_mega-menu.scss

- Removed a display none that was causing AMP not to remove the overlay over the images in Mega Menu
I checked https://vertis.d.pr/hNU3z0 that was the reason for adding that display none. The issue in the video is not happening.
NO
1. Go to WordPress Dashboard > Neve > Neve Options > Neve Pro and enable the Mega Menu setting.
2. Go to your WordPress Dashboard > Appearance > Menus and create a Mega Menu there and [place an image there](https://share.getcloudapp.com/eDuEE254) as I did. 
3. Go to Plugins > Add New and install and Activate AMP Plugin. https://wordpress.org/plugins/amp/
4. Go to AMP > Settings and set the Template Mode to Standard if it's not already that.
5. Place your the Menu in Header using the Customizer > Header Builder
6. Check the image on the frontend 
7. Double-check …

Images not loading in mega menu with AMP

---

assets/apps/customizer-controls/src/global-colors/PaletteForm.js
inc/core/admin.php

Added text domain to strings in PaletteForm.js
Fix to admin.php file for displaying color palette and SS notice text translations
YES/NO
1. Install Poedit and generate a language file, you can use this video: https://www.youtube.com/watch?v=HzcZeNZu7To&ab_channel=AuroobaMakes. 
2. Translate "Try one of our ready to use Starter Sites" which is the button text of our welcome notice
3. In WordPress, switch to your new language in dashboard settings
4. Check the notice button text 
Closes #4096

Fix: [i18n] Added text domain to strings

---

assets/apps/metabox/src/components/MetaFieldsManager.js
e2e-tests/specs/editor/page.spec.ts
inc/views/pluggable/metabox_settings.php

Decrease the opacity of the Editor Title if the disabled title toggle is active from the editor Neve Options.
YES
<details open>
<summary>Title visual cue (Pic 1)</summary>
</details>
<details>
<summary>Neve Page Options (Pic 2)</summary>
</details>
**Check Title visibility**
1. On a new Instance of Neve create a new page
2. Add a title
3. Check that when you disable the title from Neve Options of the page (see Pic 2) the title is less visible (see Pic 1)
**Check Defaults**
Check that when you reload the page the visual cues are correctly applied.
Closes Codeinwp/neve-pro-addon#2550.

feat: show visual cue for disabled title inside editor

---

assets/apps/dashboard/src/Components/Content/StarterSitesUnavailable.js
assets/apps/dashboard/src/Components/PluginCard.js
assets/apps/starter-sites/src/ss-try-button/SSTryButton.tsx
inc/core/admin.php

Change the redirect button link to the new onboarding.
NO
- Please install this version of Neve
- Go to Neve's dashboard and check the Starter Sites tab
- Install TPC from there. After the installation, the redirect to the new onboarding should happen.
- The same thing should happen when you install TPC from Neve Dashboard plugins tab and from About Us
- I don't recall to be other TPC installations but please have another look and see if I missed something
Closes Codeinwp/templates-patterns-collection#289

Fix redirect to new onboarding

---

assets/apps/components/src/Common/DropdownFix.js
assets/apps/customizer-controls/src/builder/components/ComponentsPopover.tsx
assets/apps/customizer-controls/src/font-family/FontFamilySelector.js
assets/apps/customizer-controls/src/repeater/IconSelector.js

- Fix the popover issue that appears in WP 6.4. The source of it comes from https://github.com/WordPress/gutenberg/pull/53889
NO
- Please test if the problems mentioned inside the issue's body are fixed
Closes #4107.

Popover issues in wp 6.4

---

inc/views/partials/post_meta.php

This was triggered only when also using the Author meta.
References: #4011
This was a bug introduced with the changes from #4011 the `wp_reset_postdata` would reset the secondary query back to the main query. It should not be required and have both issues fixed without the need for resetting the post data.
NO
<details open>
<summary><h4>Related Posts displaying correct excerpt</h4></summary>
</details>
<details>
<summary><h4>Sticky Post Author Name</h4></summary>
</details>
<details open>
<summary><h4>Test Related Posts Exerpt</h4></summary>
1. Enable the related posts section on the single post
2. Add two, three, or more articles in the same category
3. Check a post.
4. Each post should display the correct excerpt, previously it would show the excerpt from the main post.
5. Check the …

fix: Related Posts Exerpt

---

.github/workflows/test-php.yml
tests/test-neve-dynamic-selector.php

Use the same PHP version running for Lint and PHPUnit as in PHPStan.
> [!NOTE]  
> PHPUnit 9 will be used to run the tests.
NO
Just an update to dev tools. Nothing should be changed in the build.
Closes #4169

chore: use 7.4 for PHP tests

---

inc/views/nav_walker.php

Changes the spacing between the text and submenu toggle to keep the elements aligned to the center on mobile even when a submenu is not present. 
It also accounts for the previous fix for the submenu alignment https://github.com/Codeinwp/neve/issues/3980 ie. it keeps the elements aligned when the submenu toggle is present.
YES 
[Alignment on mobile when submenu is present](https://vertis.d.pr/i/qiCpTO)
[Alignment for the secundary menu when submenu's are defined for the primary menu](https://vertis.d.pr/i/Nwokuk)
First we need to test that the secundary menu is aligned to center on mobile as in the issue description: 
1. Create a primary and a secondary menu, without any submenus
2. Add the primary menu on desktop and the secondary menu in the mobile sidebar
3.  Set the mobile sidebar …

fix: alignment of secondary menu on mobile #4015

---

assets/scss/components/compat/woocommerce/_checkout.scss

Fixes the coupon code button on the WooCommerce checkout page when using the WooCommerce blocks.
YES
1. On an instance with Neve, Neve Pro, and WooCommerce 8.3
2. Change the checkout page to use blocks
3. Check that when clicking `Add discount Code` the input and button display correctly, previously the button would take up all the space available.
Closes Codeinwp/neve-pro-addon#2697

fix: woo block checkout cupon button Codeinwp/neve-pro-addon#2697

---

assets/scss/components/compat/woocommerce/_breadcrumbs.scss

This [property ](https://github.com/Codeinwp/neve/blob/388f8d7485c81c7633030ed39b610bd5c0efd758/assets/scss/components/compat/woocommerce/_breadcrumbs.scss#L6)prevents long breadcrumb names from wrapping, thus creating an overflow that was inaccessible to the user. 
To solve this, I made the breadcrumbs scrollable like on the [reference point](https://www.emag.ro/masina-de-spalat-rufe-arctic-8-kg-1000-rpm-clasa-c-motor-silent-inverter-extrasteam-alb-apl81023xlw0/pd/D4YDZ3MBM/ )
NO
https://github.com/Codeinwp/neve/assets/17597852/2c687fab-dd08-4321-80ef-392420eb524b
- Have WooCommerce with some long product names
- On Mobile, check if the breadcrumbs are scrollable.
Closes #4112

fix: make woo breadcrumps scrollable

---

assets/apps/customizer-controls/src/repeater/RepeaterItemContent.js
start.php

Added some support chages for custom payment icons feature in PRO
NO
- Nothing to test here, check the PR from Neve Pro
Closes Codeinwp/neve-pro-addon#2549.

Support changes for custom payment icons in pro

---

assets/scss/components/compat/woocommerce/_notices.scss

With the release of WooCommerce v8.5.0, the notices have been changed to use a new HTML structure.
I added new rules to style the notices as they were previously based on the customizer settings.
NO
<details>
<summary>Product notice BEFORE wc.8.5</summary>
</details>
<details>
<summary>Product notice AFTER wc.8.5</summary>
</details>
<details>
<summary>Cart notices BEFORE wc.8.5</summary>
</details>
<details>
<summary>Cart notices AFTER wc.8.5</summary>
</details>
<details>
<summary>Checkout notices BEFORE wc.8.5</summary>
</details>
<details>
<summary>Checkout notices AFTER wc.8.5</summary>
</details>
- 
- 
Closes #4189.

fix: woocommerce notices for wc8.5 #4189

---

assets/scss/components/elements/blog/_single.scss

The text alignment CSS property for the title in Single Post was only used when the option `Cover Container` had `contained` as a value. For value `Full Width`, it was missing because the CSS property was only on `.container` selector.
Moving the CSS property to parent `.nv-post-cover` solves this issue.
YES
https://github.com/Codeinwp/neve/assets/17597852/0d3fee57-0035-4a9f-a272-3eae8d4dbfe6
- Make a long title for the Post
- Go to Customizer > Layout > Single Post
- Modify the `Cover Container` like in the video
Closes #4018

fix: single post title alignment on full width

---

header-footer-grid/templates/components/component-logo.php

Changed the tag for `site-title` on mobile to use `p` instead of `h1` the same as for all other pages where the site title should not be the main title. SEO will now see only the `h1` used by the desktop on the homepage where usually no other main title is present.
NO
1. Create a new instance with Neve and set the home page to your latest posts
2. Add the Logo & Site Identity component
3. Set a site title if not already set
4. Enable `Show Site Title`
5. Check on the front-end homepage that only one h1 tag is present.
Closes #3984.

fix: SEO site-title tag for homepage

---

inc/core/front_end.php

Not having HTML5 support for scripts might impact some users who use specific plugins. More context about the problem [here](https://wordpress.org/support/topic/popular-posts-disapeared-after-wp6-4-update/#post-17184460)
NO
- Make sure that the build is OK.
Closes #4167

Enable full HTML5 theme support

---

assets/js/src/frontend/hgf.js
assets/js/src/frontend/navigation.js

By default, the search input is positioned on the left or the right of the search icon, depending on the position. The input popup might be partially offscreen if the search icon is in the middle of a position not too close to the edge.
To solve this, I added an extra step that rechecks if the search input fits. If not, I add an extra offset on the X-axis, which solves the offscreen bug. ℹ️ This is the solution with the least amount of code, which helps us to stay below the limit.
> [!TIP]
> Create an alias for `document.window` to save space. The build does not do an aggressive optimization to do this step automatically.  
YES
- Like in the issue, position the icon search near the middle and check in a small window.
Closes #4017

Fix wrong position of search input on minimal when it does not fit in the space.

---

e2e-tests/fixtures/customizer/hfg/footer-mobile-setup.json
e2e-tests/specs/customizer/hfg/hfg-copyright-component.spec.ts
e2e-tests/specs/customizer/hfg/hfg-footer-menu-component.spec.ts
e2e-tests/specs/customizer/hfg/hfg-footer-mobile.spec.ts
header-footer-grid/Core/Builder/Footer.php
header-footer-grid/functions-migration.php
header-footer-grid/templates/footer-row-wrapper.php
inc/compatibility/starter-content/theme-mods.php

Allow mobile layout for the Footer Builder in HFG.
YES
<details>
<summary>Footer Desktop/Mobile builder (Pic. 1)</summary>
</details>
1. On a fresh instance of Neve
2. Go to "Customizer" > "Footer"
3. Check that the "Mobile" tab is available for the builder (see Pic. 1)
4. Check that on the front-end the items from the Desktop are also displayed in Mobile view without changing anything.
5. Change just one of the views (Mobile or Desktop)
6. Check on the front-end that each footer is displayed correctly for the view (Mobile/Desktop)
7. Check that it works as expected with Neve Pro
Closes Codeinwp/neve-pro-addon#2504.

feat: add mobile support for the footer in HFG

---

e2e-tests/specs/customizer/hfg/hfg-menu-item-description.spec.ts
inc/views/nav_walker.php

Do not show item descriptions in regular navigation.
Added e2e test for this specific case.
YES
1. On a fresh instance of Neve FREE
2. Change an existing menu item to have a description or use a category with a description as a menu item.
3. Check that the description is not visible inside the navigation when the item is nested under a main item.
Closes #4199.

fix: description visible in regular menu

---

inc/views/template_parts.php

During the `render_block_data` filter we check if the rendered block is a `core/post-excerpt` block and we disable our excerpt addon for the first call after the `render_block_data` hook. 
NO
Duplicate read more is no longer present when the excert more block is used: https://vertis.d.pr/i/aqx1p7 and works as excepted in the rest of the cases: https://vertis.d.pr/i/uAYkUZ .
Check the instructions from the linked issue for replication. The `read more` should not be doubled anymore. 
Closes https://github.com/Codeinwp/neve/issues/4187.

fix: disable excerpt more filter when excerpt block is used

---

assets/scss/components/elements/_mega-menu.scss

Override calculated styles for the mega-menu as it uses a different display style for the dropdown.
The `translateX` changes were introduced here: https://github.com/Codeinwp/neve/pull/4165 previous properties like `right` and `left` are overridden by mega-menu styles the `translateX` were not as it was not expected there.
YES
1. On a fresh instance with Neve and Neve PRO
2. Enable the Mega Menu and use it for the Primary Menu.
3. Check that on the front end for the emulated tablet (iPad), it opens and displays correctly.
Closes: Codeinwp/neve-pro-addon#2769.

fix: mega menu opening on tablet

---

assets/apps/customizer-controls/src/builder/components/BuilderItem.tsx
assets/apps/customizer-controls/src/builder/components/ComponentsPopover.tsx
assets/apps/customizer-controls/src/builder/components/Slot.tsx

Improve the tracking for components of the Header/Footer Builder in Customizer:
- track the device (desktop, mobile)
- improve the tracking id to differentiate between device and builder type.
NO
- Have Neve Pro installed
- Active the anonymous tracking in Neve Dashboard
- Go to Customizer in Header Builder, then open the Browser Console
- Add components into the builder, either via drag-and-drop or Popup
- In the browser console, write `tiTrk.events`
- You should see something similar to the image below (Notice the `device` property)
Closes https://github.com/Codeinwp/neve-pro-addon/issues/2776

Tracking improvements for Header/Footer Builder in Customizer

---

e2e-tests/specs/customizer/hfg/hfg-footer-mobile.spec.ts
header-footer-grid/templates/footer-row-wrapper.php

Solves the issue with the footer not having a unique ID since mobile was introduced.
NO
1. Check on any page where the footer is being used that there is only one element with `id` any of the IDs: 
- `cb-row--footer-desktop-top` 
- `cb-row--footer-mobile-top`
- `cb-row--footer-desktop-bottom` 
- `cb-row--footer-mobile-bottom`
- `cb-row--footer-desktop-main` 
- `cb-row--footer-mobile-main`
Closes: #4212.

fix: footer id unique

---

inc/admin/dashboard/main.php

Remove survey from dashboard script deps.
NO
https://github.com/Codeinwp/neve/assets/17597852/ad02b80d-2b9c-4bcb-9080-b74d1ad0de7e
- Check the script loading in Neve dashboard like in the video
Closes https://github.com/Codeinwp/neve-pro-addon/issues/2785

fix: remove survey from dash deps

---

e2e-tests/specs/customizer/hfg/hfg-menu-item-wrap.spec.ts
inc/views/nav_walker.php

Fixes long items with a dropdown on the mobile menu overlapping with the dropdown button.
YES
1. On a fresh instance, create a primary menu
2. Add some items with longer names
3. Add subitems to them so the submenu icon will be visible
4. Check on the mobile menu that the text will not overlap with the dropdown icon.
Closes #4226.

fix: long menu items with toggle overlap

---

inc/compatibility/woocommerce.php

Because we were using `new WC_Payment_Gateways`, we added duplicate filters in the loop, which resulted in duplicate behavior when rendering the bank details.
By using the singleton pattern provided by the class via `WC_Payment_Gateways:instance()`, we prevent this bad behavior. 
To find where the problem was, I first printed the stack trace on the function that renders the bank details and then checked all Neve functions that were used. There was nothing problematic with them; there were no multiple calls.
This leads me to the idea that some filter was added multiple times, so I printed the stack trace of the `WC_Payment_Gateways` constructor, which revealed the Neve function that added the filter multiple times.
NO
- Use WooCommerce
- Activate `Direct bank transfer` in Payments tab of …

fix: use `WC_Payment_Gateways` instance

---

inc/core/admin.php

- Changed the primary hero button to be more flexible and not break the layout when it contains a large text (generated by the translations).
- Also balanced the design. (centered text and lower line-height, thanks to @mghenciu )
NO
- In fresh instances with the Romanian Language, install Neve. (Alternatively you can edit the HTML directly in the page to add some extra text )
- Check the onboarding notice.
> [!NOTE]
> When testing with TasteWP,  make sure do not have Neve installed already when you try to put the new build. TasteWP might server some cached file!
Closes https://github.com/Codeinwp/neve/issues/4240

fix: hero btn onboarding on large text

---

inc/views/nav_walker.php

Fixed extra `&` in CSS syntax.
NO
1. On a fresh Neve instance check no W3C Validation errors are shown.
Closes #4251.

fix: solve css syntax

---

inc/compatibility/starter-content/contact.php
inc/compatibility/starter_content.php

I've reverted the starter site menu items, due to the 404 pages issue with a new release.
Closes #2823

Revert starter site menu items

---

header-footer-grid/Core/Components/SecondNav.php
header-footer-grid/templates/components/component-nav-secondary.php

When the page load, I count the number of secondary menus and add it to the nav menu wrap ID.
e.g: `secondary-menu_2`
ref: https://github.com/Codeinwp/neve/blob/master/.storybook/dummy-data.js#L514
1. Create Wordpress site with Neve.
2. Add a header element to both desktop and mobile view (for example a secondary menu)
3. Save
4. The HTML source will contain duplicate id values (e.g. secondary-menu)
Closes #4256

Fixed duplicate id issue with secondary nav menu

---

inc/views/breadcrumbs.php

This fixes Breadcrumb NavXT breadcrumb rendering which was removed by in ee748ab1469559c56dd26444089e0cf8646e7e36 (by mistake I assume).
I tested the change (in prod :wink:) on my [WordPress/WooCommerce installation](https://42keebs.eu/build-guides/lumberjack-pro/).
This change re-adds the code that calls the `bcn_display()` Breadcrumb NavXT function to display the breadcrumbs.
YES (I guess? It adds breadcrumbs that have been missing)
- Install WordPress with Neve
- Install Breadcrumb NavXT and enable breadcrumbs
- Breadcrumbs **will not** be rendered
- Update the Neve code with this PR
- Breadcrumbs will now be rendered correctly
Closes #4267.

Fix Breadcrumb NavXT breadcrumb rendering

---

taxonomy-download_category.php
taxonomy-download_tag.php

Fixes https://github.com/Codeinwp/neve/issues/4286 by moving the apply "Before Download Archive" hook to above the download grid div.
YES
See reproduction steps in https://github.com/Codeinwp/neve/issues/4286
- 
- 
Closes #.

Fix #4286 EDD Before Archive Hook

---

assets/apps/customizer-controls/src/repeater/RepeaterItemContent.js
stories/utils/values.js

In this PR, I've hidden the `Page Name` option if the user does not select the messenger social media option. 
I've registered the `Page Name` and added messager support in this PR https://github.com/Codeinwp/neve-pro-addon/pull/2852
Closes https://github.com/Codeinwp/neve-pro-addon/issues/2788

Added messenger social media support

---

header-footer-grid/templates/components/component-logo.php

I've used arrows unicode to fix the issue with `TranslatePress`
Closes https://github.com/Codeinwp/neve/issues/4301

Fixed compatibility issue TranslatePress plugin

---

inc/core/admin.php

In this PR, I've hidden the welcome notice if the current user does not have `install_plugins` permission.
Closes https://github.com/Codeinwp/neve/issues/4117

Fixed the plugin install issue with multisite

---

inc/views/template_parts.php

In this PR, I've fixed the PHP warning.
Please follow the test instructions provided in the issue description or use the code snippets below.
`add_filter( 'neve_read_more_args', '__return_false', 99 );`
Closes https://github.com/Codeinwp/neve-pro-addon/issues/2854

Fixed PHP warning in template_parts.php

---

assets/scss/components/main/_gutenberg.scss
inc/views/template_parts.php
package.json

Fixed issue with WP default lightbox model.
1. Add an image block
2. enable “Expand on click” for the image
3. change the alignment of the image ( left/right/center) -> when an alignment option (other than None ) is enabled, the image doesn't expand to full width
Closes #4260

Fixed lightbox issue with alignment control

---

e2e-tests/specs/customizer/layout/single-post-settings.spec.ts
inc/customizer/defaults/single_post.php
inc/customizer/options/layout_single_page.php
inc/customizer/options/layout_single_post.php
inc/views/cover_header.php
inc/views/post_layout.php

In this PR, I've fixed the cover layout issue with CPT.
Closes #4062

Fixed cover layout issue with CPT

---

assets/scss/components/elements/navigation/_nav-menu.scss

I resolved the text wrapping issue in the mobile nested submenus.
Closes Codeinwp/neve-pro-addon/issues/2868

Fixed submenu text wrapping issue on mobile

---

assets/apps/dashboard/src/Components/Deal.js
inc/admin/dashboard/main.php

Include Tier 1 Pro for BF promotion on Dashboard
NO
Must be used with https://github.com/Codeinwp/themeisle-sdk/pull/269
- Set the instance date between 25 NOV and 3 DEC to trigger Black Friday banner
- You should see the banner on the Library page.
- You should NOT see the banner if it is not a Blackfriday Interval
Closes https://github.com/Codeinwp/themeisle/issues/1688

feat: show BF banner for Tier 1 Pro and Free

---

e2e-tests/specs/customizer/general/custom-global-colors.spec.ts
e2e-tests/specs/customizer/hfg/hfg-menu-item-description.spec.ts
inc/admin/dashboard/main.php
inc/compatibility/web_stories.php
inc/core/core_loader.php
start.php

I have removed the early translation function call following [WordPress standards](https://make.wordpress.org/core/2024/10/21/i18n-improvements-6-7/).
Closes https://github.com/Codeinwp/neve/issues/4322

Fixed load textdomain issue with WP 6.7

---

assets/scss/components/compat/woocommerce/_notices.scss

Fixed WooCommerce notices icon issue with mobile screen.
Closes https://github.com/Codeinwp/neve/issues/4319#event-15262468572

Fixed WC icon display issue with notices

---

e2e-tests/specs/customizer/general/custom-global-colors.spec.ts
e2e-tests/specs/customizer/hfg/hfg-menu-item-description.spec.ts

Update some selectors for the recent WordPress update.

fix(test): update element selectors

---

assets/apps/starter-sites/src/ss-try-button/SSTryButton.tsx
e2e-tests/specs/admin/tpc-notice-install.spec.ts
inc/core/admin.php

Make the onboarding notice similar to the one in Raft and screenshot on the issue.
YES
- Install Neve in a fresh instance
- Check if the button works
- Check if the layout is ok
Closes https://github.com/Codeinwp/neve-pro-addon/issues/2909

refactor: onboarding notice

---

header-footer-grid/templates/components/component-logo.php

Remove `title` attributes with its arrow value since we already have `aria-label` 
NO
- Check if the `title` no longer appears.
Closes https://github.com/Codeinwp/neve-pro-addon/issues/2930

fix: remove unnecessary title attributes from brand elements

---

inc/admin/metabox/manager.php

Use the Post Type registered display name as the label instead of using the database slug.
NO
- Check if the label is displayed correctly.
Closes https://github.com/Codeinwp/neve-pro-addon/issues/2938

fix: use post type label in meta box settings

---

assets/apps/dashboard/src/Components/Content/Start.js
inc/admin/dashboard/main.php

Redirect to Onboarding when clicking on the `Starter Sites` button in the Dashboard.
NO
- After installing TPC, click on the `Starter Sites` button in the Dashboard and see if you are redirected to the Onboarding workflow
> [!NOTE]
> For sidebar sub-menu, use this https://github.com/Codeinwp/templates-patterns-collection/pull/423
https://github.com/user-attachments/assets/bef65930-c935-4a1d-9211-e20182de253d
Closes https://github.com/Codeinwp/neve-pro-addon/issues/2910

Redirect to Onboarding

---

inc/admin/dashboard/main.php
inc/admin/hooks_upsells.php

- Add new UI elements for the header section (backward compatible).
- Bring the Custom Layout `edit.php` with a new upsell modal.
YES
> [!NOTE]
> Test together with https://github.com/Codeinwp/neve-pro-addon/pull/2968 to get the new table enhancement.
- Check if the changes do not have regressions.
Closes https://github.com/Codeinwp/neve-pro-addon/issues/2927

Custom Layout Dashboard Refactor

---

assets/apps/customizer-controls/src/controls.js
assets/apps/customizer-controls/src/starter-content/Notice.js
assets/apps/customizer-controls/src/starter-content/StarterContentNotice.js
assets/customizer/css/_generic.css
inc/customizer/loader.php

Show a notice if the Starter Content is being used.
YES
- On a new instance, if the Starter Content is being used, the notice should be visible in the Customizer Sidebar
Closes https://github.com/Codeinwp/neve-pro-addon/issues/2919

feat: add starter content notice and dismissal functionality

---

inc/core/admin.php

Remove property that is not compatible with Safari.

fix: safari compatibility with image width on onboarding notice

---

functions.php

We should use a lower value than `tested_up`.

fix: use 2.9 for required in compatibility with NevePro

---

inc/admin/hooks_upsells.php

Allow the user to close the modal for Custom Layout upsell. The modal appears every time the user enters the page, and if it is closed, it reappears if the user presses on `Add New Layout`.
YES
https://github.com/user-attachments/assets/cd90921f-a684-485d-8128-2dfca42a23d2
- Check the upsell modal close workflow.
Closes https://github.com/Codeinwp/neve-pro-addon/issues/2927

refactor: allow closing the upsell modal for Custom Layout

---

inc/customizer/traits/features_upsell.php

Use the upsell link for the feature comparison link in the Customizer Upsell comparison sections.
NO
- Check the links
Closes https://github.com/Codeinwp/neve-pro-addon/issues/2954

refactor: use upsell link for feature comparison

---

assets/apps/dashboard/src/Components/Common/Notification.js
assets/apps/dashboard/src/Components/Content/Changelog.js
assets/apps/dashboard/src/Components/Content/FreePro.js
assets/apps/dashboard/src/Components/Content/ModuleGrid.js
assets/apps/dashboard/src/Components/Controls/ControlWrap.js
assets/apps/dashboard/src/Components/Header.js
header-footer-grid/Core/Builder/Footer.php
inc/admin/dashboard/main.php
inc/admin/hooks_upsells.php

Reviews some translations changes done during the 4.0.0 review.
- Ensures that when using `Pro` we use `PRO` as this was available previously and already translated;
- Removes translations from Plugin / Theme name i.e. `Neve` | `Neve Pro`;
- Removes `Version` in the Changelog dashboard tab (using just `v` instead);
- Removes translation for the testimonial itself and the author name in the Custom Layouts page;
- Removes translations for all the plugins names in the Recommended plugins section;
YES (only on the backend)
* ~[] I have [written a test](CONTRIBUTING.md#writing-an-acceptance-test) and included it in this PR~
Closes Codeinwp/neve-pro-addon#2979

chore: translations review

---

inc/core/front_end.php
inc/views/nav_walker.php

Detaches the inline style for sidebar visibility from the nav walker class which is only instantiated when we have a menu component in the header.
NO
- Remove all menus (primary & secondary) from desktop/mobile header;
- The mobile sidebar should work;
Closes Codeinwp/neve-pro-addon#2973.

[Fix] Mobile nav sidebar not working when no nav menu in header

---

assets/scss/components/elements/blog/_pagination.scss

Restricts width of pagination input to 75px.
NO
- Make sure the blog has at least a few pages so you can check this fix;
- Set **Post Pagination** to **Number & Search Field**;
- The input should be restricted to a reasonable width;
Closes Codeinwp/neve-pro-addon#2698.

[Fix] Pagination number input too wide

---

assets/scss/components/editor/_typography.scss
assets/scss/components/main/_gutenberg.scss

- Updates styles for quote block according to Codeinwp/neve-pro-addon#2945.
- Make sure that quote block styling is consistend between frontend and the editor.
- Removes deprecated block styles for the quote block - i.e. `Large` style which has been removed (it will fallback on the default quote block style).
YES
<details>
<summary>Editor</summary>
</details>
<details>
<summary>Frontend</summary>
</details>
- Add quote blocks in a page/post
- Styling should be consistent between frontend and editor
Closes Codeinwp/neve-pro-addon#2945.

[Fix] Quote block style consistency between editor & frontend

---

assets/scss/components/elements/navigation/_nav-menu.scss

Fixes issue with dropdown caret icon size setting from Neve Pro not working in the sidebar menu.
YES
- Install this version (without pro);
- The caret icon for doropdowns should work just as before for the free version;
- Install and activate the Pro version;
- The icon size control should work for the menus in the mobile sidebar;
Closes Codeinwp/neve-pro-addon#2483.

[Fix] nav caret icon size not working on mobile/tablet

---

assets/customizer/css/tabs.css
header-footer-grid/Core/Builder/Abstract_Builder.php

Adds shortcut pointing to the Global Header Background in all header rows when advanced settings are turned off
NO
- Go to **Customizer > Header > Global Header Settings**;
- Disable the `Enable Advanced Options` setting;
- The Header Background control should appear in the section;
- If you now go to any of the Header Builder rows, under the **Style** tab, the Background control should be hidden;
- A shortcut to the Background control in the **Global Header Settings** section should be visible;
Closes Codeinwp/neve-pro-addon#2858.

[Fix] Adds shortcut to clarify header background controls

---

assets/apps/dashboard/src/Components/Content/Sidebar/LicenseCard.js
assets/apps/dashboard/src/utils/module-observer.js
inc/core/core_loader.php

Fixes license card state for `active_expired` status - previously it wasn't showing the state at all;
Adds new hook before theme modules loading: `neve_before_modules_load`;
NO
- Use Neve Pro with this PR.
- Refer to this comment https://github.com/Codeinwp/neve-pro-addon/issues/2994#issuecomment-2865898694.
- Switch license states, the UI should update properly for `active_expired`.
Supporting PR for Codeinwp/neve-pro-addon#2994.

[Fix] License card UI & adds action before theme modules loading

---

inc/core/styles/frontend.php
inc/customizer/options/layout_single_post.php
inc/views/post_layout.php

Adds new settings for the single post thumbnail when using the `Normal` header layout option.
NO
- Check the **Blog > Single Post** panel;
- Under the elements ordering, inside the thumbnail panel there should be two select settings;
- The settings should work as expected;
- The settings should only be available when using the "Normal" header layout;
- When switching from the old version to this one, the settings should not affect the frontend;
Closes Codeinwp/neve-pro-addon#2934.

[Feat] Adds image size options to single post thumbnail

---

header-footer-grid/Core/Magic_Tags.php

Fixes issue with `{current_single_content}` magic tag that was over-escaped, not allowing post HTML.
NO
- Please refer to the[ initial issue](https://github.com/Codeinwp/neve-pro-addon/issues/2992) for testing steps as they are defined perfectly well there as well.
Closes Codeinwp/neve-pro-addon#2992.

[Fix] current_single_content magic tag was over-escaped

---

assets/scss/components/compat/woocommerce/_product.scss

Fixes issues with Gallery for Woocommerce plugin;
Improves how we treated layout on single product page;
NO 
- Follow initial issue for testing steps: Codeinwp/neve-pro-addon#2943
Closes Codeinwp/neve-pro-addon#2943.

[Fix] Gallery for WooCommerce conflict & improve product layout

---

header-footer-grid/Core/Components/Abstract_Component.php
header-footer-grid/Main.php
start.php

Supporting changes for https://github.com/Codeinwp/neve-pro-addon/pull/3019.
Also fixes a bug where some font families were not properly added in the customizer preview. 
You can see the bug if you change the submenu font family and use a setting that does a customizer refresh, or run this code in the browser console: 
`window.top.wp.customize.previewer.refresh();`
The font family will be broken for the submenu items.
NO
- This pull request should break nothing by itself; 
- It contains supporting changes for https://github.com/Codeinwp/neve-pro-addon/pull/3019
Ref: Codeinwp/neve-pro-addon#2937.

[Chore] Supporting changes for component styles

---

header-footer-grid/Core/Components/MenuIcon.php
header-footer-grid/templates/components/component-menu-icon.php
header-footer-grid/templates/row-wrapper-mobile.php

Reworks nav menu icon component options:
- removes some of the icon options - we chose to remove all options which only had a different animation but the same graphic;
- adds a shortcut to edit the sidebar open behavior;
YES
> [!NOTE]
> This is adapted to work with [this PR](https://github.com/Codeinwp/neve-pro-addon/pull/3020), but there should be no errors when using the old production version.
- When the user had one of the options which was removed, they will have the default option enabled on frontend;
- When using this in conjunction with the Pro version from production, the removed options will fallback to the default one;
- The shortcut and the options should work as expected;
Closes Codeinwp/neve-pro-addon#3003.

[Feat] Rework nav menu icon options & add shortcut

---

assets/apps/customizer-controls/src/builder-instructions/Instructions.tsx
assets/apps/customizer-controls/src/builder/components/Builder.tsx
assets/apps/customizer-controls/src/builder/scss/_customizer-adjustments.scss
assets/apps/customizer-controls/src/builder/scss/_instructional-section.scss
assets/apps/customizer-controls/src/builder/scss/_rows.scss
assets/apps/customizer-controls/src/scss/_general.scss
header-footer-grid/Core/Builder/Footer.php
header-footer-grid/functions-template.php
header-footer-grid/templates/footer-row-wrapper.php
inc/core/front_end.php
inc/core/migration_flags.php
inc/customizer/options/upsells.php
tests/test-neve-migration-flags.php

1. Make mobile footer inherit components from desktop if empty;
2. Center copyright on mobile;
3. Copyright footer enhancements;
NO
- Install this version of the theme;
- Make sure all components are removed on the mobile version of the footer;
- An overlay should appear, informing the user that the mobile footer inherits the desktop;
- If you dismiss it (click enable), it will not appear again for the current page load;
- The footer components from desktop should be inherited on mobile screen-size on the frontend;
- If there are components in the mobile version of the footer, these will be displayed instead;
<details><summary>Overlay Screenshot</summary>
<p>
</p>
</details> 
---
- Install this version of the theme;
- On the frontend, the copyright should be centered on mobile screen …

[Feat] Footer enhancements

---

assets/apps/dashboard/src/Components/Content/Settings.js
inc/admin/dashboard/main.php

Adds button to Sparks settings page inside the neve dashboard 
NO
- Install and activate Sparks;
- Open the dashboard page, the link to sparks settings should be there and work;
Closes https://github.com/Codeinwp/neve-pro-addon/issues/2890.

[Feat] Sparks integration improvements

---

inc/compatibility/woocommerce.php

Fixes edge case fatal error where session was null on the return from `WC()` method.
NO
Couldn't replicate so not really sure how to test.
Closes Codeinwp/neve-pro-addon#2998.

[Fix] Fatal error edge case in WooCommerce checkout 

---

assets/scss/components/compat/woocommerce/_notices.scss

Fixed broken notice layout on cart and checkout pages.
Closes https://github.com/Codeinwp/neve-pro-addon/issues/3034

Fixed broken notice layout
